### ISSUE TITLE
Fuel fuel level show wrong

### ISSUE THREAD

**Issue by JuhaFIN1** [itchannel/fordpass-ha#103]
Hello. Our Focus 2020 shows fuel level correct in car and Ford Pass App on iphone, but home Assistant show random % ... now there in 50% on tank and HA shows 5%.

**Comment by schlaggi** [comment]
Can you share some screenshots or something? I had a similar problem with the Focus, maybe there is more to it than expected...

**Comment by JuhaFIN1** [comment]
![fordpass](https://user-images.githubusercontent.com/70380474/121852730-90e7d400-ccf8-11eb-9109-309f630047d2.png)
Here is :)

**Comment by schlaggi** [comment]
Yeah that's exactly the same problem I had. For more details look at this issue: https://github.com/itchannel/fordpass-ha/issues/101

> Okay I was able to help myself with a template sensor:
> 
> ```
> template:
>   - sensor:
>     - name: "Fordpass Fuel (Correct)"
>       unit_of_measurement: "%"
>       icon: 'mdi:gas-station'
>       state: >
>         {% if state_attr('sensor.fordpass_fuel', 'fuelLevel') > -5 %}
>           {{ states('sensor.fordpass_fuel') | int }}
>         {% else %}
>           {{ states('sensor.fordpass_fuel_correct') | int }}
>         {% endif %}
> ```
> 
> This sensor now always shows the value of sensor.fordpass_fuel, as long as it is not -5 or below.
> 
> Thanks anyway 🙂

The problem with the solution I came up with is, that it won't show anything after a server reboot if your sensor already shows "-5".
But that's an edge case I can live with. If you have improvements fell free to share!

**Comment by JuhaFIN1** [comment]
Nice! That worked for me now!! :) Thank you very much!

**Comment by itchannel** [comment]
I will add this to the list to look at if it seems to be a thing Ford have done for some models of cars. Seems weird they would regress to not storing the value but we could store the previous value or the API might have another field we can use if the gauge reports -5%.

**Comment by JuhaFIN1** [comment]
> I will add this to the list to look at if it seems to be a thing Ford have done for some models of cars. Seems weird they would regress to not storing the value but we could store the previous value or the API might have another field we can use if the gauge reports -5%.

Very strange :) But if you remember to let me know when this modification has made, then i can take off this "schlaggi" helped code :)

**Comment by JuhaFIN1** [comment]
Hello again. Just updated HACS in HA newest version and after it Fuel shows 0%. I tried this original fuel and it show -5%.
I just dont understand how this HACS update effects this... But really didn do anything else than reboot after.

**Comment by schlaggi** [comment]
I don't know about the 'guardstatus' error but I mentioned the other error earlier:

> The problem with the solution I came up with is, that it won't show anything after a server reboot if your sensor already shows "-5".
But that's an edge case I can live with. If you have improvements fell free to share!

In this case you can either set the value for "sensor.fordpass_fuel" manually or start the engine - or live with it until you drive your car again.
Since my workaround has no external cache or similar, after the reboot when "sensor.fordpass_fuel" already shows -5%, there is no correct value to fall back on.

**Comment by JuhaFIN1** [comment]
> I don't know about the 'guardstatus' error but I mentioned the other error earlier:
> 
> > The problem with the solution I came up with is, that it won't show anything after a server reboot if your sensor already shows "-5".
> > But that's an edge case I can live with. If you have improvements fell free to share!
> 
> In this case you can either set the value for "sensor.fordpass_fuel" manually or start the engine - or live with it until you drive your car again.
> Since my workaround has no external cache or similar, after the reboot when "sensor.fordpass_fuel" already shows -5%, there is no correct value to fall back on.
> 
> @itchannel Besides that I have the 'guardstatus' error to. My car supports this guard feature but I disabled it after a short test.

Is this -5% error in Ford Api? And if so, have you contact them? ( i can do it too :) )

**Comment by itchannel** [comment]
@JuhaFIN1 It's by design as it's the fuel sender value which can range from -5% to 105% according to an engineer. However it seems some models of fords don't save the fuel sender value to memory when the car's off which results in a -5% value if you poll the car whilst it's turned off.

**Comment by JuhaFIN1** [comment]
> @JuhaFIN1 It's by design as it's the fuel sender value which can range from -5% to 105% according to an engineer. However it seems some models of fords don't save the fuel sender value to memory when the car's off which results in a -5% value if you poll the car whilst it's turned off.
> 
> The problem I have is -5% is a genuine value so I can't just do a check for -5 and use old value like you guys have done in the template. So it's going to be an interesting issue to think about fixing.

I was asking this because i notised when HA shows -5%, Ford Pass iPhone app dosent show fuel at all! Whole gauge disapheres :)

**Comment by itchannel** [comment]
Oh really. Then maybe there is a fault on their end.

**Comment by JuhaFIN1** [comment]
> Oh really. Then maybe there is a fault on their end.

Ill take screen captures next time when it happens!

**Comment by JuhaFIN1** [comment]
> Yeah that's exactly the same problem I had. For more details look at this issue: #101
> 
> > Okay I was able to help myself with a template sensor:
> > ```
> > template:
> >   - sensor:
> >     - name: "Fordpass Fuel (Correct)"
> >       unit_of_measurement: "%"
> >       icon: 'mdi:gas-station'
> >       state: >
> >         {% if state_attr('sensor.fordpass_fuel', 'fuelLevel') > -5 %}
> >           {{ states('sensor.fordpass_fuel') | int }}
> >         {% else %}
> >           {{ states('sensor.fordpass_fuel_correct') | int }}
> >         {% endif %}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This sensor now always shows the value of sensor.fordpass_fuel, as long as it is not -5 or below.
> > Thanks anyway 🙂
> 
> The problem with the solution I came up with is, that it won't show anything after a server reboot if your sensor already shows "-5".
> But that's an edge case I can live with. If you have improvements fell free to share!
> 
> But if I am not the only one with the problem, but the whole Focus MK4 series is affected, we can perhaps still encourage the author of the integration to a proper solution.

Latest updates brokes this fix, error in log: "TemplateError('TypeError: '>' not supported between instances of 'NoneType' and 'int'') while processing template 'Template("{% if state_attr('sensor.fordpass_fuel', 'fuelLevel') > -5 %} {{ states('sensor.fordpass_fuel') | int }} {% else %} {{ states('sensor.fordpass_fuel_correct') | int }} {% endif %}")' for attribute '_attr_state' in entity 'sensor.fordpass_fuel_correct'"

- Juha

**Comment by itchannel** [comment]
I was hoping Ford might update the API to not return -5% on the models of cars that are affected by this as it's really a programming error on there side and adding patches will cause problems down the line.

**Comment by itchannel** [comment]
Closing old issue for housekeeping, new API now displays it better.

Please reopen if the issue is still present :)
