### ISSUE TITLE
f150 and explorer rear window state undefined

### ISSUE THREAD

**Issue by smos08** [itchannel/fordpass-ha#112]
here is the current state for the f150:
```
driverWindowPosition: Closed
passWindowPosition: Closed
rearDriverWindowPos: Undefined window position
rearPassWindowPos: Undefined window position
friendly_name: f150_windowPosition
icon: mdi:car-door
```

here is the current state for the explorer
```
driverWindowPosition: Closed
passWindowPosition: Closed
rearDriverWindowPos: Undefined
rearPassWindowPos: Undefined
friendly_name: explorer_windowPosition
icon: mdi:car-door
```

latest version of the integration
hass version - core-2021.6.3

**Comment by itchannel** [comment]
It will show that when your car doesn't support a window position status for those windows. The Ford API just responds back with Undefined.

**Comment by smos08** [comment]
figured that but was surprised it isn't supported on 2021 vehicles
