### ISSUE TITLE
Integration not initialising #90

### ISSUE THREAD

**Issue by pinthenet** [itchannel/fordpass-ha#114]
The path problem reported in **Integration not initialising #90** hasn't been resolved in the last 2 releases - I have to patch it every time. Just a reminder

**Comment by schlaggi** [comment]
Yeah I have the same problem since I moved my HA Setup from docker to FreeNAS. 😕

**Comment by itchannel** [comment]
@pinthenet @schlaggi Does one of you mind trying the version from this branch. I'm still testing the fix but retrieving the config location from HASS seems to work. [1.22 - Config fix](https://github.com/itchannel/fordpass-ha/tree/1.22---config)

**Comment by pinthenet** [comment]
I can try later todayOn 22 Jul 2021 02:13, itchannel ***@***.***> wrote:
@pinthenet @schlaggi Does one of you mind trying the version from this branch. I'm still testing the fix but retrieving the config location from HASS seems to work. 1.22 - Config fix

**Comment by pinthenet** [comment]
Sorry, it will have to be tomorrow...On 22 Jul 2021 08:05, ***@***.*** wrote:I can try later todayOn 22 Jul 2021 02:13, itchannel ***@***.***> wrote:
@pinthenet @schlaggi Does one of you mind trying the version from this branch. I'm still testing the fix but retrieving the config location from HASS seems to work. 1.22 - Config fix

**Comment by schlaggi** [comment]
I tested it and for me it just worked. I did not have to change the path and the log shows no error. 👍

**Comment by pinthenet** [comment]
I still can’t test for you, sorry. Other things have conspired to take up my time. As @schlaggi had the same issue, and he confirmed that the new branch worked, I’ll accept the change too. When do you plan to release?

 

John

**Comment by casperse** [comment]
Sorry I am having the same problem the integration Fordpass does not show up after intstallation and a reboot
I can see the installation is in the correct folder. Can anyone explain what file I need to patch/update?
Thanks!

**Comment by itchannel** [comment]
@casperse Did you reboot HA after installing the integration in HACS? It won't show up as an avaliable integration to add until you have. The issue referenced here is not what you experiencing as that comes after it's been setup.

**Comment by itchannel** [comment]
@pinthenet @schlaggi I have now released the fix as version 1.22.

**Comment by pinthenet** [comment]
Thanks, finally found a few minutes to install the new version – it works fine😊
