### ISSUE TITLE
Stuck on "Retrying setup: None"

### ISSUE THREAD

**Issue by HeathL17** [itchannel/fordpass-ha#117]
I installed today and added my vehicle.  My integration screen has been stuck with red text stating "Retrying setup: None" for over an hour.  

I can see my token is populated in fordpass_token.txt, but I do not see a service to call for the update.

Any next steps/insights where to go from here?

**Comment by itchannel** [comment]
Can you look in your log and let me know the full error you are getting.

**Comment by HeathL17** [comment]
I would, but I since wiped the repo and reinstalled.  Working now!
