### ISSUE TITLE
Send GPS location externally

### ISSUE THREAD

**Issue by JVTEAM** [itchannel/fordpass-ha#119]
I'm looking for a way to extract the GPS location to a google sheet.  I have a weather API that works off that google sheet to provide road conditions and weather.  I'd love to have it update based on the location of the car.  Anyone have a script that can do this already?

I also wouldn't mind all the data to be live exportable to make custom graphs.

**Comment by itchannel** [comment]
The only thing I can suggest is to either have a script that pulls data from the influxdb (if you have it enabled) that way you can pull out data for specified time periods. By default HA doesn't support and spreadsheet libraries or an easy way to export data within it.

**Comment by JVTEAM** [comment]
Where is the influxdb located?  is it sql?

**Comment by JVTEAM** [comment]
Nevermind, found the instructions
