### ISSUE TITLE
Sandbox or sample authentication

### ISSUE THREAD

**Issue by bschippers718** [itchannel/fordpass-ha#120]
Hi

I'm trying to test out a few concepts but don't currently have a Mach E to authenticate against.  Is there a sandbox and or sample car I could log in with so I can try a few things?  

Thanks!

**Comment by itchannel** [comment]
Sorry there isn't. Not officially supported by Ford so all work has been doing on my own car or help from fellow users unfortunately. In some of the issues you will find people's output which contains the data structure needed for cars like the Mach E if that helps
