### ISSUE TITLE
EV Charging Status

### ISSUE THREAD

**Issue by 400HPMustang** [itchannel/fordpass-ha#129]
Under fordpass_elVeh there is "Plug status" and there is "Battery Charge Status". Right now my car is charging and "Plug status" shows "1" and "Battery Charge Status" shows "NoReportRequest". I was wondering if those report any useful information such as whether or not the vehicle is actually charging and if there's some sort of fault or something like that or if it's possible to get the charging information in a meaningful way to use on a dashboard.

Thanks!

**Comment by 400HPMustang** [comment]
Actually figured out how to handle the plug status ie plugged in vs unplugged but I still haven't found out what to do with Battery Charge Status.

**Comment by ziptbm** [comment]
It'd be great to see the actual charging rate so you can better shuffle time of use rates, other power sources (solar/powerwall), and when it should and should not charge based on some of those variables.

**Comment by ziptbm** [comment]
@400HPMustang have you found a way to report if the vehicle is charging or not?

**Comment by 400HPMustang** [comment]
> @400HPMustang have you found a way to report if the vehicle is charging or not?

Nope. All I ended up with is plugged in or unplugged.

**Comment by tom-vos** [comment]
Noticed that for my PHEV the 'Charge End Time' attribute goes to "01-01-2010 00:15:00" when not charging.

Combining that information with the "Plug Status" information allowed me to create some charging status sensors.

This is what I did:

```
template:
  - unique_id: sensor_ford
  - sensor:
    - name: "Car Charge Level"
      unique_id: charge_level
      state: "{{ state_attr('sensor.fordpass_elVeh', 'Battery Fill Level') }}"
      unit_of_measurement: "%"
      state_class: measurement
      icon: >-
        {% set tenths = state_attr('sensor.fordpass_elVeh', 'Battery Fill Level') | float(default="Unknown") / 10 %}
        {% set numeral = 10 * tenths|int %}
        mdi:battery{% if state_attr('sensor.fordpass_elVeh', 'Plug Status') == 1 %}-charging{% endif %}{% if 10 <= numeral < 100 %}-{{ numeral }}{% elif numeral < 10 %}-outline{% endif %}                

  - sensor:
    - name: "Car Charging"
      unique_id: charging
      state: >
        {% set charge_begin = as_timestamp(strptime(state_attr('sensor.fordpass_elVeh', 'Charge Start Time'), '%m-%d-%Y %X')) %}
        {% set charge_end   = as_timestamp(strptime(state_attr('sensor.fordpass_elVeh', 'Charge End Time'), '%m-%d-%Y %X')) %}
        {% set charging = (charge_end > charge_begin) and state_attr('sensor.fordpass_elVeh', 'Plug Status') %}
        {% if not charging %}Ready{% else %}Charging{% endif %}
      icon: >-
        mdi:car{% if is_state('sensor.car_charging', 'Charging') %}-electric{% endif %}
```
