### ISSUE TITLE
Lock doors with automation?

### ISSUE THREAD

**Issue by ksignorini** [itchannel/fordpass-ha#131]
Is it possible to lock the doors with an automation? If so, how?

It was easy enough to get the ignition to work on a switch.turn_on service, but I have no idea how to do the locks.

Thanks.

**Comment by itchannel** [comment]
Yes just use the "lock.lock" and "lock.unlock" service such as below

```
service: lock.lock
target:
  entity_id: lock.fordpass_doorlock
```

**Comment by itchannel** [comment]
Closing this issue as comment above should help. Any further questions feel free to reopen.
