### ISSUE TITLE
1.23 Update 

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#135]
The 1.23 update changes the way Units are handled in the options. Therefore you will need to go to "Configure" on the fordpass integration after you've updated and select and save your preferred units otherwise it will error!. Once you've selected these units please restart your HA instance and it should be back and working. 

I did want to avoid a breaking change however this is the easiest way to get people to select their units and prevent 2 different configs being used. 

Any issues drop me a comment below.

**Comment by Blackpander** [comment]
I am testing this version, but it looks like the integration isn't that stable. Sometimes I see all sensors unavailable and when the integration is reloaded, everything works again.

Also the Odometer sensor doesn't work anymore.
If you need some info, just ask :)

**Comment by JVTEAM** [comment]
I lost the odometer, fuel and tire pressure.  I did configure it and update the UofM with no change.

**Comment by itchannel** [comment]
Those sensors are reliant on the options being set for units. Can I confirm you set them such as below:

![image](https://user-images.githubusercontent.com/5840973/144515678-a4587d36-cde9-431f-bc5a-97fd4f828421.png)

It does require a restart of HA once you've updated the Fordpass plugin.

**Comment by JVTEAM** [comment]
Yes, the reboot of the server restored the entities.

**Comment by Blackpander** [comment]
@itchannel after setting the units and restarting home assistant, the odometer is still unavailable. Can’t seem to find out why. The rest is working as expected.

**Comment by pinthenet** [comment]
As all Fordpass values were 'unavailable' I restarted HA a couple of hours ago then values reappeared. Now everything is 'unavailable' again

**Comment by pinthenet** [comment]
Sorry, forgot to add the log messages
`Error fetching fordpass data: Error communicating with FordPass for VIN
15:58:20 – (ERROR) FordPass (custom integration) - message first occurred at 14:47:15 and shows up 2 times
Error communicating with FordPass for VIN
15:58:20 – (WARNING) FordPass (custom integration) - message first occurred at 14:47:15 and shows up 2 times
15:58:20 – (WARNING) FordPass (custom integration) - message first occurred at 14:47:15 and shows up 2 times`

**Comment by pinthenet** [comment]
Sorry, spoke too soon, a few hours later the values were updated. Must have been a problem with the Ford server(s).

**Comment by heyepic** [comment]
Seems like Ford is down / having issues with this again as all entities are showing as unavailable for me.

![image](https://user-images.githubusercontent.com/12517908/144892508-1bcbf2d9-9a55-4f4e-bbc7-9a4945cb4ce0.png)

**Comment by JVTEAM** [comment]
> Seems like Ford is down / having issues with this again as all entities are showing as unavailable for me.
> 
> ![image](https://user-images.githubusercontent.com/12517908/144892508-1bcbf2d9-9a55-4f4e-bbc7-9a4945cb4ce0.png)

Is that a picture tile above the Fordpass details or have you somehow combined the 2?

**Comment by heyepic** [comment]
> > Seems like Ford is down / having issues with this again as all entities are showing as unavailable for me.
> > 
> 
> Is that a picture tile above the Fordpass details or have you somehow combined the 2?

Just a combination of the following:
`  - type: picture
    hold_action:
      action: none
    image: https://www.visionsconnect.com/smart/fordescape.jpg
    tap_action:
      action: none
    theme: ios-dark-mode-blue-red
  - type: entities
    entities:
      - entity: device_tracker.fordpass_tracker
      - entity: switch.fordpass_ignition_switch
      - entity: sensor.fordpass_ignitionstatus
      - entity: lock.fordpass_doorlock
      - entity: sensor.fordpass_doorstatus
      - entity: sensor.fordpass_oil
      - entity: sensor.fordpass_battery
      - entity: sensor.fordpass_tirepressure
      - entity: sensor.fordpass_fuel
    title: Ford Escape`

BTW it's back to working for me!

**Comment by Blackpander** [comment]
It looks like that the Fordpass-service is sometimes stuck. When I reload the integration myself it immediately works again. The Odometer is still not working and fordpass_fuel is not working too (Maby because of my vehicle type?).

**Comment by itchannel** [comment]
@Blackpander Can you please just go to integrations/Fordpass and click configure and check the 2 unit values are set and just click apply anyway. The symptoms you are describing are caused by the values not being saved correctly so when the sensor value is set it's erroring out finding the unit variable.

**Comment by itchannel** [comment]
Old issue and fixed in later releases.
