### ISSUE TITLE
South Africa

### ISSUE THREAD

**Issue by terencevs** [itchannel/fordpass-ha#141]
Good day, 

What would be needed to get support for South Africa region?

Thanks.

**Comment by itchannel** [comment]
It's worth trying the other regions like Europe first as it might work for you. Failing that I need a copy of the headers being sent from your Fordpass mobile app to the ford server to get the Country API code. I can guide you through this and is fairly easy using a proxy such as Burp.

**Comment by terencevs** [comment]
> It's worth trying the other regions like Europe first as it might work for you. Failing that I need a copy of the headers being sent from your Fordpass mobile app to the ford server to get the Country API code. I can guide you through this and is fairly easy using a proxy such as Burp.

I have tried using the other regions did not work. It would be nice if you could guide me?

**Comment by itchannel** [comment]
Before we go down the route of running a proxy etc. What error do you get when trying to add fordpass?

**Comment by terencevs** [comment]
I get "Invalid Authentication"

**Comment by DeFiEcoSys** [comment]
Hey hey, just following up on this to see if anyone for the region code for SA?

**Comment by cyrenaud** [comment]
Howzit! Any progress with support for South Africa. Happy to help in any way, but a bit of guidance may be necessary with Burp if required.

**Comment by Obvpoff** [comment]
Hi,
Just another follow up on if there is any progress on this and or if there is something we can do to help?
Would love to use this integration on my Ranger!

**Comment by theunidj** [comment]
this issue should be merged with the other one on the same topic. I have had success by using my mobile number without the leading 0. e.g 73... instead of 073... and using the Europe/UK region.

**Comment by itchannel** [comment]
Closing as have opened a new issue to track #358
