### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [itchannel/fordpass-ha#15]
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Comment by itchannel** [comment]
More than welcome to. What actions were you thinking?

**Comment by KTibow** [comment]
I was thinking of https://github.com/KTibow/ha-blueprint but I could add the new HACS action if you want instead (it has less features though).

**Comment by itchannel** [comment]
Looks like a handy action :)
