### ISSUE TITLE
Options now showing

### ISSUE THREAD

**Issue by dbroxterman** [itchannel/fordpass-ha#151]
I am trying to install the FordPass in my Home Assistant and never can get to the options for initial setup.  I first tried the latest version 1.30, but then removed and have tried all the versions listed down to 1.26 and never get the options page.  Is there something I am doing wrong on install?  I have the latest HA installed as well.

**Comment by karlgo** [comment]
Just wanted to let you know that you're not the only one having this issue. I installed through HACS and went to configuration|Add New Integration and can't find the FordPass integration.

I'm on:
Home Assistant OS 7.1
HA core-2021.12.7
HACS 1.18.0

Any assistance would be most appreciated - thank you!

Karl

**Comment by mattbarber87** [comment]
Same here :(

**Comment by paukstelis** [comment]
I am also having this issue. No options or configuration available under the fordpass card. 
![image](https://user-images.githubusercontent.com/28326982/168488792-70a75db6-c929-44dc-9f07-05a27757e093.png)

**Comment by itchannel** [comment]
Closing as been no updates since May. Make sure you restart Home assistant once adding with HACS for the integration to show up.
