### ISSUE TITLE
There was an issue at Ford, messages are displayed now. Alas with incorrect date

### ISSUE THREAD

**Issue by mikje** [itchannel/fordpass-ha#153]
I do not get the latest messages. Only from the past.
![267565309_399744281898807_7854176761557958976_n](https://user-images.githubusercontent.com/12999690/147596991-223ae017-3da8-4997-92fe-051ac36490e6.jpg)
![269992422_633009174791834_6585539056649475521_n](https://user-images.githubusercontent.com/12999690/147597022-85ea190d-a114-4eef-bd99-db1d516c8e6a.png)

**Comment by itchannel** [comment]
This was fixed in a previous release.
