### ISSUE TITLE
Mi vs Km in sensor.fordpass_odometer

### ISSUE THREAD

**Issue by gniknalu** [itchannel/fordpass-ha#154]
How do I get sensor.fordpass_odometer to be in miles? I've already went to "configuration" --> Devices & Services --> Ford Pass --> Configure  --> and set "Unit of Measure" to MI but it hasn't changed sensor.fordpass_odometer where it says "unit_of_measurement: km"

**Comment by JacobWasFramed** [comment]
Did you restart Home Assistant after changing the configuration option?

**Comment by gniknalu** [comment]
> 

Yes. Restarted after making the change is one of the things I've tried.

**Comment by gniknalu** [comment]
Woke up this morning and not it's saying Mi instead of Km???? Didn't restart nor update anything.
