### ISSUE TITLE
FordPass Stops Working After Awhile

### ISSUE THREAD

**Issue by heyepic** [itchannel/fordpass-ha#159]
First - thank you so much for making this integration! Mega helpful for starting the car easily without the Ford app.

I've been noticing that after awhile, all entities are unavailable until I go to devices & integrations and click reload - then they will show up proper.

**Comment by tobox** [comment]
Same for me, for quite a while. I have an EV (Mustang Mach E) in Germany, if that information helps.

It's sad, because the addon was working quite nicely.

**Comment by itchannel** [comment]
Can you check your HA logs for any events that might be related to this.

**Comment by heyepic** [comment]
> Can you check your HA logs for any events that might be related to this.

Error doing job: Task exception was never retrieved
4:14:56 PM – (ERROR) FordPass (custom integration) - message first occurred at February 12, 2022, 7:36:03 PM and shows up 821 times
Error fetching fordpass data: Error communicating with FordPass for 1FMXXXXXXXXXXXXXXX
1:34:34 AM – (ERROR) FordPass (custom integration)
Error communicating with FordPass for 1FMXXXXXXXXXXXXXXX
1:34:34 AM – (WARNING) FordPass (custom integration)
503 Server Error: Service Unavailable for url: https://api.mps.ford.com/api/messagecenter/v3/messages
1:34:34 AM – (WARNING) FordPass (custom integration)
Error adding entities for domain sensor with platform fordpass
February 14, 2022, 8:14:30 PM – (ERROR) Sensor (custom integration) - message first occurred at February 12, 2022, 7:31:02 PM and shows up 9 times
Error doing job: Task exception was never retrieved
February 14, 2022, 6:56:31 PM – (ERROR) FordPass (custom integration)

**Comment by heyepic** [comment]
Any ideas @itchannel ? 

New example is that the remote status stopped working. Locked status also hasn't worked for like 4 months for me.

![image](https://user-images.githubusercontent.com/12517908/154713088-a2e4dcd0-a599-4004-bde7-e88c14216376.png)

Error doing job: Task exception was never retrieved
9:31:11 AM – (ERROR) FordPass (custom integration) - message first occurred at February 17, 2022, 11:34:40 AM and shows up 261 times
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /api/oauth2/v1/refresh
9:11:11 AM – (WARNING) /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py - message first occurred at February 17, 2022, 11:50:10 AM and shows up 5 times
Error doing job: Task exception was never retrieved
February 17, 2022, 4:56:02 PM – (ERROR) FordPass (custom integration)
Error fetching fordpass data: Error communicating with FordPass for 1FMXXXXXXXXXXX
February 17, 2022, 2:15:14 PM – (ERROR) FordPass (custom integration) - message first occurred at February 17, 2022, 11:45:10 AM and shows up 2 times
Error communicating with FordPass for 1FMXXXXXXXXXXX
February 17, 2022, 2:15:14 PM – (WARNING) FordPass (custom integration) - message first occurred at February 17, 2022, 11:45:10 AM and shows up 2 times
February 17, 2022, 2:15:14 PM – (WARNING) FordPass (custom integration) - message first occurred at February 17, 2022, 11:45:10 AM and shows up 2 times
Error adding entities for domain sensor with platform fordpass
February 17, 2022, 11:29:40 AM – (ERROR) Sensor (custom integration) - message first occurred at February 17, 2022, 11:29:38 AM and shows up 3 times

**Comment by itchannel** [comment]
Closing as old issue. Please re-open a new one if issue still exists.
