### ISSUE TITLE
Car update interval

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#16]
Hi All. Was just wondering what people think is a suitable interval to poll the car for updates. The current version has the functionality to poll the car and request updates however I have disabled it in the HA integration due to it constantly waking the car up. 

I could set it to poll every hour or potentially only when a person arrives or leaves the house to get an update? 

Please let me know your thoughts, I'm currently running tests on my car to see how often I can poll my car without experiencing battery drain.

**Comment by pinballnewf** [comment]
Might be a good idea to create a service.refresh to allow automations to decide when to refresh - that way it could be refreshed whenever makes sense for each user

**Comment by itchannel** [comment]
That's the plan for the next release. That way you can either have it on a schedule or have it triggered by something else like arriving home.

**Comment by itchannel** [comment]
Have now added the fordpass.refresh_status service which will poll the car for an update. It is recommended this is only polled on actions such as arriving home or a manual/timed event. As it will result in batter drain if ran too often.
