### ISSUE TITLE
Last Refresh time incorrect

### ISSUE THREAD

**Issue by BrttClne22** [itchannel/fordpass-ha#160]
If I refreshed today at 5PM, the last refresh sensor would give me back 2022-01-27 22:00:00-05:00. The DateTime component appears to be the current UTC time, -05:00 means that it should be adjusted for EST time but it is not.

Based on what I've found, 5PM should either be listed as 2022-01-27 17:00:00-05:00 (timezone adjusted) or 2022-01-27 22:00:00-00:00 (utc).

fordpass-ha: 1.30
ha-version: 2021.12.10
timezone: America/New_York

Thanks for all your work on this :) One of my favorite integrations!

**Comment by itchannel** [comment]
At the moment the integration just returns the raw value exposed by the Fordpass API. I don't currently convert it to the relevant local timestamp. I could look at doing this in the not so distant future.

**Comment by ronytomen** [comment]
The issue is the datetime returned from the Fordpass API is UTC without a timezone designation, so when that is passed to the HomeAssistant DataTime (dt) helper it assumes the default time zone instead of UTC.  So, the refresh datetime will be UTC time with the default time zone.

**Comment by ronytomen** [comment]
This issue can be closed.
