### ISSUE TITLE
Is there a way to get 12v battery voltage with 2 decimal point accuracy?

### ISSUE THREAD

**Issue by ebialobrzeski** [itchannel/fordpass-ha#165]
As stated in the title. I can see that the voltage is rounded to an integer but it would be super helpful for some of those who are struggling with 12v battery issues to see the actual voltage and be able to alert on that.

**Comment by itchannel** [comment]
Unfortunately the Fordpass API only gives a rounded value so I'm unable to give a more accurate voltage.

**Comment by ebialobrzeski** [comment]
Thanks

**Comment by VaAndCob** [comment]
going to ask about this but it's clear now.
