### ISSUE TITLE
Renaming device does not rename associated entities

### ISSUE THREAD

**Issue by doublepedaldylan** [itchannel/fordpass-ha#167]
Renaming the overall device in fordpass does not result in entities being renamed as well (at least when a VIN is used in setup).
This may be a result of [default naming convention not matching sub-string](https://community.home-assistant.io/t/bulk-renaming-of-related-entities/354592/5)

**Comment by ronytomen** [comment]
This might be a Home Assistant issue, not the FordPass component.

**Comment by SquidBytes** [comment]
I'm going to close this because there have been large changes since then.
Please open a new issue for any new issues :)
