### ISSUE TITLE
fordpass: No module named 'dotted'

### ISSUE THREAD

**Issue by kevinvdburgt** [itchannel/fordpass-ha#171]
Installed 1.30 using HACS, after installing and adding the integration I'll receive the following message:
> This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

In the HomeAssistant logs:
> ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration fordpass: No module named 'dotted'

**Comment by itchannel** [comment]
I would try reinstalling as the "dotted" dependency should be installed as part of the install via HACS

**Comment by itchannel** [comment]
Closing as old issue and dotted is no longer used as a library in the integration.
