### ISSUE TITLE
Data Fetch only hourly while driving?

### ISSUE THREAD

**Issue by magnetic157** [itchannel/fordpass-ha#175]
My FordPass integration only seems to fetch data hourly when the car is in-motion which causes some issues when graphing my fuel and electric level.  When on a trip, it takes sharp dives each hour instead of having a gradual decline.

When parked, it seems to report every 15 minutes.   Is there a way to resolve this?

![image](https://user-images.githubusercontent.com/78054864/169817694-7219b147-c4ee-42b5-a7ee-779bb42f0062.png)

![image](https://user-images.githubusercontent.com/78054864/169818086-7a4cd3ef-1601-4a9d-8bb8-e74e13eb008c.png)

**Comment by itchannel** [comment]
The integration polls the Fordpass API every 15mins, however that data is only scraped from the car by Ford on an irregular basis. 
You can run the service "Fordpass Refresh" which will manually poll the car but doing this too often will cause significant battery drain.

**Comment by magnetic157** [comment]
I saw on the home page that this is an option but I cannot see it anywhere on my integration.  The only thing I see is "sensor.fordpass_last_refresh" which shows the time it was last refreshed.

How do I access this function?

**Comment by itchannel** [comment]
There is a service exposed by the integration in HA called "fordpass.refresh_status" you can set up an automation with a given VIN to manually poll the car on whatever interval you want. Just be aware it will cause significant battery drain.

**Comment by itchannel** [comment]
As mentioned previously the "fordpass_refresh_status" service can be used to poll the car as often as needed. Just be careful of excessive battery drain.
