### ISSUE TITLE
Retrying set up: none

### ISSUE THREAD

**Issue by JayJay-SmartHome** [itchannel/fordpass-ha#176]
I have a Ford S-Max 2019 and I'm in the uk.
I have tried installing for several weeks, being patient but still unsuccessful 

Log shows 3 errors

'Vehiclestatus'

Error fetching fordpass data: Error communicating with FordPass for Vin (copied from FordPass app)

Error communicating with FordPass for Vin

Any ideas?

**Comment by austinbeam** [comment]
@itchannel Any thoughts here? I’ve been seeing the same for the past few weeks. Thought it’d eventually come back but it seems to be stuck. I noticed there is no fordpass_token.txt to be found any longer. Assuming that’s not good. Don’t really want to purge my setup if I don’t have to because all of the entities are manually renamed and that is a pain to do over if I can avoid it.

**Comment by itchannel** [comment]
Make sure the token file in "custom_components/fordpass/{your_username}_fordpass_token.txt" doesn't exist if it does delete the integration and rerun. Failing that please add the following to your configuration and send me the logs generated. 

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

**Comment by austinbeam** [comment]
Thanks @itchannel. I've been away, so apologies for the delay, but attached is a scrubbed log for your reference. In my case, the token file doesn't exist nor does it generate. This has persisted across many reboots and reloads.

Here's what I see on the device config page:
![image](https://user-images.githubusercontent.com/1715252/185840795-e5cc6ce5-91a2-4515-8716-25b69f9e8892.png)
![image](https://user-images.githubusercontent.com/1715252/185840812-ee375a36-fe89-40f0-b7b1-6efc00c916d9.png)
[home-assistant.log](https://github.com/itchannel/fordpass-ha/files/9391266/home-assistant.log)

**Comment by JayJay-SmartHome** [comment]
Thanks @itchannel 
Like @austinbeam , I don't have the token you suggest deleting either.

I'm out at the moment - will see if I can grab a copy of the log.

Thanks

**Comment by JayJay-SmartHome** [comment]
@itchannel have now got off the web chat with FordPass 
They have turned off the FordPass functionality for cars that don't have a 'modem' - bit of a crappy response as my car could get WiFi on the front drive.
This has rendered the addon useless for me - gutted.

**Comment by austinbeam** [comment]
@itchannel Any insights you can share? I'd sure love to get this working again. Appreciate all you do, have a good one.

**Comment by ONE170** [comment]
I just installed the ford pass integration and got following error. Any ideas what to do?

![image](https://user-images.githubusercontent.com/104277080/191584499-3016fcd4-a3c8-4ba1-8eab-e6a2d83a225d.png)

**Comment by austinbeam** [comment]
Finally think I got to the bottom of this...details below but TLDR is my account had been blocked and needs manual unblocking. Fordpass doesn't respond to emails, so try calling.

https://github.com/itchannel/fordpass-ha/issues/203#issuecomment-1297721758

**Comment by copywizard** [comment]
Hello i have the same problem as described above.
My app works great on my phone and is not blocked (yet)

but in HA i keep getting 
![Screenshot 2022-11-07 at 12 07 00](https://user-images.githubusercontent.com/20820085/200299150-2def2f1b-fb9c-48f2-91d2-96afd814e429.png)

Even tried the solution in this threat by deleting the integration multiple times and every time i get a "username"_fordpass_token.txt file but it keeps giving me this error.

Any help would be really appreciated

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
