### ISSUE TITLE
New feature request: percentage of the battery

### ISSUE THREAD

**Issue by Koetjeboeh** [itchannel/fordpass-ha#178]
When intergrated, there is no battery percentage showing of the car (in this case a Mustang Mach-E).
I would like to make some automation based on the percentage, not on how far I can drive (it's to dependant on the weather).

**Comment by Bart274** [comment]
I used a template sensor to read the Battery Fill Level attribute of my fordpass_elVeh sensor. That contains the battery percentage.

**Comment by bjsmyth** [comment]
I did what Bart did. In my configuration.yaml I have the following and it breaks out the battery percentage into its own sensor.

`template:
  - sensor:
      - name: "Escape EV Range Percentage"
        unit_of_measurement: "%"
        state: "{{ state_attr('sensor.fordpass_elveh', 'Battery Fill Level') }}"
        icon: "mdi:ev-station"`

**Comment by Koetjeboeh** [comment]
I've got the percentage now, thanks!
