### ISSUE TITLE
New request : write to influxdb

### ISSUE THREAD

**Issue by mattiaoui** [itchannel/fordpass-ha#179]
I want to write data direclty to influxdb without using HA.

Thanks 
Mattia

**Comment by itchannel** [comment]
I'm sorry but if you want to do something like that then you're welcome to use the functions in the fordpass_new.py file but it's not something I'm looking at doing as this is just a HA integration and doesn't make sense to add separate functionality for writing to an influxdb as HA can be set to do that.
