### ISSUE TITLE
error while trying to install 1.32 beta

### ISSUE THREAD

**Issue by philbowers** [itchannel/fordpass-ha#182]
Looks like HACS doesn't like 1.32 beta.

Logger: custom_components.hacs
Source: custom_components/hacs/websocket.py:286
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 1:03:28 AM (7 occurrences)
Last logged: 1:05:29 AM

Expecting property name enclosed in double quotes: line 13 column 3 (char 359
![fordpass](https://user-images.githubusercontent.com/8340735/174721083-70053e15-1b58-41e7-b431-e6e4a6f2c5fa.jpg)
)

**Comment by itchannel** [comment]
Give 1.43Beta2 a go. There was an issue with the hacs file.

**Comment by itchannel** [comment]
Closing issue as this has now been fixed
