### ISSUE TITLE
Integration not working...again

### ISSUE THREAD

**Issue by 400HPMustang** [itchannel/fordpass-ha#187]
So after a few days of happiness it looks like Ford has decided to change things up again. Not sure if we can continue to use this integration. Here's the logs

```
This error originated from a custom integration.

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:223
Integration: Fordpass (documentation, issues)
First occurred: 9:03:06 AM (1 occurrences)
Last logged: 9:03:06 AM

Error fetching fordpass data: Error communicating with FordPass for 1XXXXXXXXXXXXXXX7
```
```
This error originated from a custom integration.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:188
Integration: Fordpass (documentation, issues)
First occurred: 9:03:06 AM (1 occurrences)
Last logged: 9:03:06 AM

401 Client Error: Unauthorized for url: https://api.mps.ford.com/api/messagecenter/v3/messages
```

**Comment by tonesto7** [comment]
Yeah... ford is restricting the token endpoints further.  I'm working on a solution for my Fordpass Widget... I will post any solutions I find here as well

**Comment by itchannel** [comment]
I occasionally see that error in my logs but it's more the fordpass API having a wobbly with tokens every so often. Usually fixes itself on the next refresh(15mins). In the last 24hrs it did it twice so at the moment it's not really worth worrying about unless it's stopping permanently for anyone.

**Comment by Brandawg93** [comment]
I'm looking into this as well for my homebridge plugin. I've generated authorization codes before and have code that may be useful to this: https://github.com/Brandawg93/homebridge-nest-cam/blob/master/src/login.ts.

**Comment by tonesto7** [comment]
@itchannel @Brandawg93 

![image](https://user-images.githubusercontent.com/1835933/176254575-677ad6c4-b3ea-448d-a8d9-80d566c112f4.png)
With a body of ```operation=verify&login-form-type=pwd&username=EMAIL_HERE&password=PASSWORD```

The identity_source_id param for me always stays the same with 75d08ad1-510f-468a-b69b-5ebc34f773e3
The state_id is what constantly changes

**Comment by Brandawg93** [comment]
That's the same one I get too. More than likely, the state_id is randomly generated.

**Comment by tonesto7** [comment]
So they do have an official API but does not mention how to request a token
https://developer.ford.com/apis/fordconnect

**Comment by Brandawg93** [comment]
They probably have to set the business up to handle Oauth, and then you can use their official page.

**Comment by tonesto7** [comment]
nice find... I can't believe I missed the state_id in the HTML (I was looking for it)

**Comment by Brandawg93** [comment]
Ya. Just found that info too. That's the same way I had to do it for homebridge-nest-cam. It's a bit hacky, and makes things more difficult for the end-user unfortunately.

**Comment by ianjwhite99** [comment]
Ford also is validating the cookies as they are coming across to check to make sure the request is actually coming from `https://sso.ci.ford.com/`. I'm thinking the best solution to this is going to be opening a browser window using selenium, puppeteer or whatever and pulling the cookies & tokens down then using that to make the requests.

**Comment by tonesto7** [comment]
In my use case, I should be able to encapsulate this all in a nice webview

**Comment by Brandawg93** [comment]
I've done the puppeteer way before. It's pretty horrible.

https://github.com/Brandawg93/homebridge-nest-cam/blob/f40d106620d96972fedb0dd57179d67731cc33aa/src/util/login.ts

**Comment by ianjwhite99** [comment]
> I get the need to improve security. Where there's a will there's a way. If they would just release an official API they would have much more control over those that abuse it. Instead of forcing us to come up with these solutions.

Agreed. It would be nice if they added the ability to generate tokens for user accounts or a client_id and client_secret that could be used with their OAuth.

**Comment by tonesto7** [comment]
I still don't see how we are going to capture the code... We can't capture fordpass:// URL and we can't change it to a custom URL because it throws a CSIAQ0167E error about invalid redirect_uri

**Comment by Brandawg93** [comment]
You would need to use something like puppeteer and analyze the response before the redirection and parse the code.

**Comment by tonesto7** [comment]
Another snafu is that the Code challenge is not a static value.

**Comment by Brandawg93** [comment]
Here's how you do the code: https://github.com/Brandawg93/homebridge-nest-cam/blob/5d174ba8b11400839313c1eb9d875cf8cdb6d2ec/src/nest/connection.ts#L36

**Comment by tonesto7** [comment]
The state_id is also in the action attribute in the first URL
![image](https://user-images.githubusercontent.com/1835933/176285233-b7539135-e2d0-4a65-bb40-d8b68e0eab4c.png)

**Comment by Brandawg93** [comment]
This will probably help you but not me...

You can use the auth-token and application id from https://www.ford.com/support/vehicle-dashboard.

That way you can do the auth process completely in the browser.

**Comment by tonesto7** [comment]
> This will probably help you but not me...
> 
> You can use the auth-token and application id from https://www.ford.com/support/vehicle-dashboard.
> 
> That way you can do the auth process completely in the browser.

Sorry, I'm not following what you mean...

**Comment by Brandawg93** [comment]
It looks like they haven't properly locked down oauth between applications, so an auth-token generated by the support website will work for the connect apis.

All I did was:
1. log into https://www.ford.com/support/vehicle-dashboard
2. Look in chrome dev console for `/users` call
3. Copy `auth-token` and `application-id` to `usapi` status call

You would still need a way to intercept the network calls, but this is much easier than trying to figure the redirect_uri stuff with the fordpass app.

**Comment by ianjwhite99** [comment]
I'm having a hell of a time trying to get the `fordapp://userauthorized?code=<code>`. I can get all the way to the last request `https://sso.ci.ford.com/oidc/endpoint/default/authorize?qsId=<qsId>&client_id=9fb503e0-715b-47e8-adfd-ad4b7770f73b&identity_source_id=75d08ad1-510f-468a-b69b-5ebc34f773e3` using puppeteer but then I get Error: net::ERR_ABORTED.

I'm not sure if its the server blocking me OR if puppeteer is confused because the response is from the `fordapp://` URL Scheme.

**Comment by tonesto7** [comment]
I think i have this almost done with puppeteer... I have to go take care of something but hopefully, I can play with it more tonight.

**Comment by itchannel** [comment]
Good to see a few people working on it, I agree would be nice if we could just use the official 3rd party API but guessing there's charges associated with it.

The fordpass:// part calls a function in the app on the device which takes the given code and generates a token from what I can tell annoyingly that part is obfuscated from the little I managed to just check. Will try and have a look tonight.

**Comment by ianjwhite99** [comment]
This is a super hacky solution with puppeteer but I figured I'd share. 

I was having issues grabbing the `fordapp://userauthorized?code=<code>&grant_id=<grant_id>`. Puppeteer is confused by the `fordapp://` URL Scheme and throws `net::ERR_ABORTED`. 

I attempted to useRequestInterception to try stop the request after successfully hitting the `https://sso.ci.ford.com/oidc/endpoint/default/authorize` endpoint but I had no luck.

I then however realized that puppeteer logs the reason for the `net::ERR_ABORTED` to the console. I was able to intercept the message getting logged to the console and grab the `fordapp://userauthorized?code=<code>&grant_id=<grant_id>` URL scheme successfully using Regex.

<img width="629" alt="Screen Shot 2022-06-28 at 6 55 27 PM" src="https://user-images.githubusercontent.com/35158392/176323370-fe38cff5-a334-495c-8464-13cb6193db1d.png">

**Comment by ianjwhite99** [comment]
It also appears the old password grant authentication url is not the correct was to exchange codes for access tokens. Unless I am missing something.

<img width="985" alt="Screen Shot 2022-06-28 at 7 30 03 PM" src="https://user-images.githubusercontent.com/35158392/176326316-553e3ac1-1fee-4ffd-ba93-af2a099ed068.png">

**Comment by ianjwhite99** [comment]
One step closer. Does anybody know what the code_verifier could possibly be?

The initial URL from the FordPass application has the code_challenge and code_challenge_method. But like @tonesto7 stated the value isn't dynamic.

```https://sso.ci.ford.com/v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=9fb503e0-715b-47e8-adfd-ad4b7770f73b&code_challenge=EiBNP3VtgKB3ayeBTzAzvQJlXdvY86JeL4f2X49nDW8%3D&code_challenge_method=S256```

<img width="1002" alt="Screen Shot 2022-06-28 at 8 15 54 PM" src="https://user-images.githubusercontent.com/35158392/176330441-708ee95c-6852-43dc-a321-d65641f7848c.png">

**Comment by ianjwhite99** [comment]
SUCCESS!! I ended up using [pkce-challenge](https://www.npmjs.com/package/pkce-challenge) and that worked perfectly!

<img width="1063" alt="Screen Shot 2022-06-28 at 8 27 47 PM" src="https://user-images.githubusercontent.com/35158392/176331704-feaca132-cc69-41ab-9f7c-ea55e39d4552.png">

**Comment by Brandawg93** [comment]
Same! I have this working from beginning to end without puppeteer. I need to clean up the code and then I'll commit it to my repo.

**Comment by tonesto7** [comment]
@Brandawg93 I'm looking forward to seeing your solution

**Comment by Brandawg93** [comment]
Ok. Here's what I've got: https://github.com/Brandawg93/homebridge-fordpass/commit/cf6a2babb0ea9183e6e0dd110e814da89991ac52

The only thing that I don't have working is the [`getVehicles` function](https://github.com/Brandawg93/homebridge-fordpass/blob/new-auth/src/fordpass-connection.ts#L82). Maybe someone else can figure that one out. 😀 I need to put this up for a while and get sleep lol.

**Comment by Brandawg93** [comment]
And just a forewarning, they will most certainly break this when they add CAPTCHA to their sso UI.

**Comment by ianjwhite99** [comment]
I've released my changes as well: https://github.com/ianjwhite99/connected-car-node-sdk/commit/a6b5e02be034f3edd09988a327b56fd3fd94de18

My updates are similar to that of @Brandawg93, however I use the same routes that the FordPass application uses instead of going through the `redirect_uri=https%3A%2F%2Fwww.ford.com%2Fsupport%2Fvehicle-dashboard`. I also grab the Authorization Code from the `fordapp://userauthorized?` scheme.

Thanks Brandon for figuring out that axios implementation helped me out **BIG** time!

**Comment by itchannel** [comment]
Nice work @Brandawg93 @ianjwhite99 @tonesto7  👍 Just got it working in a very messy form in python. Need to tidy up now :)

**Comment by tonesto7** [comment]
Thanks again @Brandawg93 @ianjwhite99 I have this working in a private project again. 
Now I need to get it working in my Scriptable Script.  The main shortcoming is that I can't use Axios or Cookie-Jar.

**Comment by Brandawg93** [comment]
> The main shortcoming is that I can't use Axios or Cookie-Jar.

I was curious how you would be able to do that.

I have it working privately in my plugin again as well. I'm making a few optimizations to my previous code, but it will still include axios and cookie-jar unfortunately. I started playing around with manually getting the cookies from each request and holding them in a variable, but then found cookie-jar.

**Comment by tonesto7** [comment]
Ok i have it working without cookie-jar now.

You only need to pass the cookies to the next step in 1-4
![image](https://user-images.githubusercontent.com/1835933/176500024-dd9b7619-0bff-47a8-99be-dad60bdd0eb5.png)

**Comment by tonesto7** [comment]
Ugh... i forgot that I can't use Buffer in Scriptable

**Comment by itchannel** [comment]
> > Nice work @Brandawg93 @ianjwhite99 @tonesto7 +1 Just got it working in a very messy form in python. Need to tidy up now :)
> 
> 
> 
> @itchannel; I'd love to see your python code so I can figure out what I need to do in Java.

@khpylon check out branch 1.34 for how I've implemented it in python. I'm already using session handling in requests so that handles cookies etc for the multiple calls. It's still a little messy but should give you a guide.

**Comment by ianjwhite99** [comment]
Thanks @itchannel for sharing your python release. It was a big help in getting the auth working as quickly as possible for my python SDK! https://github.com/ianjwhite99/connected-car-python-sdk/commit/e4a23f9de98d5e78a4a7f4ccf656c7061b01d572

**Comment by tonesto7** [comment]
@itchannel @Brandawg93 @ianjwhite99 

Do you guys got any ideas on vanilla code to simulate this line?:
```const hashBuf = Buffer.from(hash, "hex");```

Here is the hash code output and the string output of the code above.
```
hash 0b2a323431340024dd29c574fa25f4bae5a09b46d459de57bd8339ff8542792a
```
```
hashBuf: <Buffer 0b 2a 32 34 31 34 00 24 dd 29 c5 74 fa 25 f4 ba e5 a0 9b 46 d4 59 de 57 bd 83 39 ff 85 42 79 2a>
```

**Comment by ianjwhite99** [comment]
> @itchannel @Brandawg93 @ianjwhite99
> 
> Do you guys got any ideas on vanilla code to simulate this line?: `const hashBuf = Buffer.from(hash, "hex");`
> 
> Here is the hash code output and the string output of the code above.
> 
> ```
> hash 0b2a323431340024dd29c574fa25f4bae5a09b46d459de57bd8339ff8542792a
> ```
> 
> ```
> hashBuf: <Buffer 0b 2a 32 34 31 34 00 24 dd 29 c5 74 fa 25 f4 ba e5 a0 9b 46 d4 59 de 57 bd 83 39 ff 85 42 79 2a>
> ```

Someone correct me if I'm wrong but...

I don't believe you can use vanilla code to simulate that with Node. The [Buffer](https://nodejs.org/en/knowledge/advanced/buffers/how-to-use-buffers/) class in Node corresponds to some raw memory allocated outside V8. Meaning you would have to interact with the raw memory to simulate the Buffer.from() function.

**Comment by rene-bayer** [comment]
@itchannel do you want to release it for hacs? :)

**Comment by itchannel** [comment]
> @itchannel do you want to release it for hacs? :)

Will push to hacs in a few hours just need to finish off bug testing 👍

**Comment by Brandawg93** [comment]
@tonesto7 Which part of the code do you need Buffer for?

**Comment by rene-bayer** [comment]
![image](https://user-images.githubusercontent.com/11734245/176638837-541d7a75-22ab-4147-9398-fd2d3a914a5e.png)

Yes,  works again :-)
thx :1st_place_medal:

**Comment by khpylon** [comment]
Thanks everyone.  It looks like I got the Java interface working for my app.

**Comment by itchannel** [comment]
Closing old issue for housekeeping
