### ISSUE TITLE
New Setup Broken?

### ISSUE THREAD

**Issue by sup3rm3ga** [itchannel/fordpass-ha#197]
I was experiencing some wonkiness so deleted and attempted to re-add my integration. Now getting this error:

```
Logger: custom_components.fordpass.config_flow
Source: custom_components/fordpass/fordpass_new.py:358
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: 10:53:55 AM (3 occurrences)
Last logged: 11:02:00 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fordpass/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fordpass/config_flow.py", line 49, in validate_input
    result3 = await hass.async_add_executor_job(vehicle.vehicles)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fordpass/fordpass_new.py", line 358, in vehicles
    r.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://services.cx.ford.com/api/dashboard/v1/users/vehicles
```

**Comment by hokenoah** [comment]
Same here -- long-time viewer of Home Assistant projects but finally got it set up in my own home. Went to setup Fordpass and the dialogue box just says "Unexpected error."

Not sure how to get the log you pulled above, but I'm sure it's the same issue?

**Comment by limbicactually** [comment]
Following

**Comment by bearli97** [comment]
Unexpected error.

With recent master branch.

**Comment by slamdf150xc** [comment]
I'm also seeing the "Unexpected error" message when attempting to setup the integration for the first time. HA logs below.


`2022-07-20 13:26:58 DEBUG (MainThread) [custom_components.fordpass.config_flow] North America & Canada`
`2022-07-20 13:26:58 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/slamdf150xc@gmail.com_fordpass_token.txt`
`2022-07-20 13:26:58 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] New System`
`2022-07-20 13:26:59 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] {'access_token': '*****', 'refresh_token': '*****', 'ford_consumer_id': '*****', 'expires_in': 1800, 'refresh_expires_in': 31556952, 'expiry_date': 1658343419.4182801}`
`2022-07-20 13:26:59 DEBUG (SyncWorker_1) [custom_components.fordpass.fordpass_new] Token is valid, continuing`
`2022-07-20 13:26:59 DEBUG (SyncWorker_1) [custom_components.fordpass.fordpass_new] {"requestStatus":"UNAVAILABLE","error":{"statusContext":"HTTP","statusCode":502,"message":"FIG request failed: "},"lastRequested":null}`

Thank you for this integration, this is a really cool project.

**Comment by itchannel** [comment]
Fixed in latest version 1.36 👍

**Comment by sup3rm3ga** [comment]
Confirmed, thank you!

**Comment by slamdf150xc** [comment]
Resolved for me.

Thanks for the awesome work!
