### ISSUE TITLE
GPS Not always updating

### ISSUE THREAD

**Issue by pendlet** [itchannel/fordpass-ha#200]
GPS randomly updates and does not refresh when doing a Fordpass: refresh_status. Sometimes the GPS is very accurate and others it takes hours and sometimes days before the correct GPS lat and long are given.  gpsState always says UNSHIFTED even when its working. Should that change? 

latitude: '38.xxxxxxxx'
longitude: '-76.xxxxxxx'
gpsState: UNSHIFTED
status: LAST_KNOWN
timestamp: 07-27-2022 16:40:50
icon: mdi:radar
friendly_name: fordpass_gps

**Comment by itchannel** [comment]
GPS coordinates are only updated when the car polls to the Ford API. You can manually poll the car using the "fordpass_refresh" service which will manually poll the car but is battery intensive if used to often. Unfortunately this is a Ford limitation and not the integration.
