### ISSUE TITLE
How to complete remove and start over

### ISSUE THREAD

**Issue by mikje** [itchannel/fordpass-ha#201]
Since the remove button was not available in  HA i tried to remove manually,
removed all fordpass entities but now stuck with the fordpass integration mentioing 1 device

![image](https://user-images.githubusercontent.com/12999690/181984733-3cc20014-c07f-4186-8e79-9d87366e34c3.png)

How do i remove this? 
I want to start over with this integration in the hope that it wil work then as well.

I uses hassio with hacs

Simply removing the map fordpass from the custonm components did not do this job.

Besides this if I add a new fordpass config, it complains about my login credentials that ARE correct

**Comment by mikje** [comment]
removal was succesfull,  but reinsalling not.  It keeps saying incorrect login

**Comment by itchannel** [comment]
Can you please provide a copy of your logs that mention fordpass.

**Comment by woempiej** [comment]
Do you have a backup from before installing the integration?

**Comment by mikje** [comment]
I don t have a backup  from before installing  the mentioned link gives me
![Screenshot_20220821-004950_Samsung Internet](https://user-images.githubusercontent.com/12999690/185780090-51f30f50-8e76-4788-831a-3cb44349c26e.jpg)

Also from the NL btw

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
