### ISSUE TITLE
Probably account blocked due to integration not working 

### ISSUE THREAD

**Issue by jansenfd** [itchannel/fordpass-ha#203]
For all who are struggling : 

At some point there were a lot of reports due to the integration not working. It appears that this was an issue on Ford side changing login api or something I think?

But now it appears that my account is completely blocked at Ford because there were too many login attempts.

I cannot login anymore in Ford website, fordpass app and the home assistant integration is not working anymore.

Password reset works but login attempt fails, website states error code CSIAH0320E.

Tried emailing Ford and fordpass but totally no response from them.

Unknown solution up until now.

**Comment by itchannel** [comment]
I had this happen to me once, but the backend system unlocked the account after a period of time. Make sure your not still trying to login and the integration isn't running. Then give it 24hrs and see if it unlocks.

**Comment by jansenfd** [comment]
Unfortunately I have it disabled for a week now and still not able to login in the fordpass app and ford website.

To be honest I have totally no indication how to solve this Ford doesn't respond to any emails so far.

**Comment by austinbeam** [comment]
I finally got through to FordPass support and they got back to me today. My account had been blocked, and they are having to manually unblock it. They also told me that this is a one-time thing and subsequently they will not unblock it.

I saw in #214 that they block after 20,000 hits in a week. The person I talked to acted like they don't allow any external access, so I'm not sure what to believe. I can say I had this working for well over a year before the account was blocked. Guess I'm going to chance it because I really value the functionality this integration provides, particularly the ability set up an automation to lock the doors nightly.

Wanted to close the loop since I have not had this working for some time now. Will reinstall once I get access back. Hopefully I can stay unblocked.

**Comment by jansenfd** [comment]
> I finally got through to FordPass support and they got back to me today. My account had been blocked, and they are having to manually unblock it. They also told me that this is a one-time thing and subsequently they will not unblock it.
> 
> I saw in #214 that they block after 20,000 hits in a week. The person I talked to acted like they don't allow any external access, so I'm not sure what to believe. I can say I had this working for well over a year before the account was blocked. Guess I'm going to chance it because I really value the functionality this integration provides, particularly the ability set up an automation to lock the doors nightly.
> 
> Wanted to close the loop since I have not had this working for some time now. Will reinstall once I get access back. Hopefully I can stay unblocked.

I just got nowhere with the Dutch fordpass support. They even wanted to send me to the dealer to update the and I quote : "G2234484-2.0
Provisionering telematicamodule (TCU)"
But this is nuts, it has to do with the account.

So what I did was completely reset the fordpass connectivity from a reset in my car. And register my VIN to another email adres and bam it worked. This was September 21st.

And now today: after an email no fordpass acces and with my Ford website email adress again the error  CSIAH0320E. Email:

Ford Motor Company • [noreply@fordcloudapp.com](mailto:noreply@fordcloudapp.com) 

IBM Security Verify
Your account information was changed.

You are receiving this email because one or more pieces of information related to your account, xxxxxxx@gmail.com, were updated for subscription fcis.ice.ibmcloud.com. Please contact your system administrator if you did not request these changes.

Changed Information:
Enabled:	FALSE

**Comment by JVTEAM** [comment]
> > I finally got through to FordPass support and they got back to me today. My account had been blocked, and they are having to manually unblock it. They also told me that this is a one-time thing and subsequently they will not unblock it.
> > I saw in #214 that they block after 20,000 hits in a week. The person I talked to acted like they don't allow any external access, so I'm not sure what to believe. I can say I had this working for well over a year before the account was blocked. Guess I'm going to chance it because I really value the functionality this integration provides, particularly the ability set up an automation to lock the doors nightly.
> > Wanted to close the loop since I have not had this working for some time now. Will reinstall once I get access back. Hopefully I can stay unblocked.
> 
> I just got nowhere with the Dutch fordpass support. They even wanted to send me to the dealer to update the and I quote : "G2234484-2.0 Provisionering telematicamodule (TCU)" But this is nuts, it has to do with the account.
> 
> So what I did was completely reset the fordpass connectivity from a reset in my car. And register my VIN to another email adres and bam it worked. This was September 21st.
> 
> And now today: after an email no fordpass acces and with my Ford website email adress again the error CSIAH0320E. Email:
> 
> Ford Motor Company • [noreply@fordcloudapp.com](mailto:noreply@fordcloudapp.com)
> 
> IBM Security Verify Your account information was changed.
> 
> You are receiving this email because one or more pieces of information related to your account, [xxxxxxx@gmail.com](mailto:xxxxxxx@gmail.com), were updated for subscription fcis.ice.ibmcloud.com. Please contact your system administrator if you did not request these changes.
> 
> Changed Information: Enabled: False.
> 
> Unknown who my administrator is. Who did you contacted to about this issue?

Got the same e-mail, now I'm locked out.

**Comment by itchannel** [comment]
Ford seem to be cracking down on API calls. In the latest version I have reduced the poll time to 15mins instead of 5 which will drastically reduce calls to the API. 

It's a shame Ford won't interact with developers so we could build an official integration where we know the exact limits and what can/can't be done.

**Comment by GeneralLouis** [comment]
Reposting here from issue 214: Got a definite answer on why my account was locked: Cyber security team checked the logs and my account swapped IPs 1500 times in a 24 hour period so they disabled my account.

The FordPass help desk can enable peoples accounts again.

What I'm confused about is how that happened? Would the Nabu Casa cloud cause such a thing with outbound traffic?

**Comment by jansenfd** [comment]
May I ask you what helpdesk email address you have used and who you talked to?

**Comment by GeneralLouis** [comment]
Actually to clarify from the other issue tracker, the FordPass help desk will put in a ticket to the internal team that can enable your account. My contact is within Ford IT Cyber Security team.

**Comment by YBonline** [comment]
> Reposting here from issue 214: Got a definite answer on why my account was locked: Cyber security team checked the logs and my account swapped IPs 1500 times in a 24 hour period so they disabled my account.
> 
> The FordPass help desk can enable peoples accounts again.
> 
> What I'm confused about is how that happened? Would the Nabu Casa cloud cause such a thing with outbound traffic?

I got told it "looks like I was using HomeBridge and that will get your account banned". They kept asking me what third party apps I was using and I told them I was using the FordPass app on a lot of different phones, and they said there policy is each phone needs to be using a different Ford account, so after my account is re-enabled, I should make a separate account for each phone, and then log into each account, request to access each car, and approve it from the main account. They told me if I'm banned again it will be permanent. I'm waiting to be re-enabled (they said by Monday), but is the obvious workaround here to just create another Ford account from your main one, share the vehicles with that one, and use that for Home Assistant?

Does anyone have multiple FordPass accounts tied to the same vehicle and can confirm that possibly only 1 gets locked out while the others remain active?

**Comment by austinbeam** [comment]
>  is the obvious workaround here to just create another Ford account from your main one, share the vehicles with that one, and use that for Home Assistant?

This is brilliant, I'm setting it up this way to derisk potentially losing my primary account. Seems to be working so far and based on the way their vehicle sharing works I'd be surprised if this could lock multiple accounts. Thanks for sharing!

**Comment by rpdanjou** [comment]
> > is the obvious workaround here to just create another Ford account from your main one, share the vehicles with that one, and use that for Home Assistant?
> 
> This is brilliant, I'm setting it up this way to derisk potentially losing my primary account. Seems to be working so far and based on the way their vehicle sharing works I'd be surprised if this could lock multiple accounts. Thanks for sharing!

Also using this approach, has been working for weeks now. Great tool. Keep up the good work!

**Comment by itchannel** [comment]
Closing as no reports of blocks for a few months using the new poll interval
