### ISSUE TITLE
Dashboard Icon mdi:android-messages was renamed to mdi:message-text

### ISSUE THREAD

**Issue by BillyFKidney** [itchannel/fordpass-ha#204]
The auto generated sensor for the dashboard is using an out of date icon.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/65253277/183522072-fcda0785-75f4-4a7e-8001-53b4441dcb12.png">
<img width="383" alt="image" src="https://user-images.githubusercontent.com/65253277/183522142-48c00554-b02f-4111-bd92-209770d7f262.png">

Ford Pass Integration Version 1.36

```
Logger: frontend.js.latest.202208020
Source: components/system_log/__init__.py:227 
First occurred: 5:49:42 AM (17 occurrences) 
Last logged: 2:57:41 PM

Icon mdi:android-messages was renamed to mdi:message-text, please change your config, it will be removed in version 2022.10.
```

**Comment by itchannel** [comment]
Fixed in 1.37
