### ISSUE TITLE
"ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for <MY VIN>"

### ISSUE THREAD

**Issue by Krolitian** [itchannel/fordpass-ha#205]
Error as title shows. This is the result of the car constantly going offline for 5 minutes at a time:
![Screenshot_29](https://user-images.githubusercontent.com/82565931/183809744-96693c98-81bd-4b01-bfb5-82672e0d6117.png)

Just constant areas of "unavailable" where I can't monitor or interact with the car.

**Comment by itchannel** [comment]
This is a bug with the API where it times out occasionally resulting in the sensors going unavailable to next refresh. I did try adding timeouts etc but didn't seem to help.

**Comment by Krolitian** [comment]
Is there any way that a future release could enable a config option where if the timeout occurs, it doesn't write the "unavailable" unless two timeouts occur in a row so that the 5 min timeouts are ignored, the data looks normal, and also the remote start button won't be disabled when another API call for it to start would still work?

Like you could do `ignore_consecutive_timeouts: '0'` and we could put the number of timeouts we allow, where it'll show the latest successful data and if it passes the limit, it'll show as unavailable.

**Comment by itchannel** [comment]
I'm testing code at the moment that might help but too early to tell yet 👍

**Comment by Krolitian** [comment]
Excited to see the results! Love the work you've put into this integration. My favorite use of HA so far.

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
