### ISSUE TITLE
Tire pressure

### ISSUE THREAD

**Issue by woempiej** [itchannel/fordpass-ha#208]
Hi, 

Thanks for this great integration for HA.
I don't understand the below data "STATUS_LOW" because it is incorrect. I wan't to set a message if the tire pressure is low, but it is always low :)

![afbeelding](https://user-images.githubusercontent.com/62903344/185807098-495f5e8b-06cd-49fe-bb43-4f2871f27df9.png)

**Comment by woempiej** [comment]
Can I somewhere setup the "Recommended" tire pressure?
And is there an option to set the Oil status to % ? The fordpass app use the % for oil.

**Comment by woempiej** [comment]
> Hi,
> 
> Thanks for this great integration for HA. I don't understand the below data "STATUS_LOW" because it is incorrect. I wan't to set a message if the tire pressure is low, but it is always low :)
> 
> ![afbeelding](https://user-images.githubusercontent.com/62903344/185807098-495f5e8b-06cd-49fe-bb43-4f2871f27df9.png)

This is no PSI or kPa but BAR

![afbeelding](https://user-images.githubusercontent.com/62903344/186518277-d9de3b12-6bee-4a23-b616-a9dc1e886ad4.png)

**Comment by itchannel** [comment]
@woempiej the "STATUS_LOW" value is what is returned by the Ford API. In your situation I don't know why your car is reporting that as the pressures look ok but unfortunately that's a thing with your car not the integration. 

I'm confused by your 2nd post. You can set the unit used between psi or kPa in the integration options menu?

**Comment by woempiej** [comment]
PSI or kPa do not have the same values as BAR. The recommended Tire pressure is based on what?
I can't select the unit BAR.

**Comment by woempiej** [comment]
For the Oil I found the attribute :)
![afbeelding](https://user-images.githubusercontent.com/62903344/186737372-75864b0d-0ec8-4c8a-a0c5-7dc8f7c3736f.png)

**Comment by itchannel** [comment]
> PSI or kPa do not have the same values as BAR. The recommended Tire pressure is based on what? I can't select the unit BAR.

I'll look at adding BAR as an option in the next release

**Comment by itchannel** [comment]
Bar has now been added in 1.40
