### ISSUE TITLE
Error communicating with FordPass for VINNUMBER

### ISSUE THREAD

**Issue by JOHLC** [itchannel/fordpass-ha#21]
Hello!

First of all, thank you for this integration. I CANNOT wait to get it working. I have been looking for something like this since I started with HA in April.
I have a '17 Ford Fusion and I am trying to get this integration setup.
Installed via HACS and configured via Integrations but I am getting the errors below.  

For the username/PW I confirmed they were correct by signing into Ford's site
For the VIN I copied and pasted directly from the Ford site where I have my car registered. 

Could this be because I do not have the "connected" features? I have the Ford Pass app and I can still view mileage, etc. 

LOG:
`
Config entry for fordpass not ready yet. Retrying in 5 seconds
4:17:26 PM – config_entries.py (WARNING) - message first occurred at 4:07:56 PM and shows up 11 times
Error fetching fordpass data: Error communicating with FordPass for VINNUMBER
4:17:26 PM – FordPass (ERROR) - message first occurred at 4:07:56 PM and shows up 11 times
Error communicating with FordPass for VINNUMBER
4:17:26 PM – FordPass (WARNING) - message first occurred at 4:07:56 PM and shows up 11 times
'vehiclestatus'
4:17:26 PM – FordPass (WARNING) - message first occurred at 4:07:56 PM and shows up 11 times`

**Comment by itchannel** [comment]
That is an indication that it was unable to retrieve information from your car from the vehicle status endpoint. It is more than likely that your car doesn't support the features as I don't recall 17 model cars having a modem on board to relay information. 

However I'll add some debug functions later today and get you to update and enable debug mode for me so we can see exactly what is returned to diagnose exactly what's happening if that would be useful to you?

**Comment by JOHLC** [comment]
I've confirmed my car doesn't have a modem. I gets vehicle health reports through ford pass applink and that's about it. Only connects to wifi for sync updates. Guess I'll have to trade it in and get a newer model lol.

Cheers.
________________________________

**Comment by carlosvroque** [comment]
I've added the custom component and had the same "problem". I guess my car only sends the data to the app, it's shame. 

Still, great idea and I'll keep watching the development.

**Comment by pinballnewf** [comment]
I;ve a similar problem, and my vehicle definitely supports the functions - it DID work for a little while, but has gone 'unavailable' and the HA error log has many Error communicating with FordPass for <VIN> errors.
Is there any way to enable debug to see what's going on?

**Comment by itchannel** [comment]
It's because I haven't added in any code to run the refresh command as I removed it due to significant battery use. The next version I'll be adding debugging and a service function that can be called in home assistant to poll the car when required so people can choose.

**Comment by itchannel** [comment]
Refresh has now been added to the code. I recommend creating an automation that runs the "fordpass.refresh_status" service on set intervals or events such as arriving home. That way it won't drain the battery. I'm still working on debug but that should resolve the issue for now that @pinballnewf was experiencing with outdated data.
