### ISSUE TITLE
Unable to add fordpass_odometer as a statistic

### ISSUE THREAD

**Issue by k1lln1n3** [itchannel/fordpass-ha#210]
I'm trying to use fordpass_odometer to populate a bar graph to show distance travelled per month and map it to energy used from my charger. When I add it to the statistics dashboard, it doesn't show up in the list of statistics. I'm not sure if I'm doing something wrong or its not implemented. Please let me know. Thank you!

**Comment by itchannel** [comment]
Statistic support has been added in 1.39 (Latest) for the odometer. so give it a go now.
