### ISSUE TITLE
Door status 'open', but all doors are locked/closed

### ISSUE THREAD

**Issue by Calimerorulez** [itchannel/fordpass-ha#211]
Hi,

I just discovered this nice addon, and I'm trying to get things to work. Curious about the door status, I've locked the car, but the overview says 'open':

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1130552/191991227-61efe64c-91b0-4a66-b596-03dcc5c2e6f2.png">

What does 'ajar' exactly mean? Is that why the overall status is 'open'?

**Comment by Calimerorulez** [comment]
I've double checked, but the passenger door is really locked and closed.

**Comment by itchannel** [comment]
Sorry been away for a while. Yeah it will only report Closed if all doors are set to the Close condition. If you keep getting the "Ajar" status then there might be something faulty with your door lock

**Comment by safehome-jdev** [comment]
> Sorry been away for a while. Yeah it will only report Closed if all doors are set to the Close condition. If you keep getting the "Ajar" status then there might be something faulty with your door lock

I don't think it's only @Calimerorulez door. I get the same prompt on a 2017 Ford Escape with an access point about 15-20 feet away.

**Comment by Calimerorulez** [comment]
I've noticed, when, like @safehome-jdev , using a fairly remote access point, like at home, I've got the symptoms. When not near an access point (like not at home), the doors are shown as closed.

How does the connection on non-wifi work? Does the car have a builtin modem? I haven't enabled/bought the subscription.

**Comment by woempiej** [comment]
H,

I have the same issue with the windows since updating to newest version

![afbeelding](https://user-images.githubusercontent.com/62903344/218553042-91e2dbe5-d6be-4a86-8037-3d4bc02f3994.png)

![afbeelding](https://user-images.githubusercontent.com/62903344/218553209-f3236019-85fa-4701-84ab-482cb31c9304.png)

**Comment by woempiej** [comment]
Yes works. thank you!

![afbeelding](https://user-images.githubusercontent.com/62903344/218835777-20436a76-e716-4b14-8387-697330fd4208.png)

**Comment by michalk-k** [comment]
I would like to join this thread. 
It reports Ajar for one of my doors too (Left rear), while all doors are closed for sure. In fact, locks cannot be locked if any of the doors are not closed. This leads me to the conclusion that maybe there is some issue that can be fixed.
How can I debug data received from the ford server?

**Comment by BenDavidson90** [comment]
Hi,
Same problem here. It reports that the doors are open but they are closed.
I since drived and returned, nothing change, same status since install.

**Comment by gee-jay-bee** [comment]
I observed this today. Driver door reported ajar but was actually closed (and locked). 

I wonder if the car's modem reported status as the engine was turned off (or a short time after) as I had the door open for a while whilst unloading. 

When I realised that the door was reported as open, I returned to the vehicle to check. I then triggered a remote unlock and the status of the door corrected itself.

**Comment by michalk-k** [comment]
I guess something must be f*up in Ford vehicles. The fact they removed related features from the Ford app (alerts about open doors etc) might support this thesis

**Comment by itchannel** [comment]
The integration just reports the status from the Fordpass API. If you are getting out of date data like doors being unlocked then you might need to run the fordpass_refresh service to poll the car to get the latest data. I recommend this is done whenever returning home.
