### ISSUE TITLE
Entity to create button for Trunk and Frunk?

### ISSUE THREAD

**Issue by kroven9** [itchannel/fordpass-ha#212]
Hi,

Looking to be able to add a card to make buttons for the open frunk and trunk that are in the fordpass app. Would be really useful because HA allows you to make widgets in android where the fordpass app does not allow you to make widgets. Would be a neat work around for any of the remote access features to have quick access to on my phone.

**Comment by itchannel** [comment]
I'll have a look at the latest fordpass app and see if I can add in trunk/frunk controls where supported.

**Comment by SquidBytes** [comment]
I would also love this feature, but it is not in the FordPass app so I do not think we would be able to support it.
As this request is from 2022, I'm going to close this.
If the app updates and adds the feature, we should be able to add it.
