### ISSUE TITLE
batteryFillLevel not showing up as sensor

### ISSUE THREAD

**Issue by danyal** [itchannel/fordpass-ha#213]
I added the integration and it pulls many of the values fine but batteryFillLevel is not showing up as a sensor available (my car is an EV).

**Comment by Olum-hack** [comment]
I have the same problem. I think it must be just converted to a number?
![image](https://user-images.githubusercontent.com/42848723/229580321-60c77d95-3251-4bd6-9406-65afb9219db1.png)

**Comment by TomVanHal** [comment]
With my car its the radius of the car. Atm i have 338km left of charge. 
![IMG_6458](https://github.com/itchannel/fordpass-ha/assets/84924089/7ce8516f-ce76-46fa-b01f-a117e100690f)
![IMG_6459](https://github.com/itchannel/fordpass-ha/assets/84924089/65090ad6-e992-4275-8b4e-478b9441caa4)

**Comment by itchannel** [comment]
Currently it uses the EL Vehicle Distance to empty as the value but I could add a separate one to show charge level and DTE

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
