### ISSUE TITLE
Fuel level shows as 103%

### ISSUE THREAD

**Issue by plmcgrn** [itchannel/fordpass-ha#216]
Not sure why/how this could happen, but my fuel level is reporting higher than 100%.  This is a 2020 F-150 with the extended range fuel tank.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/889547/198938686-ea426950-7abe-4bf3-9975-ea74f48ce38a.png">

**Comment by itchannel** [comment]
The fuel sender can report values from -5 to 105. As technically you can fill the tank past 100% so you will see the Ford API showing more than 100% if you've just topped your tank up its normal 👍

**Comment by itchannel** [comment]
Closing as this is normal operation as mentioned.
