### ISSUE TITLE
Lock status only showing as "unlocked" in Home Assistant

### ISSUE THREAD

**Issue by BroManDudeGuyPhD** [itchannel/fordpass-ha#218]
My sensor in Home Assistant only shows door status as "unlocked" even after successfully locking with the integration. 

The sensor also becomes temporarily unavailable right before or after locking. I have a 2017 Escape Titanium

![image](https://user-images.githubusercontent.com/13458477/202527966-ee711e9f-adc4-4cec-8ae5-4fe4210ae4fb.png)

**Comment by itchannel** [comment]
@BroManDudeGuyPhD Can you send me a screenshot of the "fordpass_doorlock" in developer tools  so I can see the raw status. Also can you give me your status for "fordpass_alarm"

**Comment by BroManDudeGuyPhD** [comment]
Here is the lock state ![image](https://user-images.githubusercontent.com/13458477/206143931-d239e42b-7922-48b0-989a-4a8601cd5cd7.png)

Here is alarm. It's shown as error ever since installing, I assumed that was my car being older since it doesn't show window state, but I can't see that in FordPass either
![image](https://user-images.githubusercontent.com/13458477/206144265-3daab00a-dccd-4bc6-843a-b3d4158f4463.png)

**Comment by BroManDudeGuyPhD** [comment]
> @BroManDudeGuyPhD Can you send me a screenshot of the "fordpass_doorlock" in developer tools  so I can see the raw status. Also can you give me your status for "fordpass_alarm"

Let me know if you need anything else! I love this integration want to help any way I can

**Comment by itchannel** [comment]
Well that's an interesting alarm value. It looks like the API is reporting an ERROR status for your alarm and always unlocked. 

Does your car support locking/unlocking from the Fordpass application?

My guess would be as it's a 2017 model certain features aren't support such as door statuses maybe 🤔

**Comment by Jeppedy** [comment]
'lockStatus': {
        'value': 'ERROR',
        'status': 'CURRENT',
        'timestamp': '03-12-2023 23:19:40'
    },

And yes, mine car is a 2017 as well, a Ford CMax.  
I’ll just not use the Door Lock sensor, but it would be nice for you to update to remove sensors when they report back errors.  Otherwise, I’m loving your integration…. Thank you!!

**Comment by itchannel** [comment]
I will add this as a feature request to check if the Door lock status = ERROR and not add the sensor. Weird how the API just gives an "ERROR" response instead of just showing your vehicle doesn't support remote lock status.

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
