### ISSUE TITLE
Client ID not Unique to Each User

### ISSUE THREAD

**Issue by GeneralLouis** [itchannel/fordpass-ha#225]
I will preface with I am not extremely knowledgeable with OAuth flows but wouldn't having every single HA instance using the same client ID potentially be an issue?

In fordpass_new.py on lines 85 and 151, we are using a pre-filled Client ID.

Could this be the cause of a lot of HA lockouts? If Ford all of a sudden starts monitoring Client IDs differently and sees that this client ID is doing thousands of requests from different IP addresses couldn't this prompt automated actions against accounts?

**Comment by itchannel** [comment]
ClientID is a public identifier for the APP/API. It's whats used in oauth flow to identify the application so isn't unique per user. 

https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/

**Comment by GeneralLouis** [comment]
The article you sent says that "[The client ID] must also be unique across all clients that the authorization server handles", does this simply mean that the HA integration needs a unique ID for the API to identify? Or is this client ID the same as Fordpass?

(Feel free to close this issue with your response)

**Comment by GeneralLouis** [comment]
Disregard my comments, I saw your comment in another issue, reverting my client ID.

**Comment by itchannel** [comment]
> The article you sent says that "[The client ID] must also be unique across all clients that the authorization server handles", does this simply mean that the HA integration needs a unique ID for the API to identify? Or is this client ID the same as Fordpass?
> 
> (Feel free to close this issue with your response)
> 
> EDIT: I did a fresh install after getting my account back this morning, got configured, then went in and changed the last 2 digits on my client ID in the code and it successfully refreshed, though it may just be using a stored credentials and not re-authorizing access?

If the HA integration was fully supported then yes 100% there should be a unique clientID per application e.g. Fordpass, HA, Homebridge. However in this case Ford haven't fully released their 3rd party API so there isn't a way to request a ClientID currently. Usually the ClientID is used so you can identify what application is logging in etc so by setting a random ClientId you would be showing up as an unknown oauth source.

**Comment by GeneralLouis** [comment]
Ok thank you for taking the time to explain it to me and I really appreciate all the work you've put in to this integration.
