### ISSUE TITLE
odometer reading incorrect

### ISSUE THREAD

**Issue by cwallace** [itchannel/fordpass-ha#227]
The odometer on my 2021 Raptor is reading incorrectly. In the truck and also in the fordpass app the odometer shows 5611 miles, but in hass it is coming across as 9030. Not sure where to start troubleshooting this. Let me know if there are any specifics I can provide to help isolate the issue.

**Comment by cwallace** [comment]
Ah it looks like the reading states "9030 mi", but after installation the default setting is kilometers. 5611 miles = 9030 km. Looks like we just need to make sure that when km is selected that the stat comes across with km after the number instead of mi.

**Comment by jpettitt** [comment]
I'm also seeing this on my 2022 F150 Limited, if I set the units to KM HA does the conversion and it's still wrong by the same factor.

**Comment by G2Secure** [comment]
Same for me  - 2020 Ford Edge here.   
Make sure you go back to the integration, setup the MI to KM and the Kpa to PSI.
Then reload the integration. that worked for me.  
![Untitled](https://user-images.githubusercontent.com/124701103/217920018-4412140b-7aa6-4444-abd6-a504fb4416b8.png)

**Comment by itchannel** [comment]
Fixed in 1.47
