### ISSUE TITLE
Improper handling of drive before start again use case

### ISSUE THREAD

**Issue by sdahlberg** [itchannel/fordpass-ha#228]
After starting my car two times without actually driving, the API prohibits a third attempt. Using the FordPass app the user is presented a message that you need to drive first before trying to start again.

In this case the Ford API returns a 404 with this response body:

```
{
    'statusCode': 404, 
    'message': 'Resource not found'
}
```

This body is not handled properly in the python script as it results in:
```
  File "/config/custom_components/fordpass/fordpass_new.py", line 468, in __pollStatus
    if result["status"] == 552:
KeyError: 'status'
```

Would expect to check for this specific message and communicate this in the HASS ui.

**Comment by SquidBytes** [comment]
I'm going to close this because there have been large changes since then.
Please open a new issue for any new issues :)
