### ISSUE TITLE
HA 2023.01 / can't set attribute 'options'

### ISSUE THREAD

**Issue by Strohhutpat** [itchannel/fordpass-ha#231]
In 2023.01 fordpass-ha doesn't really work anymore 

Logger: homeassistant.components.sensor
Source: custom_components/fordpass/sensor.py:45
Integration: Sensor (documentation, issues)
First occurred: 18:51:42 (2 occurrences)
Last logged: 19:52:04

Error while setting up fordpass platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fordpass/sensor.py", line 25, in async_setup_entry
    sensor = CarSensor(entry, key, config_entry.options)
  File "/config/custom_components/fordpass/sensor.py", line 45, in __init__
    self.options = options
AttributeError: can't set attribute 'options'

**Comment by itchannel** [comment]
If you want to try the 1.41 beta/preRelease it should be fixed in HA 2013 Beta

https://github.com/itchannel/fordpass-ha/releases/tag/1.41-PreRelease

**Comment by Strohhutpat** [comment]
> If you want to try the 1.41 beta/preRelease it should be fixed in HA 2013 Beta
> 
> https://github.com/itchannel/fordpass-ha/releases/tag/1.41-PreRelease

Thx, the prerelease is working

**Comment by itchannel** [comment]
Fixed in 1.41
