### ISSUE TITLE
Service Due

### ISSUE THREAD

**Issue by stumiles86** [itchannel/fordpass-ha#235]
Hello again,
Back with another suggestion rather than an issue,
Can we add the service due date / due in x Miles /Kilometres?
Here is the section in the log that contains this info

{"nextIntervalMiles":36000,"nextIntervalKMs":57600,"estimatedDate":{"year":"2023","month":"01","day":"09"},"remainingMiles":950,"remainingKMs":1500},"dtsMessage":{"para1":"Based on your driving requirements, it\'s time for your next recommended service. Book a service now to keep your vehicle running at its best. ","para2":"","para3":"Let\'s book that now."}}}',

**Comment by itchannel** [comment]
Can you send me the full vehicle output as I don't have service data at all showing for my vehicles so need to know exactly where it shows in the json to be able to look at adding support.

**Comment by stumiles86** [comment]
See below:

`{'vin': 'DEDACTEDVIN', 'lockStatus': {'value': 'UNLOCKED', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'alarm': {'value': 'NOTSET', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'PrmtAlarmEvent': {'value': 'Null', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'odometer': {'value': 59994.0, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'fuel': {'fuelLevel': 29.239224, 'distanceToEmpty': 224.0, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'gps': {'latitude': '51.5110917', 'longitude': '0.2865483', 'gpsState': 'UNSHIFTED', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'remoteStart': {'remoteStartDuration': 0, 'remoteStartTime': 0, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'remoteStartStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'battery': {'batteryHealth': {'value': 'STATUS_GOOD', 'timestamp': '02-15-2023 08:15:16'}, 'batteryStatusActual': {'value': 13, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}}, 'oil': {'oilLife': 'STATUS_LOW', 'oilLifeActual': 3, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'tirePressure': {'value': 'STATUS_GOOD', 'timestamp': '01-07-2023 10:03:56'}, 'authorization': 'AUTHORIZED', 'TPMS': {'tirePressureByLocation': {'value': 1, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'tirePressureSystemStatus': {'value': 'Systm_Activ_Composite_Stat', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'dualRearWheel': {'value': 0, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'leftFrontTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'leftFrontTirePressure': {'value': '259', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'rightFrontTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'rightFrontTirePressure': {'value': '292', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'outerLeftRearTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'outerLeftRearTirePressure': {'value': '249', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'outerRightRearTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'outerRightRearTirePressure': {'value': '250', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'innerLeftRearTireStatus': {'value': 'Not_Supported', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'innerLeftRearTirePressure': None, 'innerRightRearTireStatus': {'value': 'Not_Supported', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'innerRightRearTirePressure': None, 'recommendedFrontTirePressure': {'value': 30, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'recommendedRearTirePressure': {'value': 26, 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}}, 'firmwareUpgInProgress': {'value': False, 'timestamp': '06-25-2021 09:53:15'}, 'deepSleepInProgress': {'value': False, 'timestamp': '09-04-2022 17:46:43'}, 'ccsSettings': {'timestamp': '12-30-2021 07:11:19', 'location': 1, 'vehicleConnectivity': 1, 'vehicleData': 1, 'drivingCharacteristics': -1, 'contacts': -1}, 'lastRefresh': '02-15-2023 08:15:16', 'lastModifiedDate': '02-15-2023 08:15:48', 'serverTime': '02-15-2023 14:46:09', 'batteryFillLevel': None, 'elVehDTE': None, 'hybridModeStatus': None, 'chargingStatus': None, 'plugStatus': None, 'chargeStartTime': None, 'chargeEndTime': None, 'preCondStatusDsply': None, 'chargerPowertype': None, 'batteryPerfStatus': None, 'outandAbout': {'value': 'PwPckOffTqNotAvailable', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'batteryChargeStatus': None, 'dcFastChargeData': None, 'windowPosition': {'driverWindowPosition': {'value': 'Fully_Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'passWindowPosition': {'value': 'Fully_Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'rearDriverWindowPos': {'value': 'Fully_Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'rearPassWindowPos': {'value': 'Fully_Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}}, 'doorStatus': {'rightRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'leftRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'driverDoor': {'value': 'Ajar', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'passengerDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'hoodDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'tailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'innerTailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}}, 'ignitionStatus': {'value': 'Off', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'batteryTracLowChargeThreshold': None, 'battTracLoSocDDsply': None, 'dieselSystemStatus': {'exhaustFluidLevel': {'value': '71.200000', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'filterSoot': None, 'ureaRange': {'value': '4000', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'metricType': {'value': 'Inactive', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}, 'filterRegenerationStatus': {'value': 'DPF_Normal_Operation', 'status': 'CURRENT', 'timestamp': '02-15-2023 08:15:48'}}, 'messages': [{'id': '1', 'messageId': '1281653178', 'messageSubject': 'SAVE £30 OFF SELECTED SERVICES IN FEBRUARY', 'messageBody': 'Run smoothly into 2023 by ensuring your vehicle service is ticked off your new year’s to-do-list by the end of February, with £30 off when booked online using code FORD30*. Book a Ford Scheduled Service, recommended by Ford and tailored to your car ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '02/02/2023 02:09:35 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"490003042|GBR|","CampaignId":"FP_GBR_EN_OSB_FEB_OP6799"}', 'isRead': False}, {'id': '2', 'messageId': '-687506478', 'messageSubject': 'Recommended service required now', 'messageBody': 'Based on your driving requirements, your next recommended service is due. Book a service now to keep your vehicle running at its best.', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '01/20/2023 09:21:04 AM', 'priority': 2, 'messageTypeId': 10008, 'highlighted': True, 'relevantVin': 'DEDACTEDVIN', 'contentType': 'Text', 'metadata': '{"progNotificationMetaData":{"featureType":"OLSM","confidenceLevel":1,"shouldShow":true,"urgency":"H","messageCode":"OLSM_2EU","messageDesc":"Recommended service required now","eventTime":"2023-01-20 09:20:30","severity":"2","featureData":{"nextIntervalMiles":36000,"nextIntervalKMs":57600,"estimatedDate":{"year":"2023","month":"01","day":"20"},"remainingMiles":0,"remainingKMs":50},"dtsMessage":{"para1":"Based on your driving requirements, your next recommended service is due. Book a service now to keep your vehicle running at its best.","para2":"","para3":"Let\'s book that now."}}}', 'isRead': True}, {'id': '3', 'messageId': '353959470', 'messageSubject': 'Recommended service required soon', 'messageBody': "Based on your driving requirements, it's time for your next recommended service. Book a service now to keep your vehicle running at its best. ", 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '12/26/2022 10:42:18 AM', 'priority': 2, 'messageTypeId': 10008, 'highlighted': True, 'relevantVin': 'DEDACTEDVIN', 'contentType': 'Text', 'metadata': '{"progNotificationMetaData":{"featureType":"OLSM","confidenceLevel":1,"shouldShow":true,"urgency":"M","messageCode":"OLSM_1aEU","messageDesc":"Recommended service required soon","eventTime":"2022-12-26 10:41:52","severity":"1","featureData":{"nextIntervalMiles":36000,"nextIntervalKMs":57600,"estimatedDate":{"year":"2023","month":"01","day":"09"},"remainingMiles":950,"remainingKMs":1500},"dtsMessage":{"para1":"Based on your driving requirements, it\'s time for your next recommended service. Book a service now to keep your vehicle running at its best. ","para2":"","para3":"Let\'s book that now."}}}', 'isRead': True}, {'id': '4', 'messageId': '1670730382', 'messageSubject': 'Diesel Exhaust Fluid  ', 'messageBody': 'The AdBlue® diesel exhaust fluid level is low.', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '12/21/2022 05:13:28 PM', 'priority': 2, 'messageTypeId': 10001, 'highlighted': True, 'relevantVin': 'DEDACTEDVIN', 'contentType': 'Text', 'metadata': '{"wilCode":"600F27","dtcCode":null,"failureCode":null,"displaySequence":1086,"severity":"1","components":{"version":"1.0","headline":{"enable":"1"},"icon":{"assetLocation":"Local","icon":"diesel_exhaust_fluid_level_indicator"},"actions":{"roadSideAssistance":"0","scheduleService":"1"}}}', 'isRead': True}, {'id': '5', 'messageId': '356227820', 'messageSubject': 'Tyre Pressure Monitor System Warning', 'messageBody': 'The Tyre Pressure Monitoring System has detected one or more tyres is significantly underinflated.', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '12/15/2022 09:41:52 AM', 'priority': 2, 'messageTypeId': 10001, 'highlighted': True, 'relevantVin': 'DEDACTEDVIN', 'contentType': 'Text', 'metadata': '{"wilCode":"600E27","dtcCode":null,"failureCode":null,"displaySequence":4000,"severity":"1","components":{"version":"1.0","headline":{"enable":"1"},"icon":{"assetLocation":"Local","icon":"tire_pressure_monitor"},"actions":{"roadSideAssistance":"1","scheduleService":"1"}}}', 'isRead': True}, {'id': '6', 'messageId': '1019533101', 'messageSubject': 'Tyre Pressure Monitor System Warning', 'messageBody': 'The Tyre Pressure Monitoring System has detected one or more tyres is significantly underinflated.', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '12/06/2022 09:48:37 AM', 'priority': 2, 'messageTypeId': 10001, 'highlighted': True, 'relevantVin': 'DEDACTEDVIN', 'contentType': 'Text', 'metadata': '{"wilCode":"600E27","dtcCode":null,"failureCode":null,"displaySequence":4000,"severity":"1","components":{"version":"1.0","headline":{"enable":"1"},"icon":{"assetLocation":"Local","icon":"tire_pressure_monitor"},"actions":{"roadSideAssistance":"1","scheduleService":"1"}}}', 'isRead': True}, {'id': '7', 'messageId': '166306285', 'messageSubject': 'Is your Ford summer ready?', 'messageBody': 'Hi there, Get your Ford ready for the road this summer, with your next Ford Scheduled or Essential Service. Booking through FordPass couldn’t be easier, and right now, you can save £20 on your next Ford Service when booked and completed before the ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '06/06/2022 03:57:23 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"414104805|GBR|","CampaignId":"FP_GBR_EN_OSB_OP5430"}', 'isRead': False}, {'id': '8', 'messageId': '524374986', 'messageSubject': 'FordPass takes the hassle out of service bookings ', 'messageBody': 'Hi there, Don’t let a little thing like car maintenance get in the way of your bank holiday plans! Keep your vehicle performing at its best. Booking through FordPass couldn’t be easier, and right now, you can save £20 on your next Ford Service when ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '05/24/2022 09:58:11 AM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"410861372|GBR|","CampaignId":"FP_GBR_EN_Platinum Jubilee UK_OP5355_IOS"}', 'isRead': False}, {'id': '9', 'messageId': '1789809944', 'messageSubject': 'Some FordPass features will be discontinued', 'messageBody': 'Hi there, We’d just like to let you know that the current performance of the features below does not meet our expectations for your experience and therefore we will be discontinuing them in the near future: • Journeys• Send Destination To Vehicle• ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '05/16/2022 12:57:17 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"408898764|GBR|","CampaignId":"FP_GBR_EN_TCU FEATURES DECOMMISION_OP5335"}', 'isRead': False}, {'id': '10', 'messageId': '-490606769', 'messageSubject': 'Potential disruption to some FordPass services ', 'messageBody': 'Hi there, We will be carrying out important maintenance to our service network between 15.00 (GMT+1) on Saturday 30th April, and 15.00 (GMT+1) on Monday 2nd May. During this period, certain remote features and services may become disrupted. You may ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '04/28/2022 08:53:44 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"403318523|GBR|","CampaignId":"FP_GBR_EN_Outage_Weekend_OP5301"}', 'isRead': False}, {'id': '11', 'messageId': '52847081', 'messageSubject': 'Effortless service bookings!', 'messageBody': 'Whether it’s an MOT, scheduled service, vehicle health check or even just a quick assessment of your tyre treads, we’ll help get you ready for your road trip this bank holiday weekend. And the best thing is that some of the checks we offer are ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '04/06/2022 05:51:43 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"396465176|GBR|","CampaignId":"FP_GBR_EN_Easter_BH_OP5101"}', 'isRead': False}, {'id': '12', 'messageId': '-1980356242', 'messageSubject': 'Festive tips for the road', 'messageBody': 'Whether you’re shopping for gifts, or taking a winter road trip, FordPass can take the hassle out of driving this festive season. If your vehicle has FordPass Connect and an automatic transmission, you can use your phone to start it remotely so that ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '12/20/2021 06:08:57 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"364540083|GBR|","CampaignId":"FP_GBR_EN_XMAS_Wishes_OP4303"}', 'isRead': False}, {'id': '13', 'messageId': '-1941595106', 'messageSubject': 'New SecuriAlert Scheduler', 'messageBody': 'Helping to keep your car secure is now easier than ever. With the new SecuriAlert Scheduler, you don’t have to remember to activate SecuriAlert manually. Instead, you can set a schedule for when you want your car to be in a heightened state of ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '10/05/2021 09:22:29 AM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{"DeliveryId":"341489528|GBR|","CampaignId":"FP_GBR_EN_SecuriAlert_Scheduler_A_OP3200"}', 'isRead': False}, {'id': '14', 'messageId': '-1125809540', 'messageSubject': 'My Journeys has been updated', 'messageBody': 'Hi there , We’ve listened to your feedback and are working to make sure you have seamless experience and valuable information with My Journeys . That’s why, you will notice we have made a few changes ! We have started by streamlining how My Journeys ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '09/17/2021 06:06:25 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{{"DeliveryId":"336545289|GBR|","CampaignId":"FP_GBR_EN_Journeys_OP3180"}', 'isRead': False}, {'id': '15', 'messageId': '1947219426', 'messageSubject': 'Drive smarter', 'messageBody': 'Did you know FordPass can help make you a better driver? My Journeys lets you view the details of your previous trips, including distance, average speed, and fuel usage. You can also see tailored Driving Insights to help you drive more efficiently. ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '08/27/2021 04:33:14 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{{"DeliveryId":"331384779|GBR"}', 'isRead': True}, {'id': '16', 'messageId': '294000252', 'messageSubject': 'Get better rates and avoid confusion', 'messageBody': 'Travelling across Europe this summer?  FordPass have teamed up with tolltickets to get you exclusive rates and help you take the hassle out of paying for tolls and local road charges. Make the purchase through the app and then you can use the ', 'messageType': 'EXTERNALNOTIFICATIONREQUEST', 'createdDate': '08/10/2021 04:29:47 PM', 'priority': 1, 'messageTypeId': 20001, 'highlighted': True, 'relevantVin': '', 'contentType': 'Html', 'metadata': '{{"DeliveryId":"324605353|GBR"}', 'isRead': True}, {'id': '17', 'messageId': '-709855899', 'messageSubject': 'Milestone Reached!', 'messageBody': 'One giant leap', 'messageType': 'GENERAL', 'createdDate': '05/14/2021 12:01:39 PM', 'priority': 1, 'messageTypeId': 260, 'highlighted': False, 'relevantVin': 'DEDACTEDVIN', 'contentType': 'Text', 'metadata': '{"ShowTile": 1, "TileClickAction": "ShowMessageDetail","TileTitle": "Milestone Reached!"}', 'isRead': True}]}
`

**Comment by stumiles86** [comment]
Actually. Looking at it again. Looks like that data is from a message reminding me my service is due soon. Not from a sensor at all.
