### ISSUE TITLE
Fordpass HA Integration only has 3 Entities Now

### ISSUE THREAD

**Issue by GeneralLouis** [itchannel/fordpass-ha#238]
Noticed my FordPassHA was acting up again and saying unavailable for every entity for a few days, so I re-setup the entire integration, now I only get 3 entities on setup:
-Fordpass_doorlock
-Fordpass-ignition-switch
-fordpass-tracker

I have tried this on all 3 of my Ford accounts that have access to my 2017 and 2019 vehicles. Fordpass app still works on all 3 accounts.

**Comment by AlteVerwischteZiege** [comment]
Same symptoms as reported in closed issue #238.

**Comment by GeneralLouis** [comment]
@AlteVerwischteZiege thanks, so did you just add logging and restart your HA or the entire machine?

**Comment by AlteVerwischteZiege** [comment]
Yes.

**Comment by itchannel** [comment]
@GeneralLouis can you please enable debug mode for fordpass and send me the contents of your log(sanitize your vin) and I'll have a look.

**Comment by GeneralLouis** [comment]
@itchannel I may have the wrong logs, its just what appears in the full logs under system once you turn on debug mode right? It doesn't have my vin or anything just all the options when configuring it, is there a different place for the debugging logs? 

[home-assistant_2023-01-09T21-49-10.072Z.log](https://github.com/itchannel/fordpass-ha/files/10377279/home-assistant_2023-01-09T21-49-10.072Z.log) (The only thing I did was clear out other unreleated errors or warnings from other integrations and hid my email address, it was already ,1800 (I set this), username, password, vin, region, etc.....)

**Comment by itchannel** [comment]
> @itchannel I may have the wrong logs, its just what appears in the full logs under system once you turn on debug mode right? It doesn't have my vin or anything just all the options when configuring it, is there a different place for the debugging logs? 
> 
> 
> 
> [home-assistant_2023-01-09T21-49-10.072Z.log](https://github.com/itchannel/fordpass-ha/files/10377279/home-assistant_2023-01-09T21-49-10.072Z.log) (The only thing I did was clear out other unreleated errors or warnings from other integrations and hid my email address, it was already ,1800 (I set this), username, password, vin, region, etc.....)
> 
> 

Looks like you're running an old version. You need 1.42 which fixes an options issue in HA 2023.1.

**Comment by GeneralLouis** [comment]
lol I always forget to check for HACS updates, so use to auto-update on the add-ons... sorry about the bother...

**Comment by itchannel** [comment]
> lol I always forget to check for HACS updates, so use to auto-update on the add-ons... sorry about the bother...

No problem I do the same thing👍
