### ISSUE TITLE
Make fordpass_lastrefresh more readable?

### ISSUE THREAD

**Issue by ulanking** [itchannel/fordpass-ha#239]
My fordpass_lastrefresh says it  was at 2023-01-09 18:59:40-06:00. Is there a way to make this more in sync with the HA timezone/time?

Thank you

![fordpass_lastrefresh](https://user-images.githubusercontent.com/177106/211409188-6245e1f3-5db2-40cf-952e-d0edccb7c573.jpg)

**Comment by ronytomen** [comment]
What I have seen the value is UTC with the incorrect timezone.

**Comment by ronytomen** [comment]
This issue can be closed.

**Comment by itchannel** [comment]
Added in latest version
