### ISSUE TITLE
Use elVeh instead of fuel for Conditions

### ISSUE THREAD

**Issue by dewdrinker19** [itchannel/fordpass-ha#240]
I'm trying to setup an automation where if there is less than 50 miles left at 10PM I get a reminder to plug in the car but only fuel value is an option for the condition. Hopefully I'm not being dumb, but I don't see how to use battery range.

**Comment by Bert-R** [comment]
I have that automation running. See #123 for the solution. You can add the plug-in status as a condition, so you only get reminded when you didn't already plug-in your car.

**Comment by dewdrinker19** [comment]
Thank you, even though it is not available as a dropdown option, using the custom YAML to set parameters works great!  I appreciate the help!
