### ISSUE TITLE
Automation to restart integration

### ISSUE THREAD

**Issue by JVTEAM** [itchannel/fordpass-ha#241]
Ever since the great ford lockout I've been having issues with the integration moving to unavailable.  Doing a manual reload fixes it.  Non  HACS integrations can be auto restarted.  Is there any way to create an automation to auto restart the integration after a certain amount of time?

**Comment by boctok** [comment]
I added a button under the entities card for my car (vertical stack) that reloads the integration. You may have to refresh the page.

Requires:
Custom Button Card
The integration "configuration entry id" - found within the core.config_entries file within /config/.storage (Don't edit anything in that file. Just search for "ford" and copy the entry id.

`type: custom:button-card
action: call-service
service: homeassistant.reload_config_entry
data:
  entry_id: <entry_id>
icon: mdi:reload
show_state: true
size: 25px`

**Comment by itchannel** [comment]
Reload integration service has been added in 1.44 which I'm releasing later today to make it easier. Then you can just call the service from any automation.
