### ISSUE TITLE
sensor.fordpass_windowposition = Closed when Open-Partial

### ISSUE THREAD

**Issue by ulanking** [itchannel/fordpass-ha#242]
With the sensor `sensor.fordpass_windowposition`, one window will be "Open-Partial" but the overall sensor reports "Closed". If one window is open-partial, shouldn't the windows be considered either "Open" or "Open-Partial"?

Also is the `rearDriverWindowPos` and `rearPassWindowPos` reporing "Undefined window position" because my vehicle doesn't report it back or the API doesn't?

**Thank for this wonderful integration!**

**Comment by itchannel** [comment]
I'll take a look 👍

**Comment by itchannel** [comment]
Will be fixed in 1.44. 

In answer to your question the API reports "Undefined Window Position" on windows that don't have window position sensors

**Comment by itchannel** [comment]
Should be fixed in 1.44
