### ISSUE TITLE
Error adding Repository

### ISSUE THREAD

**Issue by Prindle19** [itchannel/fordpass-ha#244]
Hi, 

While trying to add this repo to HA I get the following: 

"https://github.com/itchannel/fordpass-ha is not a valid add-on repository"

Is there a different URL than 'https://github.com/itchannel/fordpass-ha' that I should be using?

**Comment by itchannel** [comment]
It's an integration not an add-on. If you have HACS installed you can just search for "fordpass" in the default repos and install no need to add it as a custom repo.

**Comment by Prindle19** [comment]
Ah, sorry, misunderstood. Have it working now!
