### ISSUE TITLE
Detect if remote start worked? 

### ISSUE THREAD

**Issue by rjmcfadd** [itchannel/fordpass-ha#246]
Is there a reliable way to detect if the remote start was successful? I've tried using both remote start status and ignition status but they don't update in time.

Thank you!

**Comment by woempiej** [comment]
You can update manualy and wait 5 minutes ;)
or
Get eyes on the car?

In the README I saw that the update time is 5 minutes anyway so I don't think that can be made much faster because I think the Ford server isn't faster.

**Comment by noman1228** [comment]
Sorry, but this is what I do...


alias: Confirm Remote Start
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.fordpass_remotestartstatus
    to: Active
condition: []
action:
  - service: tts.google_translate_say
    data:
      cache: false
      entity_id: media_player.all_speakers
      message: >-
        Your truck is confirmed Started.  {{
        states('sensor.fordpass_fuel') }} percent fuel remains.
  - service: notify.mobile_app_jmt_s20
    data:
      message: >-
        Remote Start Success. {{ states('sensor.fordpass_fuel') }}% fuel
        remains.
      title: Truck Started
  - service: lock.unlock
    data: {}
    target:
      entity_id: lock.fordpass_doorlock
mode: single

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
