### ISSUE TITLE
Round numbers on fuel

### ISSUE THREAD

**Issue by WantedLange** [itchannel/fordpass-ha#25]
Hi!
Can you make the sensor for fuel round the numbers?
Now it reports 5 digits.

Maybe also add a sensor for mileage left seperate?

**Comment by itchannel** [comment]
Hi @WantedLange, I will add it so it rounds out the fuel number again in the next update. The reason I changed it as I'm not fully convinced that number is Litres and might be more like a percentage value. However until I've acccumulated more data from my car I've left it as is. 

If you want to add in a sensor for mileage/km left then you could add something like below to your config sensor section. I use this on mine for KM remaining

``` - platform: template
  sensors:
    fordpass_fuelremaining:
      friendly_name: "Ford Distance Remaining"
      unit_of_measurement: km
      value_template: "{{ state_attr('sensor.fordpass_fuel', 'distanceToEmpty') }}"

or this for Miles

``` - platform: template
  sensors:
    fordpass_fuelremaining:
      friendly_name: "Ford Distance Remaining"
      unit_of_measurement: mi
      value_template: "{{ (state_attr('sensor.fordpass_fuel', 'distanceToEmpty')|float/1.60934)|round(0) }}"

**Comment by TRusselo** [comment]
lol  its hard to tell the difference between a 95 Liter tank and 100 % full....
my work van is 95 liters (25.1 gallons on spec sheet)

**Comment by petheridge** [comment]
@itchannel Im sure the fuel level shown in home assistant is should be % (mine at least). ![image](https://user-images.githubusercontent.com/30731128/99908374-43633580-2cda-11eb-8047-d4a6db32f491.png)![image](https://user-images.githubusercontent.com/30731128/99908380-4827e980-2cda-11eb-95d8-2747131cb0f3.png) Fiesta has a 45L tank.

**Comment by TRusselo** [comment]
according to google the ford fiesta 2019 has a 12.4 Gallon / 47 liter fuel tank capacity.

**Comment by arjan-s** [comment]
Fuel shows 103.913776 L for me, while the capacity should be 52 L. The tank is full, so it's probably a percentage, but somehow it can still go above 100%.

**Comment by itchannel** [comment]
So I thought it was percentage but don't get how it can be over 100% as it showed 105% on mine when I topped up 🤔

**Comment by itchannel** [comment]
unless the fuel sender unit gives a raw value and can go over 100

**Comment by petheridge** [comment]
@itchannel you are correct, raw fuel level calculated by the PCM from the tank float sensors ranges from -5.217 to 105.979 %. Float sensor range 0x0 to 0x3FF(1023), translated by the PCM (1023 x 0.108696) -5.217408 to % and broadcast over the vehicle CAN network. The precise position of the needle or digital fuel gauge is then calculated by the cluster. This has been the standard in Ford vehicles for some years. 

(I should say I do happen to work for Ford as a powertrain engineer in the UK, but am not involved with FordPass at all 🙂)

**Comment by itchannel** [comment]
@petheridge Awesome, thanks for that info. I'll get and change it to % in the next update.

**Comment by itchannel** [comment]
I've now changed it to percentage. The only thing is with those values it will technically report -5% and + 105% depending on the tank but as it's now converted to a float that shouldn't matter.
