### ISSUE TITLE
Window position wrong

### ISSUE THREAD

**Issue by callerpj** [itchannel/fordpass-ha#251]
Status says open, but all windows are closed:
![Screenshot_20230215-164802](https://user-images.githubusercontent.com/13097676/219078767-8da88425-a4a0-451c-aefd-556dd6b1edf3.png)

**Comment by max-github-mjhodgson-com** [comment]
I am seeing the same.

**Comment by itchannel** [comment]
Fixed in 1.45

**Comment by callerpj** [comment]
Great!

**Comment by itchannel** [comment]
Closing as fixed in 1.45 +
