### ISSUE TITLE
Oil sensor bounces between STATUS_GOOD and STATUS_LOW incorrectly

### ISSUE THREAD

**Issue by mlg9000** [itchannel/fordpass-ha#259]
I have an automation to track the number of miles left between oil changes to that it can add a change oil task to my to do oil and display the status on my dashboard.  It triggers a reset on the oil life sensor being reset in the car.  This changes the oil sensor status from STATUS_LOW to STATUS_GOOD.  In home assistant though this sensor jumps all over the place flipping to status_low with attribute "OilLifeActual 0" and then back to the correct status after awhile, then back again.  The whole time the fordpass app shows the correct oil status and oil life values.

**Comment by itchannel** [comment]
@mlg9000 Could you please enable debug mode on the integration and send me the contents of the vehicle array in your HA logs. (Sanitize your VIN first) so I can see if the data coming back from your car is different. Only thing I can think of is your car shows different data when it's turned off vs when it's on which I've seen before with Fuel levels on certain models.

**Comment by itchannel** [comment]
No debug logs provided so unable to diagnose.
