### ISSUE TITLE
sensor.fordpass_alarm Available as switch.fordpass_alarm?

### ISSUE THREAD

**Issue by ulanking** [itchannel/fordpass-ha#260]
Does the FordPass API allow for a switch.fordpass_alarm? When the value of sensor.fordpass_alarm is 'NOTSET' I have to unlock and re-lock the vehicle to change it to "SET" (or double-click the lock button on my keyfob). If it was available (and the API allows) as switch.fordpass_alarm, it could be set in a simpler manner.

Thank you for the FordPass HA work - it's awesome!

**Comment by itchannel** [comment]
Unfortunately I don't believe its possible to arm the alarm using the Fordpass API or app. The unlock/lock command at least for me only locks the car but I have to physically use the key to lock/unlock the car if I want the alarm to be armed.

**Comment by ulanking** [comment]
> The unlock/lock command at least for me only locks the car but I have to physically use the key to lock/unlock the car if I want the alarm to be armed.

For me, locking with the app also sets the alarm. SO I have an automation that, if the truck is locked but alarm is not set, it unlocks the truck, waits and relocks.  Thought it would be cool to just set the alarm instead.

OK - thank you. I'll mark this as closed
