### ISSUE TITLE
Window Status - Undefined

### ISSUE THREAD

**Issue by magnetic157** [itchannel/fordpass-ha#262]
Hello, 

Two of my windows recently have been showing as "undefined" - does anyone know if this is a bug or something within my configuration causing this?  I'm running the most recent version 1.46

<img width="487" alt="image" src="https://user-images.githubusercontent.com/78054864/226726234-495697ed-ca66-4a09-8113-231b17ad2227.png">

**Comment by itchannel** [comment]
Closing as there's been no response in months. Happy to re-open if still experiencing issues.
