### ISSUE TITLE
timestamp issues

### ISSUE THREAD

**Issue by michalk-k** [itchannel/fordpass-ha#263]
I would like to report a few timestamp issues. I could report it separately but those share common problems. Changes I suggest will make reported values compliant with current HA standards.

1. sensor.fordpass_lastrefresh
    - should be set to: `device_class: timestamp`
    - the value passed to this sensor should be ISO formatted (add `T` literal between date and time, for example: `2023-04-15 13:04:33+02:00`)

2. wrong format of timestamp attributes
`timestamp` attributes found in entities are in the wrong format. It's American format with the date formatted as `month-day-year`.
To allow further processing the expected format is `year-month-day`. 
Please note, using the American format may lead to interpretation errors in other countries, for example, what date is 03-04-2023? is it 3rd April or 4th Match?
See the image below, the time of the last refresh is obviously correct (otherwise, but the timestamp attribute for ignition status has exchanged day and month values.
Also, I suggest making all timestamps ISO compliant (with `T` literal between date and time)
I believe the value itself represents GMT time. So the time from the image should look like 2023-04-15T11:04:44+00:00 (unless HA itself converts it to the local time zone which I don't believe it does)
![image](https://user-images.githubusercontent.com/7868445/232250238-71b03c32-a028-4733-b3ee-1fb753ff049b.png)
3. weird data for `fordpass_dieselSystemStatus`
    - I'm sure it's not the proper format for json. Then what it should be?
    - timestamp issue, the same as described in point 2.
![image](https://user-images.githubusercontent.com/7868445/232250264-ff74c7a8-169e-48db-bce5-6dcc55cdb8ff.png)

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
