### ISSUE TITLE
Remote start 

### ISSUE THREAD

**Issue by michalk-k** [itchannel/fordpass-ha#264]
Not sure bug or FR.
The project main page sais remote start is supported. On the other hand then only entity I can see is `fordpass_remoteStartStatus` which obviously gives no ability to start the car.

Could we get the feature of starting a car remotely?

**Comment by itchannel** [comment]
@michalk-k As long as your car supports it you should have a switch entity added in HA called fordpass_ignition_switch, by toggling this it will start the car the same as using remote start in the Fordpass App.

**Comment by michalk-k** [comment]
Ahh. 
I was misled by the ignition name. AFAIK it doesn't mean starting the engine. While speaking about ignition switches in a car, it may have several positions, with one of them called the ignition. But it doesn't crank the motor up. It turns on electric circuits. yeah.. The  (momentary) position starting the car is usually named "start". It might differ from company to company, but here is the link from some Ford manual:

https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?variantid=7785&languageCode=en&countryCode=USA&Uid=G1918297&ProcUid=G1518436&userMarket=usa&div=f&vFilteringEnabled=False&buildtype=web

And similar one for car equiped wih Ford Power button 
https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?variantid=8545&languageCode=en&countryCode=USA&Uid=G2183162&ProcUid=G2175466&userMarket=USA&div=f&vFilteringEnabled=False&buildtype=web

Anyway, thanx for clarifying.

**Comment by itchannel** [comment]
Closing issue as user found the switch. 

The switch is called ignition as this is how it is referred to in the Fordpass API

```
        "ignitionStatus": {
            "value": "Off",
            "status": "CURRENT",
            "timestamp": "07-10-2023 04:06:29"
        },
```
