### ISSUE TITLE
Old datas and no remote actions

### ISSUE THREAD

**Issue by BenDavidson90** [itchannel/fordpass-ha#266]
Hi,

I installed the FordPass integration this morning, it fetched datas from my vehicle but since nothing works.
Data are not updated, remote ignition and remote doors lock doesn't work.
fordpass_lastRefresh is 2023-06-20 20:49:35+02:00 (so before I installed this integration).
Fordpass app works fine (used today to remote ignition and watch my fuel tank percentage).

Here are the logs:
`
Platform fordpass does not generate unique IDs. ID WF###############-fordpass_deepSleepInProgress already exists - ignoring sensor.fordpass_deepsleepinprogress

Platform fordpass does not generate unique IDs. ID WF###############-fordpass_tracker already exists - ignoring device_tracker.fordpass_tracker

Platform fordpass does not generate unique IDs. ID WF###############-fordpass_ignition already exists - ignoring switch.fordpass_ignition_switch

Platform fordpass does not generate unique IDs. ID WF###############-fordpass_doorlock already exists - ignoring lock.fordpass_doorlock

Unable to find referenced entities switch.fordpass_ignition_switch or it is/they are currently not available

Debouncer call ignored as shutdown has been requested.
`

**Comment by w0d4** [comment]
Hi,
I have exactly the same problem. I cannot refresh any values. Even calling fordpass.refresh_status does lead to exactly this error messages in the log and nothing gets refreshed.
Also removing and adding my car again does not help.

**Comment by helgek** [comment]
Many entities were retrieved with values not updating since the initial retrieval of data from FordPass Api. No response from car for any actions executed through this Home Assistant integration.

**Comment by Rulles06** [comment]
Hello.
I'm getting the same errors and none sensor changing status for hours. Even if I call refresh_status.

Looking for the error, it appear they cannot update because the sender are already created. Maybe some error on code?!

**Comment by domolys** [comment]
Same problem... tried reinstalling, restarting, removing and start over, don't know if it's a problem with my account

**Comment by helgek** [comment]
In the meantime the situation has significantly improved for me. All actions sent to the car through the integration work and entities also seem to update properly. I have to point out though that I haven't tested on a regular basis yet so I can't tell if all this works reliably always. But I'd really like to thank the developers for this great initiative and development! With this integration interesting things are possible like locking the car based on triggers which wouldn't be possible with Fordpass itself.

**Comment by itchannel** [comment]
Closing as old issue. Please re-open a new one if issue still exists.
