### ISSUE TITLE
fordpass_gps  should be device_tracker not sensor.

### ISSUE THREAD

**Issue by TRusselo** [itchannel/fordpass-ha#27]
Im still learning myself, but i think

Fordpass_gps should be a device_tracker not sensor.
this will allow it to be set as a "tracking device" for "people",  and the status should show as a location, rather than "unshifted"....  ( I assume)

EDIT
dont change. ADD. no reason cant have both.

**Comment by TRusselo** [comment]
you might also get an actual location address with geocoded_location attribute on the sensor device type.
but please look into adding device_tracker device type for presence detection (home/away status)

**Comment by itchannel** [comment]
I'll have a look into adding a device_tracker but the docs aren't the best in the world so may take a little time to get my head around it. 

For now it should show on the MAP and work like a tracker, the only difference is the "SHIFTED" / "UNSHIFTED" which is an attribute pulled from the FORD API which I agree can look a little weird so would be nice to have home/not_home

**Comment by TRusselo** [comment]
Home/Away status is only available with a Device Tracker that has been added to a person.
you can only link a device tracker to a person, not sensors.

But yes i have the sensor showing in a map card.... when its not "UNAVAILABLE" from the other issue.

**Comment by itchannel** [comment]
Added in latest version
