### ISSUE TITLE
Status updates

### ISSUE THREAD

**Issue by systema365** [itchannel/fordpass-ha#271]
I love this integration.  Great work!

One thing I would recommend is due to the delay in sending the request through the Fordpass api .  This can sometimes take a significant amount of time, so it would be good if the entity status changes "locking", or "starting", or "stopping" during the time period it's performing the action.  I would also be great if it can disable the entity during this time - so you don't start spamming the Ignition or door lock buttons in the dashboard (cough cough.. my wife).  :)

**Comment by itchannel** [comment]
This isn't a bad idea, I will look and see the best way to support this without excess polling the API whilst locking/unlocking. Given HA now services to respond with data I could have it send back data to show its "locking" or "Starting" depending on the API response.

**Comment by itchannel** [comment]
Support for door locking/unlocking status added in 1.47. However there is no way to set the intermittent state of a switch when starting the ignition it only supports on/off. The api will stop you from spanning the on/off key by not accepting multiple pushes if a task is in progress.
