### ISSUE TITLE
After upgrade to v1.47Release sensor.fordpass_odometer is showing as Unavailable

### ISSUE THREAD

**Issue by rtw819** [itchannel/fordpass-ha#273]
This was a weird one...

Multi-vehicle U.S. user here, both vehicles odometer readings seem to be missing after the upgrade via HACS and after a HA restart.  The Odometer value(s) previously showed the actual/correct odometer readings prior to 1.47.  The good news is everything else seems to be displayed as before, so only the odometer readings appeared to be affected.  Given this is not a desired scenario, it is worth noting there may be an easy way to get it back.  Please read further, YMMV.

- fordpass_odometer
> This entity is no longer being provided by the fordpass integration. If the entity is no longer in use, delete it in settings.

Apparent solution:

Navigate to Settings -> Devices & Services -> Fordpass -> (Pick a vehicle if you have multiple) -> Click CONFIGURE -> On the Fordpass "Options" dialog box Click SUBMIT.  (Not necessary to make changes unless you need something changed.  Had to do this for both vehicles.)

Upon a refresh, the odometer mileage sensor(s) should correctly display vehicle mileage once again.

Hope this is helpful.

**Comment by itchannel** [comment]
Fixed in 1.48
