### ISSUE TITLE
Odometer is unavailable

### ISSUE THREAD

**Issue by bryangalaz** [itchannel/fordpass-ha#275]
For the last 2 days, odometer has been coming back as Unavailable.

**Comment by itchannel** [comment]
> For the last 2 days, odometer has been coming back as Unavailable.

There is a bug in the current version. For now the workaround is to go to the Integration options, don't change anything and just click submit. It will then add the missing config option which is currently causing the bug.

**Comment by itchannel** [comment]
Fixed in 1.48
