### ISSUE TITLE
Locking/Locked vs Locked/Unlocked after 1.47

### ISSUE THREAD

**Issue by ulanking** [itchannel/fordpass-ha#276]
Prior to updating to 1.47, the entity `lock.fordpass_doorlock` had two states: Locked and Unlocked

After updating to 1.47 `lock.fordpass_doorlock` has so far only shown 2 states: Locking and Locked (both with a clock icon blinking in the middle). What is the cause of "Locking" and is there an action to get it to be "Locked"? When the door IS locked, it still shows the state of "Locking"

![20230726_fordpass_locking](https://github.com/itchannel/fordpass-ha/assets/177106/e21028e3-edda-450b-8455-122866749dbb)

Thank you

**Comment by itchannel** [comment]
In 1.47 it *should* only set the status as "locking" and "unlocking" when a request to lock/unlock the car has been sent and it's waiting for a response from the car. 

I'll try and see if I can replicate this issue your experiencing on my end.

**Comment by ulanking** [comment]
I also was missing the odometer. When followed the directions to the fix, it also changed the state of my truck from "Locking" to "Locked" and now displays the proper status when it is locked or unlocked.
