### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by thisisbenwoo** [itchannel/fordpass-ha#28]
Hi @itchannel, sorry for the roundabout way of reaching out. I couldn't find anywhere how I could just drop you a quick note. I'm REALLY excited about this integration, and wanted to offer myself to help with testing, or documentation. I am an enterprise IT marketing strategist by trade, but a geek by night. My programming capabilities are minimal, but anything else I can do to support. I always knew this integration was possible, and I'm so excited to be able to tell HA that I'm about to go out, and (in the future), have it warm the car, etc. so that when I get in, I can just go!

Thanks for creating this. Please just tell me what I can do!

**Comment by itchannel** [comment]
Hi Ben, 

Glad your enjoying it. It's very much a side project as like you I wanted to be able to control my car and get updates like my fuel level before I leave the house. If you can keep an eye out for any bugs you might experience and let me know that would be great. If your up for it I will need some beta testing once I've finished the latest update adding/fixing some of the reported features.

**Comment by thisisbenwoo** [comment]
Count me in! I have a 2018 Ford Explorer Sport, and a 2018 Ford Fusion Titanium Hybrid. I just bought a nonda ODB-II dongle as well, don't know if that helps too.

**Comment by itchannel** [comment]
Closing this thread, Any support needed please comment on the relevant tickets 👍
