### ISSUE TITLE
Feature Request: Add EV features

### ISSUE THREAD

**Issue by AlohaFlyer** [itchannel/fordpass-ha#281]
I would love to see us add the following for Ford EV's

1. Charging Status
2. Plug Status
3. Ability to change charge times
4. Ability to change climate settings for time of day
5. Ability to start charging via HA
6. Ability to stop charging via HA
7. Sensor that tracks kWh of Energy used per charge session
8. Ability to roll up windows via HA

**Comment by itchannel** [comment]
The following can be found under the elVeh sensor
1. Charging Status
2. Plug Status

The rest I would need to work with someone who has an electric car and knows or is willing to debug python as I don't currently have a way to check/interact with charging abilities.

**Comment by AlohaFlyer** [comment]
Thank you for your reply. I did find these in the attributes of sensor.fordpass_elveh. 

Although there are issues:
1. Charging Status:  (Displays accurately)
2. Plug Status:  (Does not change status, stays at 0 whether plugged in or not plugged in)

I would love to work together to improve this. I have a background in software QA, not really debugging python, but I do have a 2023 Ford Mustang Mach-e as well as Tesla Powerwalls and Tesla Wall Connectors for charging.

**Comment by AlohaFlyer** [comment]
![Mach-e HA](https://github.com/itchannel/fordpass-ha/assets/23268691/8a13835c-9224-458c-a34f-198545762355)

Here is the dashboard that I made using these values from the integration so far.

**Comment by AlohaFlyer** [comment]
![mache_charged](https://github.com/itchannel/fordpass-ha/assets/23268691/e9800e52-6a36-4609-9506-0c7fd558cdd8)

Here is how it shows after charging is complete, still plugged in.

**Comment by AlohaFlyer** [comment]
I really want to be able to:

**Start / Stop Charging Sessions with Fordpass.**

**Comment by itchannel** [comment]
Happy to work with someone who has the features in their fordpass application. It would involve using a proxy like Burp and seeing what requests are being made to the ford API for setting the charging session etc. I believe from past notes from people it contacts a 3rd party website if using the ford charger but don't quote me on it.

**Comment by AlohaFlyer** [comment]
I am happy to help and have a background in software testing. I do not have strong python skills yet. 

Equipment I have:
2023 Mustang Mach E
Tesla Wall Connector
Home Assistant with this Fordpass Integration

I am happy to setup Burp etc. to give you the data / logs you need to help with this.

**Comment by itchannel** [comment]
@AlohaFlyer If you could setup burp on your pc, install the CA cert from burp on your relevant mobile device then send me the requests sent between the fordpass app and the API when using the Wall connector etc. That would be really helpful. 

Instructions below for setting up the proxy. 

https://portswigger.net/burp/documentation/desktop/mobile

**Comment by AlohaFlyer** [comment]
> @AlohaFlyer If you could setup burp on your pc, install the CA cert from burp on your relevant mobile device then send me the requests sent between the fordpass app and the API when using the Wall connector etc. That would be really helpful.
> 
> Instructions below for setting up the proxy.
> 
> https://portswigger.net/burp/documentation/desktop/mobile

ok let me get this set up.

**Comment by SquidBytes** [comment]
Number 7 "Sensor that tracks kWh of Energy used per charge session"
Can probably be found related to Issue #294 I opened with data from charge logs

**Comment by SquidBytes** [comment]
Ended up finding a different API for charge stats.
I believe I have integrated that in my updated pull request

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
