### ISSUE TITLE
Documentation: Setting Up Second Account

### ISSUE THREAD

**Issue by askpatrickw** [itchannel/fordpass-ha#283]
I've read that some people are setting up an additional login to their fordpass account, and then using that account with the HA integration so if the account gets locked they can still use their main account. 

It would be great if the README could explain that in some detail. Does this require a second mobile device, can you do it all on the web? Etc. Etc.

I'll give it a go myself, but if others can chime in that would also be appreciated.

**Comment by askpatrickw** [comment]
According to this community answer it sounds like you can do it from the mobile app.

https://fpcommunity.ford.com/t5/Help/Can-there-be-multiple-FordPass-users-for-a-vehicle/ta-p/61

I just need to confirm if you can logout and do it from the same device or not.

**Comment by SquidBytes** [comment]
https://github.com/itchannel/fordpass-ha/wiki
