### ISSUE TITLE
Tyre pressure bug?

### ISSUE THREAD

**Issue by frankie-boy-hgv** [itchannel/fordpass-ha#285]
Hi,

I've installed version 1.50 and since then I've a lot of air in my tires (set to bar).

Regards,

Frank
![Screenshot_20230909_124536_Home Assistant](https://github.com/itchannel/fordpass-ha/assets/70746913/06f3ee6c-8f0d-4492-b371-9db722ac802c)

**Comment by WhiteDogBe** [comment]
Looks fine to me on my car 😅
![IMG_0321](https://github.com/itchannel/fordpass-ha/assets/10188807/729d75a3-0f6e-4003-baaa-b08918f8c9e0)

**Comment by itchannel** [comment]
Under options there is an option "Disable distance conversion" can you tick or untick that and let me know if that fixes it.

**Comment by jmyerssvt** [comment]
I have this same issue. Disabling distance conversion did not fix it.

**Comment by mrgrlscz** [comment]
Same thing here.

**Comment by itchannel** [comment]
If you change it to the opposite unit setting e.g. if set to PSI set it to Bar does it show correctly.

**Comment by mrgrlscz** [comment]
It doesn't. Values are exactly the same.
It seems to me that units in HA are stucked at kPa.
In the official fordpass app, values are OK in bars, or kPa, or PSI.

**Comment by imdeepjee** [comment]
Same issue here.

Tried tick/untick 'disable distance conversion' with psi, bar, kpa units and restarting HA every single time but nothing changes.

**Comment by itchannel** [comment]
Should be fixed in 1.51 👍

**Comment by itchannel** [comment]
@imdeepjee @mrgrlscz Can you please confirm the tyre pressure is now displaying correctly in 1.51/1.52?

**Comment by imdeepjee** [comment]
Issue solved for me!

Thanks!

**Comment by mrgrlscz** [comment]
This is OK (1.52)! Thank you!
