### ISSUE TITLE
Configuration Flow Error

### ISSUE THREAD

**Issue by Madecaredda** [itchannel/fordpass-ha#286]
Hi

I managed to find an error where if you have not defined a nickname for your car, the configuration stops after the username/password screen. 
I confirmed via Logs and also by putting the nickname for the first time in the app, and after this the integration loaded without problems

here a copy-paste of the notice on the log of HA: 

Traceback (most recent call last):
  File "/config/custom_components/fordpass/config_flow.py", line 86, in async_step_user
    return await self.async_step_vehicle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/config_flow.py", line 119, in async_step_vehicle
    avaliable_vehicles[vehicle["VIN"]] = vehicle["nickName"] + f" ({vehicle['VIN']})"
                                         ~~~~~~~^^^^^^^^^^^^
KeyError: 'nickName'


regards

**Comment by itchannel** [comment]
Thanks for the bug report, I'll get it fixed in the next version 👍

**Comment by itchannel** [comment]
Fixed in 1.51
