### ISSUE TITLE
Region Not available 

### ISSUE THREAD

**Issue by gerhardking** [itchannel/fordpass-ha#287]
No region available for South Africa. also South Africa FordPass uses mobile number as username and not e-mail address

**Comment by itchannel** [comment]
@gerhardking Can you do me a favour and try using your mobile number in the email field (Might need to remove the first 0 of your number) and then choose Europe or USA as the region and tell me if it works.

**Comment by adriaan144** [comment]
mobile number in the Username(Email) field doesn't work for me. No matter what region is selected. Maybe some changes are needed that relates to the new app that was released?

**Comment by itchannel** [comment]
Did you try your mobile number excluding the first 0?

Also can you login ok to the below URL:

https://www.ford.co.za/support/vehicle-dashboard

**Comment by adriaan144** [comment]
Thanks for the reply, I can log into the link you supplied, using the mobile number with the preceding zero.
On the HA integration not using a preceding zero gives "unexpected error" when I try with a 0 in front it says "invalid credentials"
On the standard fordpass app on my mobile the account username is shown as the mobile number excluding the preceding zero.

I've uninstalled the integration and removed the custom components fordpass folder and reinstalled but still the same

**Comment by itchannel** [comment]
Unexpected error is definitely a step in the right direction it at least means authentication is working. Do you have anything else in your logs and is debugging enabled in your configuration for fordpass. Sounds like it's logging in but not receiving the response it expects so need to work out what it's actually seeing.

**Comment by adriaan144** [comment]
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fordpass/config_flow.py", line 83, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/config_flow.py", line 62, in validate_input
    vehicles = await(hass.async_add_executor_job(vehicle.vehicles))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 370, in vehicles
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.mps.ford.com/api/expdashboard/v1/details/

**Comment by itchannel** [comment]
Can you please try version 1.48 or lower. The error seems to be around retrieving the list of vehicles.

< 1.48 doesn't use a vehicle list so if that works for you then we can narrow down the issue.

**Comment by adriaan144** [comment]
Thanks. Uninstalled using hacs. Then reinstalled version 1.48. Installed via HA and all worked fine. Also using mobile number excluding zero.

**Comment by gerhardking** [comment]
Thanks a mil !!! downgraded and used cell without the 0 and it works like a dream.

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
