### ISSUE TITLE
Updates from HACS are erasing the fordpass_token.txt file and the integration fails

### ISSUE THREAD

**Issue by cpw** [itchannel/fordpass-ha#288]
Whenever I update this integration via HACS, the integration goes offline after restarting. It seems that the `fordpass_token.txt` file that is dropped into `custom_components/fordpass/` directory is erased by the HACS update. This is probably a bug, because I suspect that's not what you want to happen. I have to restore the file from backup and restart HA to get the integration working again.

I'll also note that there seems to be no way in the config flow to reauthenticate and adding a new integration means I have to rebuild all my automations and dashboards, which is a lot of effort.

I think you should look at a different way of storing the secure token, that doesn't involve dropping it in your custom_components directory since that's probably NOT where it should go.

**Comment by itchannel** [comment]
The "fordpass_token.txt" file is only used for caching the token, the actual credentials used are stored in the HA config. Therefore an update shouldn't affect the operation of the integration. This is the first time anyone has reported this bug so must be unique to your installation. Can you enable debugging and send me the error logs next time this occurs. 

In reference to reauthentication, as I mentioned the application stores the credentials in the HA config dictionary so automatically reauthenticates if required. It should also on uninstall delete and tidy up the created entities so a reinstall/ adding again will result in it using the same entity names, thus not affecting any created automations or dashboards.

**Comment by cpw** [comment]
What logging would you like. There was very little in the log files (even at debug level), just failures to connect because of authentication failures. The file didn't come back again on its own, I restored a backup copy and things started working. I'm running a venv type environment, perhaps that's related?

Additionally I couldn't find any trace of the authentication in the HA config. I may have missed it, but I did look to see if I could find it when this first occurred. Perhaps there was a failed migration or something? The install is 14 months old now.

**Comment by itchannel** [comment]
If debug logging was enabled I would of expected to see the response json/text from most calls in your logs. As it sounds like it could be related to your specific setup. 

Might be worth trying to enable debug logging in the configuration.yaml in case the debug button isn't working as intended. 

Is it working for you now?

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

**Comment by SquidBytes** [comment]
Is this still an issue for you?
