### ISSUE TITLE
403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v4

### ISSUE THREAD

**Issue by JVTEAM** [itchannel/fordpass-ha#289]
At about 8pm last night my fordpass instance suddenly went unavailable.  Looked at the log and saw

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:68
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: 5:02:51 AM (116 occurrences)
Last logged: 5:38:01 AM

403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v4/VIN#/status?lrdt=01-01-1970+00%3A00%3A00
Error communicating with FordPass for VIN#
403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v4/VIN#/status?lrdt=01-01-1970+00%3A00%3A00
Error communicating with FordPass for VIN#

I still have access to my account on the app so it doesn't appear banned.

**Comment by max-github-mjhodgson-com** [comment]
I have the same error on mine starting around 13 hours ago.

**Comment by hendrikderek** [comment]
having the same problem here since 8 hours

**Comment by itchannel** [comment]
What version of the integration are you running and has there been any updates for your car?

I've noticed one bug where if a request fails it retries using the old v4 URL not v5. Maybe one of you could try updating the v4 url in fordpass_new.py to v5 please.

**Comment by hendrikderek** [comment]
the latest.. well if you could explain how to do that, i'd love to try it :D

i guess via the file editor, but where is is located? sry for noob questions

**Comment by itchannel** [comment]
@hendrikderek Can you give 1.51 a go. I've fixed the URL pointing to the old one. But might not fix your bug specifically.

**Comment by max-github-mjhodgson-com** [comment]
I just updated and it is now working for me.

Many thanks for your lightning quick bugfix!

**Comment by itchannel** [comment]
Just released 1.52 to address that issue. Looks like they discontinued a few API endpoints so have now moved them to the latest app version.

**Comment by hendrikderek** [comment]
worked for me as well now. Thank you!

**Comment by JVTEAM** [comment]
> What version of the integration are you running and has there been any updates for your car?
> 
> I've noticed one bug where if a request fails it retries using the old v4 URL not v5. Maybe one of you could try updating the v4 url in fordpass_new.py to v5 please.

My HACS instance is broken so I can update, but I manually updated in that script and now it works.  Thanks!

**Comment by itchannel** [comment]
Fixed in #291
