### ISSUE TITLE
After Priority Update 23-PU0724-DOM-RS,  FordPass No Longer Works

### ISSUE THREAD

**Issue by gniknalu** [itchannel/fordpass-ha#290]
After my vehicle received "Priority Update 23-PU0724-DOM-RS" yesterday (2023.09.14), FordPass stopped functioning. No errors were found when I turned on debug logging.

**Comment by itchannel** [comment]
Can you please give me the following info:

- Version of integration
- Model of vehicle and model year
- Any errors or info in the log. (Should be some, maybe try manually looking as filtering by "fordpass" doesn't always work.

**Comment by gniknalu** [comment]
Version of integration --> Version 1.50
Model of vehicle and model year --> Ford F-150, 2022
Any errors or info in the log. (Should be some, maybe try manually looking as filtering by "fordpass" doesn't always work. --> I turned on "debug logging" and then went to the extended logs and captured everything after trying to lock or unlock the doors.  I formatted the JSON but didn't see any errors logged. (I did learn that WOW there are a lot of messages that waste a lot of space!)

**Comment by pdecker414** [comment]
I also have this issue. No errors logged but the status refuses to lock and shows one door open. I can remotely lock the car and can verify it's locked but the plugin still displays unlocked and door open. It's it possible to roll back a version?

**Comment by itchannel** [comment]
Is it just the lock status not updating for you both or is none of the integration working since you updated your car?

If it's just the lock then might be worth running the service "refresh_status" to manually poll the car after you've locked it and then see if it updates on next refresh? I've always found it hit and miss if my vehicle actually reports its lock status without manually polling the car.

**Comment by WhiteDogBe** [comment]
refresh_status is no longer working for me and gives an error.

File "/config/custom_components/fordpass/__init__.py", line 88, in async_refresh_status_service
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/__init__.py", line 159, in refresh_status
    status = coordinator.vehicle.request_update(vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 457, in request_update
    return status.json()["status"]
           ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'status'

**Comment by itchannel** [comment]
It appears Ford has retired a number of API endpoints. Should have an update in the next 30mins.

**Comment by itchannel** [comment]
@WhiteDogBe Please try version 1.52 just released.

**Comment by WhiteDogBe** [comment]
> @WhiteDogBe Please try version 1.52 just released.

Everything working again with 1.52. Thanks for the reactivity and enjoy your weekend 🎉

**Comment by gniknalu** [comment]
Works Great! Thank you for this wonderful integration!

**Comment by pdecker414** [comment]
I updated to the most current version 1.52 and now it is working again.
