### ISSUE TITLE
403 Forbidden.

### ISSUE THREAD

**Issue by BenDavidson90** [itchannel/fordpass-ha#293]
Hi,

My FordPass plugin does not work anymore (failed to configure).

When I look at the log, here is what I found:
`403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v4/#VIN#/status?lrdt=01-01-1970+00%3A00%3A00`.
By going to this link, here is the response from the API:
`{ "statusCode": 401, "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API." }`
Although I think this last error is irrelevant because you should already include the subscription key in your headers calls, thing that I don't, so the main error is surely the 403.

**Comment by BenDavidson90** [comment]
> Are you on the latest 1.52 release? I had to update to fix the same issue.

Dumb question but... how do you update it ? Unlike add-ons, I don't have any update notification.

**Comment by ncsu1** [comment]
This is done from the HACS tab on the sidebar instead of the settings. You should see the update notification there.

**Comment by BenDavidson90** [comment]
> This is done from the HACS tab on the sidebar instead of the settings. You should see the update notification there.

Thanks! It works now, like you said.

**Comment by mikedhanson** [comment]
Glad I saw this. Was kind of stumped.
