### ISSUE TITLE
Added the vehicle through the integration but actions dont work 

### ISSUE THREAD

**Issue by doronazl** [itchannel/fordpass-ha#295]
Seeing all the sensors fine but actions like engine start and lock unlock dont respond and status always showing as unlocked

**Comment by doronazl** [comment]
Tried deleting the device and readding, noe cant even log in anymore, says wrong credentials.

Still work fine from my fordpass app and can log out and login.
Its not a ban.


Also i should mentioned i was trying to login for weeks and it didn't work saying wrong credentials, just today it suddenly worked, and now wont again.

**Comment by itchannel** [comment]
Can you enable debug logging and check your logs for error's. 

Also can you provide the following info:
- Model and year of vehicle
- Version of HA and integration version
- Copy of any fordpass related errors in the logs


Enable Debug Logging:

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

**Comment by doronazl** [comment]
Finally got it to work.
Deleted the integration, installed again, had to reset home assistant and login, then it started working properly.
