### ISSUE TITLE
Unable to complete setup

### ISSUE THREAD

**Issue by jackshaw20** [itchannel/fordpass-ha#296]
Hi,

i am trying to get this integration working, both vehicles were added successfully but no entities have downloaded and it says error against each vehicle when trying to initialise. 

This is the error in the logs

![image](https://github.com/itchannel/fordpass-ha/assets/61296690/9cd89ee9-c2fb-4055-92ce-c05b66723dd0)

**Comment by jackshaw20** [comment]
This is what it looks like on the devices 
![image](https://github.com/itchannel/fordpass-ha/assets/61296690/e1218bd1-d00c-4b8d-8758-577aab6f249d)

**Comment by jackshaw20** [comment]
Connection to fordpass must be ok as it downloaded the VIN numbers itself ?

**Comment by itchannel** [comment]
Can you add the following to your configuration file then try adding the integration again. The debug button doesn't always capture all the logs so adding it to your config will let you see any debug errors when it's added. 

You should see Fordpass messages which will show exactly what error is occuring. 

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

**Comment by jackshaw20** [comment]
Please see attached log where it errors;

![Uploading IMG_2937.jpeg…]()

**Comment by RyanEwen** [comment]
I appear to be having the same issue. I can add my vehicle but it never creates devices/entities

![image](https://github.com/itchannel/fordpass-ha/assets/1136808/951bc95e-46e0-46a2-9bc0-aa1e6286e3e8)

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please open a new issue if you are still having problems
