### ISSUE TITLE
Feature Request: Allow uploading a picture of the car to Home Assistant

### ISSUE THREAD

**Issue by pculebras** [itchannel/fordpass-ha#298]
Good day,

I just set up a Map Card on my dashboard, which uses the car’s GPS position to display where it’s parked. I think it would be great if we could upload a picture of the car for display, instead of letting HA use the first letter of the entity’s name, which is just an ugly ```f```.

Would such a thing be possible?

Thanks beforehand!

**Comment by itchannel** [comment]
I don't believe the HA entity that's used supports Photos. https://developers.home-assistant.io/docs/core/entity/device-tracker

My recommendation would be to change the device_tracker name to something more relevant like below:

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/4dc4e3db-293c-498d-938a-74d14cef8d56)

**Comment by SquidBytes** [comment]
You can create a user, and assign the `fordpass_tracker` entity to that user and give them a profile picture.
![image](https://github.com/itchannel/fordpass-ha/assets/145411069/478d1ee3-f897-4a87-b5f7-f6762ccc6a4b)
![image](https://github.com/itchannel/fordpass-ha/assets/145411069/d8513519-2df1-4219-926d-fd9396a07e2b)

**Comment by itchannel** [comment]
^ Good idea. 

Closing issue as not possible in the integration but can be done in HA as shown be @SquidBytes
