### ISSUE TITLE
add lock device entity for door locks

### ISSUE THREAD

**Issue by TRusselo** [itchannel/fordpass-ha#30]
if possible add lock device entity for door locks
lock.VEHICLE_door_lock

**Comment by itchannel** [comment]
So there is already a door lock entity but I might change the name as it's currently "lock.lock" and would be better as "fordpass_doorlock"

**Comment by TRusselo** [comment]
yup.. there it is... and it got missed because it didnt contain the word "ford".
Thanks.

**Comment by itchannel** [comment]
Closing the issue, door lock entity exists and latest version has it renamed to "fordpass_doorlock"
