### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by maxandersen** [itchannel/fordpass-ha#301]
not exactly sure when it stopped working but I have 749 entries of:

```
Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:262
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: September 29, 2023 at 4:35:56 PM (749 occurrences)
Last logged: 9:03:58 AM
Error fetching fordpass data: Error communicating with FordPass for WFXXXXXXXXXX
```

underlying error seem to be this:

```
403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v4/WFXXXXXXX/status?lrdt=01-01-1970+00%3A00%3A00
Error communicating with FordPass for WFXXXXXXXX
```

I've checked username/password and they work in app and on ford website itself. just fails in homeassistant.

**Comment by itchannel** [comment]
> not exactly sure when it stopped working but I have 749 entries of:
> 
> 
> 
> ```
> 
> Logger: custom_components.fordpass
> 
> Source: helpers/update_coordinator.py:262
> 
> Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
> 
> First occurred: September 29, 2023 at 4:35:56 PM (749 occurrences)
> 
> Last logged: 9:03:58 AM
> 
> Error fetching fordpass data: Error communicating with FordPass for WFXXXXXXXXXX
> 
> ```
> 
> 
> 
> underlying error seem to be this:
> 
> 
> 
> ```
> 
> 403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v4/WFXXXXXXX/status?lrdt=01-01-1970+00%3A00%3A00
> 
> Error communicating with FordPass for WFXXXXXXXX
> 
> ```
> 
> 
> 
> I've checked username/password and they work in app and on ford website itself. just fails in homeassistant.

Please upgrade to the latest version as the api endpoints have changed.

**Comment by maxandersen** [comment]
> Please upgrade to the latest version as the api endpoints have changed.

you are right. I thought I already done that but apparently missed a full restart. Works now! sorry for the noise.
