### ISSUE TITLE
Failed setup, will retry

### ISSUE THREAD

**Issue by anatwick** [itchannel/fordpass-ha#304]
Have had ford pass installed on HA for the last couple of years and its worked flawlessly until today.  On the integrations its stating Failed setup, will retry.  I attempted to uninstall from HACS, reboot, reinstall, reboot with the same result.  when i sign in to the fordpass integration it shows the vehicle just fine but the integration shows Failed setup, will retry.  The vehicle shows up but there are no devices or entities.

**Comment by stumiles86** [comment]
Yep same here. Working fine till last night.

**Comment by virtualbitzz** [comment]
Pretty sure this is broken for everyone. See https://github.com/itchannel/fordpass-ha/issues/303

**Comment by mrgrlscz** [comment]
Same here, be patient!

**Comment by doronazl** [comment]
Same here, just died

**Comment by Lanstrom** [comment]
I guess all cars worldwide use the same servers but just for reference it's not working in the UK either.

**Comment by Afterdark1st** [comment]
Mine is no longer working either UK user

**Comment by itchannel** [comment]
Please see #303 Theres been significant API changes on Fords end moving to a new system so it has broken all unofficial integrations like this one. I am working on it but I'm one person so bare with.

**Comment by Afterdark1st** [comment]
> Please see #303 There's been significant API changes on Fords end moving to a new system so it has broken all unofficial integrations like this one. I am working on it but I'm one person so bare with.

sorry i missed the #303 comment, thanks for all your hard work on this integration.

**Comment by dmkjr** [comment]
> Please see #303 There's been significant API changes on Fords end moving to a new system so it has broken all unofficial integrations like this one. I am working on it but I'm one person so bare with.

How do you want us to go about getting you our vehicle data for the export?

**Comment by itchannel** [comment]
1.53 is now live which addresses this issue.

**Comment by ins4neuk** [comment]
Updated mine and seems good to go
