### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by Lux315** [itchannel/fordpass-ha#305]
Thanks for your work at fordpass, i really like it.

Id like to help testing with the beta since the api change.

Is there a way to get the beta?

**Comment by bleeblak8** [comment]
If you got to the Tags part on the main page, you'll see links to the releases.  You'll be able to download the source code.  Once you have it downloaded, extract it to your custom component location on the home assistant server.  Please be sure to back up that folder so you can revert back in case anything goes wrong.  Then overwrite any files in the fordpass folder with the one you extracted from the download.
Hope that helps, if not, let me know and I can try and get some screenshots to assist.

**Comment by Lux315** [comment]
Thank you very much!

Ill give it a try and start testing👍

**Comment by itchannel** [comment]
Or if using Hacs you can go to the Fordpass integration click re-download and then change the "pre-release" toggle to true. It will then let you automatically use the beta instead of swapping source code :)

**Comment by Lux315** [comment]
Ohh thats way easier, thank you both!
