### ISSUE TITLE
Lock function sending wrong API command

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#307]
same issue with Beta4 - locking doesnt lock the doors, it sends an "unlock" command instead
ford ranger raptor 2023 @doronazl

**Comment by itchannel** [comment]
Will be added in the next beta, have committed the change now.

**Comment by itchannel** [comment]
Fixed in 1.53 Beta 5

**Comment by doronazl** [comment]
> Will be added in the next beta, have committed the change now.

Updated to new beta, its a bit crazier right now.
 First would show status locked when its actually not locked, then after i lock the car to try to sync it to HA, and click unlock, it stays stuck on "unlocking" status and linger like that forever

**Comment by doronazl** [comment]
Im on 1.53 beta 5.2

**Comment by doronazl** [comment]
> So the response from the lock endpoint has changed which means currently the lock will send the command but not update until next refresh. I'm hoping once I've released the update I can work on the nice bits like having the status update immediately. If you have any debug logs it would be handy for me.
> 
> Once you hit lock does it finally update after the 15min interval?

Ok so it finally updated the status after about 20min.
Problem is when its stuck in unlocking status it wont send out any commands.
Only after the status changed after the 20min,then it reacted again, but now it got stuck again so again have to wait until its done, i also tried sending the command through call service lock/unlock.


As for debug, if you could tell me how i can certainly get it and send

**Comment by itchannel** [comment]
> > So the response from the lock endpoint has changed which means currently the lock will send the command but not update until next refresh. I'm hoping once I've released the update I can work on the nice bits like having the status update immediately. If you have any debug logs it would be handy for me.
> > Once you hit lock does it finally update after the 15min interval?
> 
> Ok so it finally updated the status after about 20min. Problem is when its stuck in unlocking status it wont send out any commands. Only after the status changed after the 20min,then it reacted again, but now it got stuck again so again have to wait until its done, i also tried sending the command through call service lock/unlock.
> 
> As for debug, if you could tell me how i can certainly get it and send

Weird it's getting stuck on unlocking for you. It works for me without getting stuck I just have to wait the refresh time. I may disable the unlocking/locking status code for now. Also found a few other bugs in the service calls I need to fix

Debug logs can be obtained by going to the Fordpass integration and enabling Debug, then doing some functions and turning it off. It will then give you a txt download with the data.

**Comment by doronazl** [comment]
> > > So the response from the lock endpoint has changed which means currently the lock will send the command but not update until next refresh. I'm hoping once I've released the update I can work on the nice bits like having the status update immediately. If you have any debug logs it would be handy for me.
> > > Once you hit lock does it finally update after the 15min interval?
> > 
> > 
> > Ok so it finally updated the status after about 20min. Problem is when its stuck in unlocking status it wont send out any commands. Only after the status changed after the 20min,then it reacted again, but now it got stuck again so again have to wait until its done, i also tried sending the command through call service lock/unlock.
> > As for debug, if you could tell me how i can certainly get it and send
> 
> Weird it's getting stuck on unlocking for you. It works for me without getting stuck I just have to wait the refresh time. I may disable the unlocking/locking status code for now. Also found a few other bugs in the service calls I need to fix
> 
> Debug logs can be obtained by going to the Fordpass integration and enabling Debug, then doing some functions and turning it off. It will then give you a txt download with the data.

During the time you wait. It shows you unlocking? Or unlocked?

**Comment by doronazl** [comment]
> > > > > So the response from the lock endpoint has changed which means currently the lock will send the command but not update until next refresh. I'm hoping once I've released the update I can work on the nice bits like having the status update immediately. If you have any debug logs it would be handy for me.
> > > > > Once you hit lock does it finally update after the 15min interval?
> > > > 
> > > > 
> > > > Ok so it finally updated the status after about 20min. Problem is when its stuck in unlocking status it wont send out any commands. Only after the status changed after the 20min,then it reacted again, but now it got stuck again so again have to wait until its done, i also tried sending the command through call service lock/unlock.
> > > > As for debug, if you could tell me how i can certainly get it and send
> > > 
> > > 
> > > Weird it's getting stuck on unlocking for you. It works for me without getting stuck I just have to wait the refresh time. I may disable the unlocking/locking status code for now. Also found a few other bugs in the service calls I need to fix
> > > Debug logs can be obtained by going to the Fordpass integration and enabling Debug, then doing some functions and turning it off. It will then give you a txt download with the data.
> > 
> > 
> > During the time you wait. It shows you unlocking? Or unlocked?
> 
> If I hit the button to lock when it's unlocked it just shows unlocked until it updates.
> 
> The unlocking/locking status is set manually and should only say it for 5seconds max, so something is going wrong when your doing it. Hence if you have any debug logs it would be really helpful.

Where do i find the txt file?

**Comment by itchannel** [comment]
It should auto download in your browser when you click disable debugging.

**Comment by doronazl** [comment]
> It should auto download in your browser when you click disable debugging.

Im on the ios HA App
Do i need to do this from a desktop browser?

**Comment by itchannel** [comment]
Ahh. I've just tried it on the ios app and nothing downloads. So going to say you probably do need to use a desktop browser.

**Comment by doronazl** [comment]
> Ahh. I've just tried it on the ios app and nothing downloads. So going to say you probably do need to use a desktop browser.

Ok done.
Do i need to remove something from the file?
Token? Passwords?

**Comment by doronazl** [comment]
> Ahh. I've just tried it on the ios app and nothing downloads. So going to say you probably do need to use a desktop browser.

Ok i think i got them,removed the token and the vin
Do you have an email i can send to?
