### ISSUE TITLE
Install challenges

### ISSUE THREAD

**Issue by thisisbenwoo** [itchannel/fordpass-ha#31]
I just realized that despite Configuration | Integration showing me I have 2 cars, I actually have no devices or entities. I saw these entries in home-assistant.log:

2020-11-22 13:00:16 WARNING (MainThread) [custom_components.fordpass] 'vehiclestatus'
2020-11-22 13:00:16 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for 1XX2Y3ZZ4ABC56789
2020-11-22 13:00:16 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for 1XX2Y3ZZ4ABC56789
2020-11-22 13:00:16 WARNING (MainThread) [homeassistant.config_entries] Config entry for fordpass not ready yet. Retrying in 5 seconds

I also restarted HA (several times), and each time, I waited for a while before making a determination on whether the integration worked or failed. 

To triple check, I also ssh'd into HA, and I did a ping of google.com and ford.com to make sure the Internet is working or not. But so far, no luck. 

For reference:
 - Standard installation all around
 - Installed the fordpass-ha capabilities through HACS
 - Went to Configuration | Integration and looked for FordPass
 - I confirmed the email/password combo, AND my VIN numbers

**Comment by itchannel** [comment]
Can you confirm your car/cars has a build in ford modem. e.g. has door unlock/lock, remote start and status info.

**Comment by thisisbenwoo** [comment]
Fair question, and yes. I can use FordPass app to start the car from my phone.

**Comment by itchannel** [comment]
Ok. I'll send you a couple of debug files in a bit. If you can run them on a machine with python it will log all the API calls to a text file so I can see exactly what is going wrong for you.

**Comment by thisisbenwoo** [comment]
Thanks, I just saw that Ford has dramatically change the app, and I guess
reset the connections. Before you go to any trouble, I'll give it another
try after I update everything.
---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by itchannel** [comment]
@thisisbenwoo if you are still having issue can you run the files in this thread "debug" #26

**Comment by thisisbenwoo** [comment]
@itchannel - OK, so stupid rookie mistake not checking that everything was up to date on my end. My Explorer is now a device and entity. Unfortunately, despite being able to see my wife's Fusion Titanium Hybrid in our app, it doesn't show up as a device with entities in HA.

I think this is a FordPass issue. I hate that Ford lumps everything into SYNC3, but not every vehicle has the same set of capabilities. eg. Even in the app, I cannot start, stop, lock/unlock my wife's Fusion. OK. Closing this issue, and marking it as a stupid rookie user error.
