### ISSUE TITLE
Odometer no longer available??

### ISSUE THREAD

**Issue by danielbrunt57** [itchannel/fordpass-ha#317]
Is the odometer reading no longer provided by the new API??

![image](https://github.com/itchannel/fordpass-ha/assets/49846893/d982b56e-d95b-45d3-891d-a5510889b498)

**Comment by SquidBytes** [comment]
I was just looking at this when I saw this.
No idea why that's happening. I fixed it on my end, and added it to my pull request.

**Comment by itchannel** [comment]
> Is the odometer reading no longer provided by the new API??
> 
> ![image](https://user-images.githubusercontent.com/49846893/274402726-d982b56e-d95b-45d3-891d-a5510889b498.png)

Could you please enable debug logging and download a copy so I can see your logs. 

@SquidBytes That change you made shouldn't make any difference at all as the value of self.sensor is "odometer" already. Ideally it needs the logs from the users experiencing the issues to see what the error is.

**Comment by frankie-boy-hgv** [comment]
Same here, sometimes it's available, sometime not

**Comment by itchannel** [comment]
Without logs from people I'm struggling to replicate this. I've tried a variety of things in my dev setup including changing options/conversions and it seems to work fine.

**Comment by SquidBytes** [comment]
Yeah my "change" didn't do anything. I just noticed it started working after I made that so I figured why not.
I'll keep my eye on it and if I see it "offline" I'll grab my logs to see if the keys might be missing or something

**Comment by itchannel** [comment]
So I have a fake API setup which I poll against instead of the Ford API and have so far tried a number of peoples provided json files and they all show the odometer fine so certainly is a weird issue and wonder if it's not the odometer crashing it but one of the other sensors as it parses them in order.

**Comment by frankie-boy-hgv** [comment]
> Without logs from people I'm struggling to replicate this. I've tried a variety of things in my dev setup including changing options/conversions and it seems to work fine.

I'll try to get logging, but not much on my laptop the next 2 days :-(

**Comment by danielbrunt57** [comment]
So, after installing Beta4 several days ago and then today Beta6, I had restarted HA both times as required but both lastrefresh and odometer entities were unavailble so today I deleted them as there was no other option.  I just now reloaded the integration and the entity count increased from 16 to 18, restoring both the odometer and lastrefresh entities.  Very strange...

**Comment by danielbrunt57** [comment]
![image](https://github.com/itchannel/fordpass-ha/assets/49846893/ed3d6462-87af-42d4-850d-a19d012676fc)
