### ISSUE TITLE
Not all vehicles support battery capacity

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#319]
Current elveh sensor relies on battery capacity value to be present. Will redo the check to use a variable I can confirm is on most cards.

**Comment by YBonline** [comment]
I figured in case it helps, I'd provide the json data for another vehicle with this issue, my 2017 Ford Fusion Energi (plug in hybrid)


[2017_fusion_energi.json](https://github.com/itchannel/fordpass-ha/files/12875455/2017_fusion_energi.json)

**Comment by itchannel** [comment]
Please try Beta 7 it should fix this issue.

**Comment by YBonline** [comment]
Getting an error... unrelated to this but with beta7

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 495, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 264, in get_value
    if self.data["tirePressure"] is not None:
       ~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'tirePressure'

**Comment by itchannel** [comment]
Please try Beta 8

**Comment by frankie-boy-hgv** [comment]
Awesome, working for me now!

**Comment by YBonline** [comment]
Yes, this seems to work great, thank you! The attributes did change name from the old API but I can update my dashboard to use that if that is the plan to keep them the way they are now

**Comment by YBonline** [comment]
I don't remember how exactly it was before, but just commenting to point out for consistencies sake, the fuel (gas) sensor has the tank percentage as the main variable, and the attribute has "FuelRange" as my old Distance to Empty. The electric sensor now has the Distance to Empty as the main variable, and "Battery Charge" attribute as the percentage

**Comment by itchannel** [comment]
> I don't remember how exactly it was before, but just commenting to point out for consistencies sake, the fuel (gas) sensor has the tank percentage as the main variable, and the attribute has "FuelRange" as my old Distance to Empty. The electric sensor now has the Distance to Empty as the main variable, and "Battery Charge" attribute as the percentage, so the reading of them is kind of reversed

So the reason I've changed it is it seems not all cars support the "Battery Charge" variable so I've put it as an optional attribute and put distance to empty as the main sensor value. Whether I change this I'm open to feedback, just trying to support as many models as possible against the new Fordpass API.

**Comment by YBonline** [comment]
Ok, that makes sense... I guess the obvious question then is what about changing the fuel to make the distance to empty as the main sensor value and the percentage as the attribute to gain that consistency in how fuel levels are reported? Just an idea, I don't care too much either way, I'll just modify my dashboard to make it work

**Comment by itchannel** [comment]
> Ok, that makes sense... I guess the obvious question then is what about changing the fuel to make the distance to empty as the main sensor value and the percentage as the attribute to gain that consistency in how fuel levels are reported? Just an idea, I don't care too much either way, I'll just modify my dashboard to make it work

I'll leave it as is for now, but happy to take feedback on board and see if others want it changed down the road. 

Closing issue as original bug is now fixed.
