### ISSUE TITLE
1.53-Beta6 - Vehicles Frequently Becoming Unavailable

### ISSUE THREAD

**Issue by ziptbm** [itchannel/fordpass-ha#320]
After installing 1.53-Beta6 earlier today, I've noticed my vehicles are frequently losing connection.  All of the sensors become unavailable and it appears to come back by itself after some time or a reloading of the integration on that vehicle also works.  

**Here's a sample of what I'm seeing.**

<img width="583" alt="Screenshot 2023-10-11 at 21 34 51" src="https://github.com/itchannel/fordpass-ha/assets/46136563/de2d6b10-7acc-4423-be7f-cbfb6feaaefc">

**and during this time, I see the following in the logs.  I'm enabling debug logging as well, so please let me know what else would be helpful here.**

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/fordpass/sensor.py:127
Integration: Fordpass (documentation, issues)
First occurred: 09:38:24 (23 occurrences)
Last logged: 21:27:07

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 415, in state
    return self.get_value("state")
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 127, in get_value
    datetime.strptime(
  File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-10-11T13:38:15Z' does not match format '%Y-%m-%dT%H:%M:%S.%fz'
`

`This error originated from a custom integration.

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:322
Integration: Fordpass (documentation, issues)
First occurred: 07:06:42 (26 occurrences)
Last logged: 21:27:03

Error fetching fordpass data: Error communicating with FordPass for REDACTED
Error fetching fordpass data: Error communicating with FordPass for REDCATED`

`This error originated from a custom integration.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:227
Integration: Fordpass (documentation, issues)
First occurred: 07:06:42 (27 occurrences)
Last logged: 21:27:03

No connection adapters were found for 'fordapp://userauthorized?code=REDACTED'
No connection adapters were found for 'fordapp://userauthorized?code=REDACTED'
No connection adapters were found for 'fordapp://userauthorized?code=REDACTED'
No connection adapters were found for 'fordapp://userauthorized?code=REDACTED'
No connection adapters were found for 'fordapp://userauthorized?code=REDACTED'`

**Comment by itchannel** [comment]
Issue will be fixed in the next beta #318 

Sometimes the API returns the data in one format and sometimes its missing the microseconds. I have a fix just haven't rolled it out yet.

**Comment by itchannel** [comment]
Please try the new Beta 7 release. I've hopefully patched the issue referenced.

**Comment by ziptbm** [comment]
Per the other thread, I’ve installed 7.

I was literally taking a screenshot on my phone to show the distance to empty reporting issue and my Mach-e became unavailable within 15 minutes of the install.  Reloading the integration resolved the issue for now.

**Comment by itchannel** [comment]
Can you check your log again and see if that error or any others are present.

**Comment by mattmartinez2006** [comment]
How do i update to the beta version? Sorry, I'm new to home assistant.

**Comment by itchannel** [comment]
Under HACS go to fordpass, click redownload and make sure "Show beta versions" is selected. You can then download the Beta. 

Or wait until later today when I'll be pushing it live anyway :)

**Comment by pimisen** [comment]
Hi everyone, can someone give me a hint on how I can install the latest beta? I have installed 1.52 currently via HACS.

**Comment by JVTEAM** [comment]
Having this issue in the 1.54 release.  it'll load upon boot, but refresh and reload doesn't fix it.

**Comment by ziptbm** [comment]
I'm now on 1.54-Release2 and I'm still seeing this sporadically across both vehicles.  Interestingly though only one vehicle appears to become unavailable at a time.

**Comment by JVTEAM** [comment]
Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:322
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: October 12, 2023 at 8:29:44 AM (655 occurrences)
Last logged: 8:59:38 AM

Error fetching fordpass data: Error communicating with FordPass for Vin1
Error fetching fordpass data: Error communicating with FordPass for Vin2

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:227
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: October 12, 2023 at 8:29:44 AM (655 occurrences)
Last logged: 8:59:38 AM

No connection adapters were found for 'fordapp://userauthorized?code=GqJfSM-WXpzGdP7wJbScqA8BeXPx2uQSe05QTmJuDRU.wBTeH_ssophx5zz-jefpaTC9IiX1Vwh82tdZ8gnmZisjoJE5FKZVbs_m5Cwzt3xo5XC4Ek_zNDKouLBqmE6Ekw&grant_id=fb8e0457-4b94-4f02-8928-c987386db2bf'
No connection adapters were found for 'fordapp://userauthorized?code='
No connection adapters were found for 'fordapp://userauthorized?code='
No connection adapters were found for 'fordapp://userauthorized?code='
No connection adapters were found for 'fordapp://userauthorized?code='

**Comment by itchannel** [comment]
The error is related to the Fordpass API and not being able to connect. 

Can you provide the following info so I can correlate it with anyone else having this issue:

- Version of Home Assistant
- Type of Home Assistant install ( Docker, Hass OS)
- Version of Fordpass Integration
- Country of origin
- Model and age of vehicle
- Did you have this issue before the API changed
- Have you tried rebooting the host HA is running on
- Have you tried uninstalling and reinstalling the integration

**Comment by JVTEAM** [comment]
> The error is related to the Fordpass API and not being able to connect.
> 
> Can you provide the following info so I can correlate it with anyone else having this issue:
> 
> * Version of Home Assistant
> * Type of Home Assistant install ( Docker, Hass OS)
> * Version of Fordpass Integration
> * Country of origin
> * Model and age of vehicle
> * How quickly do you have the integration set to poll
> * Did you have this issue before the API changed
> * Have you tried rebooting the host HA is running on
> * Have you tried uninstalling and reinstalling the integration

 Version of Home Assistant:  Supervisor- 10, OS 10.5
 Type of Home Assistant install ( Docker, Hass OS) Hass os running on a VM
 Version of Fordpass Integration - 1.54
 Country of origin - US
 Model and age of vehicle - 2021 Explorer and 2021 Bronco Sport
 How quickly do you have the integration set to poll - 600 seconds
 Did you have this issue before the API changed - No
 Have you tried rebooting the host HA is running on - Yes
 Have you tried uninstalling and reinstalling the integration - The integration was recently reinstalled

**Comment by DougSisk** [comment]
On 1.57 and all my sensors go "Unavailable" when it attempts to refresh. Have a 2022 Mustang Mach-E.

**Comment by pbryan7** [comment]
I'm also still seeing this with some frequency on 1.57...   It was not something that was common with the old API.

I get the following log entries when it happens:
2023-10-13 14:55:35.450 WARNING (MainThread) [custom_components.fordpass] No connection adapters were found for 'fordapp://userauthorized?code=xxxxxxxxxxxxxxxxxx'
2023-10-13 14:55:35.450 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for 3FMTxxxxxxxxxxxxxxxxx
2023-10-13 14:55:35.450 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for 3FMTxxxxxxxxxxxxxxxx

This particular car is a 2023 US MachE...  I have the same problem occasionally on my Bronco too.
I'm running HA 2023.10.1, on a RPi with HASS OS 10.5
Integration is polling at 900s on both vehicles.

I'm happy to try to collect more log data if that helps...

--Paul

**Comment by itchannel** [comment]
So I actually have seen this once or twice in my production HA instance. I'll try and debug and find away round it. From what I can tell the URL from the initial token step is not responding all the time. Which results in the error and the next step not being able to progress. 

Problem being it seems more of an API issue, but maybe I can catch the error and retry. But not going to be a quick fix as can only replicate every 24hrs or so.

**Comment by pbryan7** [comment]
I get a drop out closer to hourly, similar to the data presented in the first post.   If there is anything I can provide that would help, let me know...

I'd settle for keeping the old 'stale' data after a d/l error (although perhaps not forever), seeing 'Unavailable' for my MachE SOC frequently on my dashboard is annoying...

**Comment by amichaelwagner** [comment]
Same issue for me. Also happy to help in any way that might be useful.

**Comment by JVTEAM** [comment]
Mine's been unavailable for 24 hours now.  Reboot and reload doesn't fix it...

**Comment by ziptbm** [comment]
I updated to 1.57-Release about 12 hours ago and I just noticed the sensors for both of my vehicles has been offline for 11 hours.  Reloading the sensors has not worked as they are still unavailable.

**Comment by itchannel** [comment]
Is this fixed for people in 1.58?

**Comment by JVTEAM** [comment]
> Is this fixed for people in 1.58?

Yes!  thank you
