### ISSUE TITLE
Add logic to detect lock status when locking

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#323]
Need to rewrite the code as the command function to lock the door no longer returns a status code it now returns a json array with a timelimit for the command to run. May be able to base a refresh off this timer.

**Comment by itchannel** [comment]
Added 90 second delay before polling car data. Command always returns with a expireTime which is 90seconds after the command has been sent. 

So easiest option was to add a 90 second delay before polling if the command was successfully sent which seems to work well. Also have re-enabled locking/unlock status's in HA

Coming in 1.54

**Comment by itchannel** [comment]
Should be working in 1.54 now

**Comment by doronazl** [comment]
> Added 90 second delay before polling car data. Command always returns with a expireTime which is 90seconds after the command has been sent.
> 
> So easiest option was to add a 90 second delay before polling if the command was successfully sent which seems to work well. Also have re-enabled locking/unlock status's in HA
> 
> Coming in #325

Will we get something like a live status like it used to be before?
Or like the fordpass app doing?

**Comment by itchannel** [comment]
@doronazl Give 1.57 Beta 1 a test. I've rewritten the command function to poll every 10 seconds and check the status of the command. It will keep doing it until the command returns "success" or "expired"

**Comment by doronazl** [comment]
> @doronazl Give 1.57 Beta 1 a test. I've rewritten the command function to poll every 10 seconds and check the status of the command. It will keep doing it until the command returns "success" or "expired"

Just did. A whole lot better now, no doubt.
It no longer getting hung up on locking or unlocking and feels much more responsive!

It was on locked status at first even though the car isnt locked so i had to attempt and unlock and lock again but that could have been that way before the version update.

Il keep an eye on it and try to enable logger everytime from now on.

**Comment by itchannel** [comment]
There is one bug I need to fix, where if the token has expired and you run a command like locking it fails. Simple fix just to refresh the token first if needed. 

That's tomorrows job though, I'll leave it in Beta for now. I've tried a few commands against my vehicle and as long as the car is awake it returns pretty dam quick :)

**Comment by doronazl** [comment]
Yes 100% when its awake everything works a charm.
How do i refresh the token? Is there a way to automate it? Perhaps at every
time i click the lock or unlock?
Thats was gonna be my next question to you, any way to keep it awake
somehow? Or would that trigger some sanctions from ford?

**Comment by itchannel** [comment]
Fixed the token issue, released 1.57 early due to another bug. 

So I've actually found some hidden commands, haven't tried them out yet but one of them is 
```
        "deviceWakeup": {
            "timestamp": "2023-10-10T15:16:52.481904Z",
            "commandId": "71e6fff3-2715-4810-ab24-20d67ad29edb",
            "value": {
                "fromState": "REQUEST_DELIVERY_IN_PROGRESS",
                "toState": "REQUEST_DELIVERY_SUCCESS",
                "trigger": {
                    "deviceWakeup": "CARRIER_DELIVERY_SUCCESS"
                }
```

However keeping your cars ecu await would surely drain the battery quick

**Comment by doronazl** [comment]
> > > Fixed the token issue, released 1.57 early due to another bug.
> > > So I've actually found some hidden commands, haven't tried them out yet but one of them is
> > > ```
> > >         "deviceWakeup": {
> > >             "timestamp": "2023-10-10T15:16:5",
> > >             "commandId": "71e6fff3-271",
> > >             "value": {
> > >                 "fromState": "REQUEST_DELIVERY_IN_PROGRESS",
> > >                 "toState": "REQUEST_DELIVERY_SUCCESS",
> > >                 "trigger": {
> > >                     "deviceWakeup": "CARRIER_DELIVERY_SUCCESS"
> > >                 }
> > > ```
> > > 
> > > 
> > > However keeping your cars ecu await would surely drain the battery quick
> > 
> > 
> > That bad huh? Device wakeup command would be cool too
> 
> Not bad just missing information for a sensor. A pull request that @SquidBytes did accidentally removed the return function for elveh :)
> 
> Other commands are: "reportWifiUsage", "deviceConnectivity", "configurationUpdate" "deviceDiagnostic" "pauseGlobalChargeCommand"

I meant the battery getting drained by leaving it awake.

How about this device wakeup, is it possible to use? By call service or something?

**Comment by SquidBytes** [comment]
> A pull request that @SquidBytes did accidentally removed the return function for elveh :)

My bad. Copy paste error. Forgot to add back in return

**Comment by itchannel** [comment]
Closing as original issue is fixed.
