### ISSUE TITLE
Integration errors on 1st load

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#326]
Token isn't cached correctly on first run. It then retries and works. 

Need to look at this down the line

**Comment by JVTEAM** [comment]
Not sure if related, but when I first upgraded it loaded fine.  Then it went unavailable and wouldn't reload.  Only a full restart of HA brought it back online.

**Comment by itchannel** [comment]
Is it still going down for you? That error looks related to the token bit. Wondering if the  Fordpass API had a wobbly.

**Comment by Rodelkoenig** [comment]
Got the same issue. When restarting HA it works once, but fails at first "refresh cycle" (at 15min for me)  and also doesn't recover from this state itself.

**Comment by itchannel** [comment]
Can you please provide a copy of your HA logs

**Comment by Rodelkoenig** [comment]
ofc, here you go:

Logger: urllib3.connectionpool
Source: custom_components/fordpass/fordpass_new.py:95
Integration: FordPass (documentation, issues)
First occurred: 10:37:48 (3 occurrences)
Last logged: 12:18:37

Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=YYY&code_challenge=XXX&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=YYY&code_challenge=XXX&code_challenge_method=S256
Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /v1.0/endpoint/default/authorize?redirect_uri=fordapp://userauthorized&response_type=code&scope=openid&max_age=3600&client_id=YYY&code_challenge=XXX&code_challenge_method=S256

___________

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:227
Integration: FordPass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: 10:37:50 (8 occurrences)
Last logged: 12:18:39

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
No connection adapters were found for 'fordapp://userauthorized?code=removedByMe
'auto_token'

___________

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:322
Integration: FordPass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: 10:37:50 (3 occurrences)
Last logged: 12:18:39

Error fetching fordpass data: Error communicating with FordPass for myVIN

**Comment by itchannel** [comment]
So that looks like the first call to the authentication endpoint is failing to connect. How are you running your HA instance, HA OS, docker ? I would say there's some network issues with your setup potentially.

**Comment by Rodelkoenig** [comment]
HA OS on a VM.
Pi-Hole allowed 100% of HA requests including those to Ford. Besides that there are no networking issues, neither within HA nor outside.

But I'll have a closer look at it.

**Comment by itchannel** [comment]
Let me know how you get on. I'm going to close this issue as your issue is not related to this one. But feel free to open up a new issue if you can't get to the bottom of it.
