### ISSUE TITLE
Getting "Forbidden" error and integration is not working.

### ISSUE THREAD

**Issue by Darkcitadel** [itchannel/fordpass-ha#331]
For the last few days I have been getting the below error.  I deleted the integration and added it again and it found my VIN but I am seeing the below error when it tries to get status info about the vehicle.  I also ran the "clear_tokens" to see if that would help and it did not.

If I should post this someplace please let me know.

************  Error  ************
This error originated from a custom integration.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:227
Integration: Fordpass (documentation, issues)
First occurred: October 8, 2023 at 5:07:24 PM (1078 occurrences)
Last logged: 10:59:11 AM

500 Server Error: Internal Server Error for url: https://api.mps.ford.com/api/expdashboard/v1/details/
403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v5/{MYVIN}/status?lrdt=01-01-1970+00%3A00%3A00

**Comment by brewskihub** [comment]
I'm getting the same error:
DEBUG (SyncWorker_7) [custom_components.fordpass.fordpass_new] Token is valid, continuing
WARNING (MainThread) [zigpy.zcl] [0x8F58:1:0xef00] Unknown cluster command 2 b'\x00Nm\x02\x00\x04\x00\x00\x00\x00'
WARNING (MainThread) [zigpy.zcl] [0x8F58:1:0xef00] Unknown cluster command 2 b'\x00Nm\x02\x00\x04\x00\x00\x00\x00'
WARNING (MainThread) [zigpy.zcl] [0x8F58:1:0xef00] Unknown cluster command 2 b'\x00Nm\x02\x00\x04\x00\x00\x00\x00'
WARNING (MainThread) [custom_components.fordpass] 403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v5/{myvin}/status?lrdt=01-01-1970+00%3A00%3A00
WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for {myvin}
ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for {myvin}
DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.418 seconds (success: False)

**Comment by itchannel** [comment]
@brewskihub @Darkcitadel Have you upgrade to 1.54 as the API has been changed by Ford hence the new updates.

**Comment by brewskihub** [comment]
I just did and it works.  Thanks.

**Comment by Darkcitadel** [comment]
> @brewskihub @Darkcitadel Have you upgrade to 1.54 as the API has been changed by Ford hence the new updates.

I thought I had the latest version because the Community store was not telling me there was a new version.  Live and learn I guess.

**Comment by chaseadal** [comment]
Hi @itchannel, I am going to look into HomeAssistant as this looks pretty cool to do. However, at the moment, I am trying to fix some iOS shortcuts I had working to control my truck. I tried looking through your code but I cannot figure out the API structure and authentication process. Where would I find the fordpass API documentation for this new API to figure out the right way to authenticate and send commands?

**Comment by itchannel** [comment]
> Hi @itchannel, I am going to look into HomeAssistant as this looks pretty cool to do. However, at the moment, I am trying to fix some iOS shortcuts I had working to control my truck. I tried looking through your code but I cannot figure out the API structure and authentication process. Where would I find the fordpass API documentation for this new API to figure out the right way to authenticate and send commands?

There is no official documentation, developer information available. The only information by ford is very outdated.

Only way to do it is to work out the endpoints yourself and experiment with given values. It's why it's taking me so long to implement changes.

**Comment by itchannel** [comment]
Closing as the original issue has been resolved by the user.
