### ISSUE TITLE
Sensor not always updating

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#334]
Putting this issue here as have been working on it with @mojomojoman

I honestly don’t understand what’s going on in your instance. 

From your logs I can clearly see that the API has reported back multiple times that the vehicle is unlocked but you’re saying that status wasn’t reflected in HA?

```
{"doorLockStatus":[{"updateTime":"2023-10-12T04:26:04Z","oemCorrelationId":"56822","value":"UNLOCKED","vehicleDoor":"ALL_DOORS"}
```

I’ve got to work today but I’ll try running some tests later on my dev instance using the json from yours to see if I can replicate the bug. 

The  initial error when starting HA I am aware of , it’s to do with how the token is initially handled on the first load. It’s on my list to fix but doesn’t really cause an issue just has to reload and starts 2nd time for now.

**Comment by doronazl** [comment]
Mine also acting weird.
Vehicle is locked. Trying to unlock it would say unlocking, then go back to locked again, in reality doors stayed locked

**Comment by itchannel** [comment]
> Mine also acting weird.
> 
> Vehicle is locked. Trying to unlock it would say unlocking, then go back to locked again, in reality doors stayed locked 

Is your car low on battery?

If you enable debugging and look in your logs you will see the huge vehicle json. In there is a section called events which will show the results of the lock command, can you take a look and see if it came back successful or if it reported an error.

The sensor itself if it didn't come back as unlocked after 90 seconds it will revert to the previous state

**Comment by doronazl** [comment]
> > Mine also acting weird.
> > Vehicle is locked. Trying to unlock it would say unlocking, then go back to locked again, in reality doors stayed locked
> 
> Is your car low on battery?
> 
> If you enable debugging and look in your logs you will see the huge vehicle json. In there is a section called events which will show the results of the lock command, can you take a look and see if it came back successful or if it reported an error.
> 
> The sensor itself if it didn't come back as unlocked after 90 seconds it will revert to the previous state

Not low on battery.
so you mean enable debug, do some actions, disable it, get the txt file and look for the event result in it ?

i keep testing trying to get a clearer picture- for example now i have unlocked the car from the ford app, the status on the home assistant app did not change to unlocked, 5 min have passed, is it supposed to after 15 min ?

**Comment by doronazl** [comment]
> > > Mine also acting weird.
> > > Vehicle is locked. Trying to unlock it would say unlocking, then go back to locked again, in reality doors stayed locked
> > 
> > 
> > Is your car low on battery?
> > If you enable debugging and look in your logs you will see the huge vehicle json. In there is a section called events which will show the results of the lock command, can you take a look and see if it came back successful or if it reported an error.
> > The sensor itself if it didn't come back as unlocked after 90 seconds it will revert to the previous state
> 
> Not low on battery. so you mean enable debug, do some actions, disable it, get the txt file and look for the event result in it ?
> 
> i keep testing trying to get a clearer picture- for example now i have unlocked the car from the ford app, the status on the home assistant app did not change to unlocked, 5 min have passed
> 
> then i enabled debug, tried a lock command, the status went to locking, then changed to unlocked, and stay this way, in reality it didnt lock the car.

then after the 2nd attempt when the status got synced with the real status of the doors, if id try again, to lock the doors, then the command worked, the doors got locked, and the status changed to lock properly.

**Comment by doronazl** [comment]
> > Mine also acting weird.
> > Vehicle is locked. Trying to unlock it would say unlocking, then go back to locked again, in reality doors stayed locked
> 
> Is your car low on battery?
> 
> If you enable debugging and look in your logs you will see the huge vehicle json. In there is a section called events which will show the results of the lock command, can you take a look and see if it came back successful or if it reported an error.
> 
> The sensor itself if it didn't come back as unlocked after 90 seconds it will revert to the previous state

one thing i suspect is this could be related to the initial command being so slow.
not sure how is it with other cars, im assuming its the same as mine, but when i leave my car alone lets say for a couple of hours, the first command im sending, lock/unlock/start engine/ whatever, takes ages to respond, like 30sec easy, im assuming its the initial uplink being established after it went into sleep mode, after that initial command goes through, then every following command is quick, 2-3 seconds max, works a treat, no lag.
could this be related ?

**Comment by doronazl** [comment]
> > Mine also acting weird.
> > Vehicle is locked. Trying to unlock it would say unlocking, then go back to locked again, in reality doors stayed locked
> 
> Is your car low on battery?
> 
> If you enable debugging and look in your logs you will see the huge vehicle json. In there is a section called events which will show the results of the lock command, can you take a look and see if it came back successful or if it reported an error.
> 
> The sensor itself if it didn't come back as unlocked after 90 seconds it will revert to the previous state

Ok so 2nd time this happened now, car was unlocked, last action was 3 hours ago, first attempt to lock showed locking then locked, in reality nothing happened on the car

**Comment by itchannel** [comment]
In the HA logs can you see the command being sent to the car and then after 90seconds can you see the vehicle refresh. 

If you check this data does it now show as unlocked?

**Comment by doronazl** [comment]
> In the HA logs can you see the command being sent to the car and then after 90seconds can you see the vehicle refresh.
> 
> If you check this data does it now show as locked?

Didn't have the logger on, il try again in a couple of hours

**Comment by itchannel** [comment]
If it encountered an error it should still show in the logs. Just won't have as much debug details.

**Comment by mojomojoman** [comment]
I've always had issues waking the car up by just issuing commands.  Even from the Ford app it can be really slow just to refresh data like battery status unless the car was recently poked awake somehow like plugging it in or locking/unlocking doors. It's finicky to say the least. That being said the car does usually eventually respond and lock/unlock the doors or whatever I'm asking it to do but to get HA to reflect that it seems i've nearly always had to reload the integration for which I usually use the service call in HA via a button I put on my HA dashboard.  So I would, in the past, issue the lock/unlock command and wait for a minute then hit reload and HA would show it updated.  Never did much digging into it back then.  Figured their API was crap (I mean their lackluster app kinda reinforces that idea) and that's just how it was  Only recently after this change have I noticed that the API data actually does get updated and maybe the problem is in HA.

**Comment by mojomojoman** [comment]
> Putting this issue here as have been working on it with @mojomojoman
> 
> I honestly don’t understand what’s going on in your instance.
> 
> From your logs I can clearly see that the API has reported back multiple times that the vehicle is unlocked but you’re saying that status wasn’t reflected in HA?
> 
> ```
> {"doorLockStatus":[{"updateTime":"2023-10-12T04:26:04Z","oemCorrelationId":"56822","value":"UNLOCKED","vehicleDoor":"ALL_DOORS"}
> ```
> 
> I’ve got to work today but I’ll try running some tests later on my dev instance using the json from yours to see if I can replicate the bug.
> 
> The initial error when starting HA I am aware of , it’s to do with how the token is initially handled on the first load. It’s on my list to fix but doesn’t really cause an issue just has to reload and starts 2nd time for now.

Yeah the data was "out there" as I could poll it with that Autonomic.py script so I assume HA was polling it as well but not sure why the entities would not change.  As i've said before all this API change stuff happened I used to just reload it when I thought the data was out of sync and that would take care of it. However while I was on beta-6 at least a reload wouldn't even refresh it so I had to reboot HA to see the changes.  I just updated to your latest release and will see if I can recreate the behavior.

**Comment by doronazl** [comment]
@itchannel it keeps getting stuck in locking status after a while.
Am i only one having this trouble?

**Comment by doronazl** [comment]
I send the command to lock, it would lock the car, but get hung ok on locking status forever

**Comment by itchannel** [comment]
I haven't had anyone else report this issue and I haven't been able to replicate it myself. I'll try and do some more debugging on my test instance.

**Comment by doronazl** [comment]
![IMG_0652](https://github.com/itchannel/fordpass-ha/assets/49086523/a466232c-7979-4b12-b42b-0f7f973a3308)
So weird

It hangs this way until i reload the integration

**Comment by doronazl** [comment]
Ok so i can definitely recreate it.
I reload the integration. It then goes into static status- the current and correct one.
Then i try an action, it would successfully get it done but stays in that ongoing action.

I also notice an error popping up after a few seconds below.
Saying failed to call service lock/unlock xevbatterychargercurrentoutput

**Comment by itchannel** [comment]
Can you do a show all on the logs and just give me a little more output. Do you have an electric car?

**Comment by doronazl** [comment]
> Can you do a show all on the logs and just give me a little more output. Do you have an electric car?

show all on the logs ? what that mean?

and no, not electric

**Comment by itchannel** [comment]
go to /config/integrations/integration/fordpass

Click enable debugging and then click it again. Should download a big log file (Not on mobile) and then look in there for xevbatterychargercurrentoutput and send me the error messages

**Comment by doronazl** [comment]
this is what i could find in the logs

  File "/config/custom_components/fordpass/lock.py", line 43, in async_lock
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 240, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 647, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 513, in get_value
    self.data["xevBatteryChargerCurrentOutput"]["value"] is not None and self.data["xevBatteryChargerVoltageOutput"]["value"] is not None
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'xevBatteryChargerCurrentOutput'

**Comment by itchannel** [comment]
Change that line to read 
```
"xevBatteryChargerCurrentOutput" in self.data and self.data["xevBatteryChargerCurrentOutput"]["value"] is not None and self.data["xevBatteryChargerVoltageOutput"]["value"] is not None
```

instead of 
```
self.data["xevBatteryChargerCurrentOutput"]["value"] is not None and self.data["xevBatteryChargerVoltageOutput"]["value"] is not None
```

**Comment by doronazl** [comment]
where do i find this sensors.py file ?

**Comment by itchannel** [comment]
in /config/custom_components/fordpass/sensor.py

**Comment by itchannel** [comment]
You will need to reload HA after you've made the change

**Comment by doronazl** [comment]
ok that fixed it, no error , locking/unlocking correctly and status updates in time

so what happened here ?
where this error suddenly came from ? for a few days since you released the 1.57 everything worked great i changed nothing on my end.

and will this change stay put ? or if i update to newer versions of your integration might have to be done again ?

**Comment by itchannel** [comment]
I've committed the fix into the next release. So it will stay put. 

I think some of the EV integration @SquidBytes has been introducing wasn't checking a certain value existed. Weird only you got the error. Didn't show in my logs at all when testing.

**Comment by doronazl** [comment]
im lucky that way :/
anyway glad its working again, thank you sir.

**Comment by itchannel** [comment]
No problems thanks for helping squish a bug :)
