### ISSUE TITLE
Location shows wrong data

### ISSUE THREAD

**Issue by Uthrom** [itchannel/fordpass-ha#336]
<img width="302" alt="fordpass-lat-lon" src="https://github.com/itchannel/fordpass-ha/assets/54080913/e3d98eee-fd51-4511-ba16-2c0c8f90b90d">

After the autonomics changes, the GPS lat/lon is not showing properly.

1.54

**Comment by itchannel** [comment]
The device_tracker entity is the one to use. The fordpass_gps really only shows debug data. I'm tempted to just remove it as the device tracker contains all of the same data.

**Comment by itchannel** [comment]
GPS sensor has been removed. All attributes have been added to the device_tracker

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/85d2512d-df5d-40f4-943b-01b232becb97)
