### ISSUE TITLE
Tire Pressure Values partially correct (1.54-Release2)

### ISSUE THREAD

**Issue by rtw819** [itchannel/fordpass-ha#337]
Thank you for all you do!

Rear tire pressure measurement calculations seem to be off (Sensor fordpass_tirePressure on my F-150 Lightning)

I'm pretty sure they were all accurate prior to the API changes.

Attributes
FRONT LEFT       42
FRONT RIGHT    42
REAR LEFT          9,505
REAR RIGHT       9,505

**Comment by rtw819** [comment]
For what it's worth, all 4 tire pressure values are all expected/correct on the Mach-E.

**Comment by itchannel** [comment]
Any chance you can enable debug logging and check the json in the logs to see what is being returned in the tirepressure array.

**Comment by rtw819** [comment]
Yep, I'll see what data it pulls

**Comment by rtw819** [comment]
While I can't seem to readily figure out how to install python3 / pip3 / modules on my Odroid N2+ HA platform to run the script, but, after a refresh of the truck data, it seems the logs indicate proper data, and the tire pressures for all 4 tires are now reasonable kPa native values in the JSON and sensor values are accurate accordingly.

Here's a snippet of JSON from the debug log for the truck VIN after a status update was received:

"tirePressure":[{"updateTime":"2023-10-13T04:45:27Z","oemCorrelationId":"140516","value":269.0,"vehicleWheel":"FRONT_LEFT","wheelPlacardFront":289.57991999999996},{"updateTime":"2023-10-13T04:45:27Z","oemCorrelationId":"140516","value":279.0,"vehicleWheel":"FRONT_RIGHT","wheelPlacardFront":289.57991999999996},{"updateTime":"2023-10-13T04:45:27Z","oemCorrelationId":"140516","value":274.0,"vehicleWheel":"REAR_LEFT","wheelPlacardRear":289.57991999999996},{"updateTime":"2023-10-13T04:45:27Z","oemCorrelationId":"140516","value":273.0,"vehicleWheel":"REAR_RIGHT","wheelPlacardRear":289.57991999999996}],"tirePressureSystemStatus":[{"updateTime":"2023-10-13T04:45:27Z","oemCorrelationId":"140516","value":"NORMAL_OPERATION"}]

The Truck's fordpass_tirePressure sensor is (still) reporting Normal, however, ALL 4 tire values are now also seemingly correct:

FRONT LEFT     39
FRONT RIGHT  40
REAR LEFT        40
REAR RIGHT     40

It has cooled off 20+ degrees outside, and the tires are cool now too.

I guess I'm going to chalk this up to the initial status pull/check not having proper tire pressure data somehow ??  Not sure why it would have reported only part of the pressures properly the first time, but, it seems good now.

Weird.

**Comment by itchannel** [comment]
Going to close as looks like stagnant data was coming from the API. Will reopen if your experience this issue again.
