### ISSUE TITLE
various issues for 2019 ford edge

### ISSUE THREAD

**Issue by ecto1a2003** [itchannel/fordpass-ha#339]
just adding the json to help out. i also have a 2019 fusion hybrid that ill add later
[ecto1a2003_status_2023-10-12_22_28_48.json](https://github.com/itchannel/fordpass-ha/files/12889876/ecto1a2003_status_2023-10-12_22_28_48.json)

**Comment by ecto1a2003** [comment]
2019 fusion does this

HTTP Error: 404 Client Error: Not Found for url: https://api.autonomic.ai/v1beta/telemetry/sources/fordpass/vehicles/3fa6p0ru5kr140856:query
done

**Comment by itchannel** [comment]
So that's not a valid vin number being sent to the api which is why your getting a 404. Where did you get that url string from?

**Comment by ecto1a2003** [comment]
> Ignore me apparently it is.
> 
> So the autonomous script worked for you but HA isn't?

flip that actually

**Comment by ecto1a2003** [comment]
wow, vin is case sensitive for the autonomous script
[ecto1a2003_status_2023-10-13_02_10_35.json](https://github.com/itchannel/fordpass-ha/files/12891620/ecto1a2003_status_2023-10-13_02_10_35.json)

**Comment by itchannel** [comment]
Cheers. Just to confirm you're now having no issues?

**Comment by ecto1a2003** [comment]
correct, just adding json for the grinder

**Comment by itchannel** [comment]
Thanks :) Will close this issue now and thanks for the json 👍
