### ISSUE TITLE
+15 minutes button or service call?

### ISSUE THREAD

**Issue by TRusselo** [itchannel/fordpass-ha#34]
Is there a way to add 15 minutes to the starter timer?

Not sure if its the same in all markets, but here in Canada, all starters are the same,
Runs for 15 minutes.  Can be started or extended once more before requiring key in ignition.

The fordpass android app has a button to extend the remote start by 15 minutes.  The app will let you use it once before requiring the key to turn in the ignition.

Here in northern Canada, its DAMN cold.  We need the full 30 minutes to warm up.

How can this be achieved?   Button? Timer? Slider? Service Call? Automation?

**Comment by itchannel** [comment]
Could probably be achieved using a service call. I don't have the option to extend on mine or at least it's never shown up just have start and kill. Would need a packet capture of someone extending the start times so I can figure out what API call it makes.

**Comment by TRusselo** [comment]
you know of an easy way to do that, or should i just start googling?
Say i run it on my work phone,  run something on the same network to capture packets from the network and filter for work phone MAC address or something?

**Comment by TRusselo** [comment]
i have a tcpdump while i started, and extended the vehicle....  i see the phone IP...  talking to google not much else... 192.168.1.118
[tcpdump.txt](https://github.com/itchannel/fordpass-ha/files/5587496/tcpdump.txt)

**Comment by itchannel** [comment]
tcpdump won't help. Needs you to set a proxy on your phone to point to something like Burp to intecercept the traffic as the app communicates over https. I'll have a look once we've fixed the timeout issue for some people

**Comment by itchannel** [comment]
If you want to try yourself you can follow this tutorial 

https://portswigger.net/support/configuring-an-android-device-to-work-with-burp

**Comment by TRusselo** [comment]
its not a big deal, no rush.
I actually found a work around,  

start, delay 15min 30sec, start again.

I actually setup an automation to auto start (twice) on days I work by using a calendar event

google_calendars.yaml:
`  entities:
  - device_id: PERSON_work
    ignore_availability: true
    name: Tristyn's Work
    track: true
    max_results: 30
    search: Work`

automations.yaml:
`- id: '1606195208315'
  alias: Start Van on Workdays
  description: ''
  trigger:
  - platform: time
    at: '7:30:00'
  condition:
  - condition: template
    value_template: '{{ ((as_timestamp(states.calendar.PERSON_work.attributes.start_time)
      - as_timestamp(now())) < 43200) and ((as_timestamp(states.calendar.PERSON_work.attributes.start_time)
      - as_timestamp(now())) > 0) }}'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.fordpass_ignition_switch
  - delay: 00:15:30
  - service: switch.turn_on
    data: {}
    entity_id: switch.fordpass_ignition_switch
  mode: single

`

**Comment by itchannel** [comment]
Nice little workaround :)

**Comment by TRusselo** [comment]
The downside is it's twice as much wear and tear on the starter but it's a company lease vehicle so I'm not upset.

**Comment by itchannel** [comment]
Once someone provides a copy of the API call for extending the timer I can build it in, unfortunately I double checked my app and don't have that ability

**Comment by TRusselo** [comment]
Yeah im 3000 km away from my work phone right now. ill look into it when i get home

**Comment by itchannel** [comment]
👍

**Comment by Madseason41** [comment]
Any update on this? I have an extend button on my app that extends for 10 min. I’m willing to help but need instructions on how to capture the call.

**Comment by itchannel** [comment]
@Madseason41 I haven't had a chance to look at this as it's not a feature on my version of the application. I have a feeling though it might just send another start command to extend the timer. So potentially could just send fordpass_ignition start again to reset the timer.

**Comment by jrprinty** [comment]
Thank you so much for this integration. My family uses it multiple times a day. 

You can extend the remote start time by the 15 minutes, by running another service call to switch.turn_on to the ignition switch. You can not use the GUI of course as that will turn the switch off. 

I turn the ignition switch on then wait about 30 seconds (not sure that it is actually needed) and then run the service as stated above and it will be then have a total run time of 29 minutes and 30 seconds.

**Comment by SquidBytes** [comment]
I'm going to close this as the last update was from Jan of 2022.
There have been large changes from them.
Please open a new issue for any new issues :)
