### ISSUE TITLE
No extra elVeh info after 1.56-release

### ISSUE THREAD

**Issue by frankie-boy-hgv** [itchannel/fordpass-ha#342]
My GPS is now gone 😀

**Comment by itchannel** [comment]
I've removed it as per the changelog lol. 

All details are contained in the device_tracker entity:

![274881055-85d2512d-df5d-40f4-943b-01b232becb97](https://github.com/itchannel/fordpass-ha/assets/5840973/c3f906ca-be96-4f10-8a45-946fbbb14a07)

**Comment by frankie-boy-hgv** [comment]
Dumb me, missen it 😀

**Comment by frankie-boy-hgv** [comment]
But I do miss my extra elVeh info 😀

**Comment by itchannel** [comment]
> But I do miss my extra elVeh info 😀

What info is missing?

**Comment by itchannel** [comment]
Found the issue lol. I merged a pull request from someone and his code didn't return the array. Rookie error :)

**Comment by frankie-boy-hgv** [comment]
> > But I do miss my extra elVeh info 😀
> 
> What info is missing?

Plug Status
Charge Status
Battery Charge

Had an automation on Plug Status..

![Screenshot_20231013_140432_Home Assistant](https://github.com/itchannel/fordpass-ha/assets/70746913/7b794d8e-9311-48b6-bc27-e43c66a3b69d)

**Comment by itchannel** [comment]
1.57 is now out earlier than planned and restores those sensors for you :)

**Comment by frankie-boy-hgv** [comment]
You must have been working overtime, think you need a coffee 😉

**Comment by itchannel** [comment]
I'm basically dead this week between work and this. I'm looking forward to the weekend :)

**Comment by frankie-boy-hgv** [comment]
Fixed indeed

**Comment by itchannel** [comment]
Thanks for the coffee, it's greatly appreciated :)
