### ISSUE TITLE
Outside Temp Sensor in C?

### ISSUE THREAD

**Issue by magnetic157** [itchannel/fordpass-ha#345]
Is there a way to change the outside temp reading to be F like the rest of the ones or do I have to create a manual template sensor with a conversion?  Really liking all the new sensor data though - keep up the amazing work!!

<img width="437" alt="image" src="https://github.com/itchannel/fordpass-ha/assets/78054864/c0b2e2b9-a37a-436b-a4b6-8117466dd318">

**Comment by itchannel** [comment]
Yes I'll add that as something to change for the next release. Only thing to note is I'm not sure if that value is celcius or fahrenheit for everyone. So I may need to do a conversion depending on feedback

**Comment by gniknalu** [comment]
Mine currently says 24.0
CLEARLY C and not Fahrenheit  because if it was Fahrenheit we'd all be dying here - LOL

**Comment by itchannel** [comment]
haha. I just wonder for some people if it will come back in a different format similar to how odometers are handled :). 

But for now I'll leave it as C and add in the units for the other sensors that are missing them later today.

**Comment by jpettitt** [comment]
There are a lot of units issues in the latest release - odometer in kM no mater what unit I select,  range in kM, tire pressure in kPa, temps in C not matter what unit I select.

**Comment by itchannel** [comment]
> There are a lot of units issues in the latest release - odometer in kM no mater what unit I select, range in kM, tire pressure in kPa, temps in C not matter what unit I select.

If your finding issues then please raise separate issues so I can track them. Yes there is currently unit conversion issues for some items which will be rectified over the coming week. Odometer though should be working have you changed the options in Fordpass options?

**Comment by magnetic157** [comment]
All mine seem to be fine except this one 🤷🏼‍♂️

**Comment by SquidBytes** [comment]
These should be fixed in 1.58 Release
