### ISSUE TITLE
fordpass_alarm :: PREARMED

### ISSUE THREAD

**Issue by gniknalu** [itchannel/fordpass-ha#346]
This is a new status for the alarm: PREARMED

Is it anything useful that I need to consume or automate? (Like if it's PREARMED, should I do anything to make it ARMED?)

THANK YOU!

![20231013_prearmed](https://github.com/itchannel/fordpass-ha/assets/3652809/527ca8c1-84c7-4707-9d4c-d6b271c0987a)

**Comment by itchannel** [comment]
So if you lock the car using HA or the APP it goes to PREARMED. If you then manually send for a status update it will change to ARMED. Unfortunately the car doesn't automatically send the update to the API to say it's gone from PREARMED to ARMED. Status wise however it still means the alarm is activated and working.

**Comment by gniknalu** [comment]
Thank you. I'll update accordingly. **Awesome work** - highly valued.
