### ISSUE TITLE
All entities become unavailable but integration is still running.

### ISSUE THREAD

**Issue by mojomojoman** [itchannel/fordpass-ha#347]
HA: 2023.10.3
FordPass: 1.57-Release

All of my entities just went unavailable but the integration still shows running.

This has happened to me a few times since the major overhaul but usually it was overnight and I brushed it off as maybe internet issues or something I did since I've been tinkering with code and running beta versions but today it happened again and I've been on the new full release all day and have not really been messing with anything.

This time I managed to capture an error message:

```
This error originated from a custom integration.

Logger: urllib3.connectionpool
Source: custom_components/fordpass/fordpass_new.py:407
Integration: Fordpass (documentation, issues)
First occurred: 12:15:33 PM (1 occurrences)
Last logged: 12:15:33 PM

Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /api/messagecenter/v3/messages
```

I was not in debug mode so that's all I have.  It has done this before but it can take hours before it happens again so it might be difficult to capture debug.  Not sure how long I can run in debug mode before the log file stats getting unmanageably large. maybe I could reduce polling.

Anyway, just wanted to put this out there and see if anyone else was having this issue.
Thanks in advance to @itchannel and @SquidBytes for any help.

**Comment by mojomojoman** [comment]
ah wait. just realized that log is old. the timestamp is off. I guess I have no logs. Let's just put this on hold until I have some useful data to report I guess.

**Comment by teejaybugge** [comment]
Try to delete your vehicle and set it up again. I had the same issue after updating and that worked for me.

**Comment by SquidBytes** [comment]
We've had a few releases since this, I'm assuming you're not seeing this issue anymore?

**Comment by mojomojoman** [comment]
Nope.  It's been running great actually since I've been on 1.58-Release. Been busy and not checking but I see 1.60-Release is out now so maybe i'll jump to that. I'll close this issue though as I've no reason to suspect any issues will arise with 1.60.  Thanks for all the help.

**Comment by SquidBytes** [comment]
Well, if you haven't. I would either wait for 1.62, or grab the 1.61 latest beta.
I did add bugs in 1.61 
:/
