### ISSUE TITLE
fordpass_gps sensor is gone.

### ISSUE THREAD

**Issue by jwinston100** [itchannel/fordpass-ha#348]
I updated to the newest release, 1.57, and now my fordpass_gps sensor is gone. I have been using this is several automations.

**Comment by gniknalu** [comment]
I have always used `device_tracker.fordpass_tracker`

**Comment by itchannel** [comment]
Please use the device_tracker entity. It has all the same details as fordpass_gps just layed out a lot nicer. 

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/a26e5180-4050-4546-88c6-9f1d892ec292)

**Comment by jwinston100** [comment]
In my configuration.yaml, I created a template sensor from the GPS data and also a proximity sensor from that so that, for example, my garage door will open within a certain number of feet of my house when the tracker will still just say "Away".

**Comment by itchannel** [comment]
Yep so instead of using that sensor use the device tracker attributes it still has all the same details as the removed gps sensor. 

```
{{ state_attr("device_tracker.fordpass_tracker", "latitude") }}
{{ state_attr("device_tracker.fordpass_tracker", "longitude") }}
{{ state_attr("device_tracker.fordpass_tracker", "Altitude") }}
```

**Comment by gniknalu** [comment]
> In my configuration.yaml, I created a template sensor from the GPS data and also a proximity sensor from that so that, for example, my garage door will open within a certain number of feet of my house when the tracker will still just say "Away".

Yes! Please Share!

**Comment by jwinston100** [comment]
> Yep so instead of using that sensor use the device tracker attributes it still has all the same details as the removed gps sensor.
> 
> ```
> {{ state_attr("device_tracker.fordpass_tracker", "latitude") }}
> {{ state_attr("device_tracker.fordpass_tracker", "longitude") }}
> {{ state_attr("device_tracker.fordpass_tracker", "Altitude") }}
> ```
> 
> If you post your template code I'll happily edit it to work :)

I see. Thank you, itchannel, I didn't realize the GPS coordinates were also stored in the device tracker.

gniknalu, here is my proximity sensor for the vehicle:

`
proximity:
  ford_raptor_from_home:
    latitude: {{ state_attr("device_tracker.fordpass_tracker", "latitude") }}
    longitude: {{ state_attr("device_tracker.fordpass_tracker", "longitude") }}
    tolerance: 50
    unit_of_measurement: ft
`

**Comment by SquidBytes** [comment]
@jwinston100 I'm assuming this is completed by moving to the device_tracker?

**Comment by jwinston100** [comment]
Yes, I'll close it.
