### ISSUE TITLE
No devices/entities are created

### ISSUE THREAD

**Issue by gijsprins93** [itchannel/fordpass-ha#35]
I installed the FordPass integration from HACS and then from the HA integrations. Logged in and filled in my VIN. Yet it doesn't create any devices or entities. 24h has passed now, no errors, but also no entities.

Doesn't it work for my car then perhaps? (Ford Focus 2018 model)
The app on my phone works perfectly.

**Comment by itchannel** [comment]
What functionality to you have avaliable on your app. I believe that the latest API is for cars fitted with fords new modem which hasn't been out long. However I know America and Canada have had it longer than other regions. 

If you can look at your home assistant logs you should see "Failed to connect" or something similar can you check for me.

**Comment by pinballnewf** [comment]
@gijsprins93 , this is very likely due to issue #26  - I had the exact same problem when i first set this up.

**Comment by thisisbenwoo** [comment]
I am having a problem with my second VIN ...
My first one is fine. The second one (my wife's) has no devices or entities:
My car:
![image](https://user-images.githubusercontent.com/45885373/100486487-eb04ad00-30b8-11eb-934c-62e6dfd4664e.png)
My wife's car:
![image](https://user-images.githubusercontent.com/45885373/100486514-02439a80-30b9-11eb-8b2d-4c1c95d7431a.png)

**Comment by itchannel** [comment]
I'm guessing those are two seperate instances of the integration @thisisbenwoo . Are they using the same fordpass account or different?

**Comment by thisisbenwoo** [comment]
Yes..
[image: image.png]
Same account though...
Same email/password

---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by itchannel** [comment]
Can you post a screenshot of your log on startup of the integration so I can see any errors

**Comment by thisisbenwoo** [comment]
This repeats every few minutes:

2020-11-27 19:01:59 WARNING (MainThread) [custom_components.fordpass]
'vehiclestatus'
2020-11-27 19:01:59 WARNING (MainThread) [custom_components.fordpass] Error
communicating with FordPass for 1XX2X3XX4XXX56217
2020-11-27 19:01:59 ERROR (MainThread) [custom_components.fordpass] Error
fetching fordpass data: Error communicating with FordPass for
1XX2X3XX4XXX56217
2020-11-27 19:01:59 WARNING (MainThread) [homeassistant.config_entries]
Config entry for fordpass not ready yet. Retrying in 10 seconds
2020-11-27 19:01:59 WARNING (MainThread) [custom_components.fordpass] Error
communicating with FordPass for 3YY2Y3YY4YYY56670
2020-11-27 19:01:59 ERROR (MainThread) [custom_components.fordpass] Error
fetching fordpass data: Error communicating with FordPass for
3YY2Y3YY4YYY56670

Now none of my entities for my car are no longer valid :-(
[image: image.png]



---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by itchannel** [comment]
@thisisbenwoo please try the new update 1.0.7 which should fix the expiring entities as that was a known issue #26 . However the multiple can one I will need to look into and work out how I can add support for 2 cars.

**Comment by JanEsders** [comment]
Just updated to 1.0.7 from 1.0.6 (worked fine before, just with the issue of entities becoming unavailable after a few hours). Didn't find a setting to set the region afterwards so deleted the Integration and added my car again with region UK/Europe (living in Germany) but no entities are created for hours now

**Comment by itchannel** [comment]
Can you check your HA log please and let me know if you have any errors

**Comment by JanEsders** [comment]
I would, but today everything works fine. Until now, no "unavailable" as well.

Good work, really love this integration!

**Comment by itchannel** [comment]
Awesome, may have just taken a while to refresh your token.
