### ISSUE TITLE
Return old data if API update fails

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#355]
API seems a little unstable causing blips of the sensors going unavailable. Simple fix is to return the previous data if the API fails. 

Will still log a warning in HA, but sensors won't show unavailable

**Comment by szeberli** [comment]
I have the same problem

**Comment by itchannel** [comment]
Does yours go unavailable for the 15mins before it refreshes and works again? Or doesn't come back at all? @szeberli

**Comment by szeberli** [comment]
No sensors are restored.  The sensors remain set to unavailable

![image](https://github.com/itchannel/fordpass-ha/assets/10152825/af32ca49-85ad-401a-9d75-e55d2cf4b7ec)

**Comment by itchannel** [comment]
Can you please check your HA logs for any errors generated.

Do you have to restart your HA to get them to update again?

**Comment by pbryan7** [comment]
Mine always recovers itself without need for restart...  so far, always on the very next attempt (900s later).   

It has happened to me 33 times in the last ~24 hours, always with this log warning:

WARNING (MainThread) [custom_components.fordpass] No connection adapters were found for 'fordapp://userauthorized?code=xxxxxxxxxxxxxxxxxx'

**Comment by dmkjr** [comment]
@itchannel Could you post a quick instruction set on how to pull the information from our vehicles?  I can provide the output from my Ford vehicles, including some EV's.

**Comment by itchannel** [comment]
Fixed in 1.58. 

@dmkjr please see https://github.com/itchannel/fordpass-ha/wiki/AutonomicData-Tutorial for details on grabbing data.

**Comment by dmkjr** [comment]
@itchannel Thank you.  I have pulled my vehicle data.  Where do you want me to put it?  2017 F150 Lariat FX4.
