### ISSUE TITLE
Items become unavailable 

### ISSUE THREAD

**Issue by Gadget111** [itchannel/fordpass-ha#36]
Installs, and works perfectly. However after an hour or so all item become unavailable. Calling the refresh service does not bring them back. Removing the device and re adding works.

**Comment by petheridge** [comment]
@Gadget111 Issue captured in #26, should be fixed in a day or so.

**Comment by TRusselo** [comment]
duplicate https://github.com/itchannel/fordpass-ha/issues/26

**Comment by itchannel** [comment]
This should have been resolved in 1.0.7. However if it still persists please use issue #26 as mentioned
