### ISSUE TITLE
FordPass stopped working … Auto_Token

### ISSUE THREAD

**Issue by AlexW75** [itchannel/fordpass-ha#360]
After the last update the integration was working perfect.
Some hours ago it stopped working - everything is not available.
I can just find the error Auto_Token.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:227
Integration: FordPass (documentation, issues)
First occurred: 20:37:24 (14 occurrences)
Last logged: 20:46:27

'auto_token'

**Comment by itchannel** [comment]
I've got the exact same issue on my prod instance. I believe I know why look like the auto API had a wobbly which resulted in the token being missing in the token file so when the code reads it, it returns an error.

**Comment by AlexW75** [comment]
Took the changes in.
Everything is working :)

Thanks

**Comment by itchannel** [comment]
Fixed in 1.58 Release
