### ISSUE TITLE
Last Refresh time is messed up

### ISSUE THREAD

**Issue by Jeppedy** [itchannel/fordpass-ha#363]
I refreshed just now, and the "Last Refresh" time says "In 3 hours..."
And the time seems to be 4 hours off.  
I'm in Central timezone.
![Screenshot 2023-10-14 181541](https://github.com/itchannel/fordpass-ha/assets/7842787/0360a476-64f4-4863-8eb7-002af51e7761)

**Comment by itchannel** [comment]
See #338 it's a known issue with HA not showing the time zone in the UI. Hoping they fix it soon

**Comment by Jeppedy** [comment]
Seems to be related to underlying issue https://github.com/home-assistant/core/issues/101371#issue-1925612889
