### ISSUE TITLE
Feature request EV mi/kWh

### ISSUE THREAD

**Issue by SquidBytes** [itchannel/fordpass-ha#365]
EVs fuel economy is measured in mi/kWh
I'd love to be able to either calculate that data, or grab it.
Initial look I didn't see any specific keys, but might be able to be calculated.

**Comment by dmkjr** [comment]
Not sure you will need to do this calculation, right?  Shouldn't the vehicle report the estimated mileage into the Fordpass application?  If that is the case, they have an object that is reporting the calculation the vehicle is doing in real time *(but probably not reported in real time).

**Comment by SquidBytes** [comment]
From a quick look around the json files I have (EV and non EV)
Under events Newer EV's contain

`xev-key-off-trip-segment-data`

which then has has
```
"trip_data": {
    "stringArrayValue": [
        "{\"time_segment_block_id\":28.0,\"ambient_temperature\":28.5,\"outside_air_ambient_temperature\":28.5,\"trip_duration\":979.0,\"cabin_temperature\":30.0,\"energy_consumed\":1918.0,\"distance_traveled\":12.0}"
    ]
}
```

This could be used for a new sensor to output data like this

Time: 28.0
Ambient Temperature: 83
Outside Ambient Temperature: 83
Cabin Temperature: 86
Distance Traveled: 7 miles
Miles per kWh: 3.89 mi/kWh
Trip Duration: 979.0
Energy Consumed: 1918.0 kW

Still looking into it, and trying to figure out what specific values are before making any code changes.
Want to make sure I don't just add it in and introduce more bugs.

And I would want to make it so it would only populate if its supported, since I did recently introduce the bug in issue #334

**Comment by SquidBytes** [comment]
ec92478225b77e2fecd5521bc78e478666d94d7a

**Comment by SquidBytes** [comment]
Implemented, but possibility of improvement.
See #409 
Closing this one.
