### ISSUE TITLE
Possible to add a sensor that will reconize when the car`s wifi is connnected to the home ssid ?

### ISSUE THREAD

**Issue by doronazl** [itchannel/fordpass-ha#366]
would be great as a "home" sensor rather than going by gps

**Comment by SquidBytes** [comment]
I took a look through the json data I have.
The only thing I see related to some type of connection is 
`        "deviceConnectivity": {
            "timestamp": "2023-10-13T13:12:55Z",
            "value": {
                "toState": "CONNECTED"
            }
`

I only have a few jsons with the `toState` being `CONNECTED`
One of which is while my vehicle is is in Drive. I would highly assume this `deviceConnectivity` is not related to the vehicle being connected to Wi-Fi and relates to connected to the API or something else.

There is a `bluetoothPhoneSystemStatus` but that is not something easy to rely upon.

For a "home" sensor, it's probably best to continue using the Vehicles GPS
For more accurate home arrival I would recommend using your Phone's GPS, and phone connections/disconnections.
So if your phone arrives home, and disconnects from Android Auto or something - then its a good assumption you're home.

**Comment by Lanstrom** [comment]
You could also have a look to see if your home network has an integration to HA.  I use Ubiquiti Unifi equipment and when the car connects to the WiFi it registers me as Home.

**Comment by bryangalaz** [comment]
You could set up a static IP for it on your router and then set up a sensor that pings that IP, when that IP pings back your connected.

**Comment by SquidBytes** [comment]
Closing as this probably isn't possible, and depending on various setups there is probably a better way to detect. Feel free to open a new issue or requests.
