### ISSUE TITLE
Fuel level shows negative number after car off

### ISSUE THREAD

**Issue by emile-bodin** [itchannel/fordpass-ha#37]
Hi ,

Great integration.
I am testing it and found that when the car is turned off, the fuel level drops to a negative number.

![IMG_20201127_180724](https://user-images.githubusercontent.com/2363359/100471878-7858f900-30db-11eb-97f2-89837a2ba254.jpg)

Initially is thought it was because the sensors became unavailable, but after calling the fordpass.refresh_status or refreshing via the ford app the status remains like that.

After the car is started it show a correct value.

**Comment by petheridge** [comment]
@emile-bodin Does the fuel gauge in your FordPass App reflect an empty tank when you vehicle is off? -5% to 105% is the range the vehicle reports. It's odd that it's actively reporting empty when off. I have not had this issue.

**Comment by emile-bodin** [comment]
I am using 2 separate apps, "FordPass" and "FordPass Pro"
I  the first one there is no fuel information at all, in the pro version the fuel status is "Information not available" 

So it seems its somthing that the ford api sends when the car is off.

Might be an idea to "remember" last fuel state, instead of reporting the "information not available" state

**Comment by itchannel** [comment]
Could you please provide me the following information because as  @petheridge says I also don't have this issue and the car returns the correct fuel amount with the engine off. 
* Application Region
* Version of app used
* model year and model of the car

**Comment by emile-bodin** [comment]
There were a bunch of communication issues, after applying the code change to reflect Europe and a sync via HA when my car was turned on and the fuel % was shown correctly, and most importantly it stayed ;)

I have upgraded to the newest release and readded the integration (after deleting the tokes) and resynced the status with the car turned on.

Have not seen the issues again.
I think the ticket can be closed.

Thanks!

**Comment by itchannel** [comment]
Glad to hear it's working for you 👍

**Comment by Banzarykey** [comment]
I seem to bet getting this same issue with 1.10

fuelLevel: -5.217408
distanceToEmpty: 246.8
status: CURRENT
timestamp: '12-15-2020 13:17:10'
unit_of_measurement: '%'
friendly_name: fordpass_fuel
icon: 'mdi:gas-station'
