### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by SquidBytes** [itchannel/fordpass-ha#374]
While adding changing elVehCharging time to match other items like last_refresh etc
I noticed the time is being converted incorrectly.

The json data says Z time, but it also appears to be local in some areas, or we are converting it incorrectly somewhere - or twice.

All the sensors using date-time are incorrect according to my local time.

Current Local Time: October 16, 2023, 2:30 PM

![image](https://github.com/itchannel/fordpass-ha/assets/145411069/b5f75989-cc11-401a-b1e8-941d86683e8e)

I'll have to look into this later when I have time, or @itchannel if you're able.

**Comment by itchannel** [comment]
See #338 it's an issue with HA and not displaying the time in the local timezone

**Comment by cpw** [comment]
I've dug into this, and it's not HA mis-displaying the time. The time is offset by a weird amount. It seems like it's doubling the zone offset and then reporting itself as UTC.
The time is currently 10:13 local time - or 14:13 UTC. It's definitely NOT 18:13 UTC. Note that the datatype is string here as well.

![image](https://github.com/itchannel/fordpass-ha/assets/1217211/4f5a46be-4749-4b67-9eea-ffa815ad6562)

**Comment by mclever** [comment]
Mine shows
2023-10-19T21:34:58+00:00
When local time is 7:34. 

Time zone: Pacific Time UTC -7

**Comment by SquidBytes** [comment]
I believe I have fixed this. So it shouldn't be an issue in future releases.
1ddc3440fe40ccf1faefe0790a150922044b73c0
