### ISSUE TITLE
1.58-beta1: OutsideTemp and CoolantTemp C is actually reporting F

### ISSUE THREAD

**Issue by mojomojoman** [itchannel/fordpass-ha#378]
I believe this bug was introduced in 1.58 beta 1 and was not in the 1.57 release. 
If I set the OutsideTemp unit to C then it reports F and if I set it to F it reports a twice converted F.

It is not 115 F in my Garage:
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/26dfd4eb-ce68-448d-adf6-0107cabab10b)

If I change the unit of measurement to C then I get the correct F value:
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/c3e28258-295d-4472-a882-178257b3941d)

I notice the same behavior with coolantTemp...
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/84dbfeaf-fcb3-4b80-b03f-4f147f1e1704)
![image](https://github.com/itchannel/fordpass-ha/assets/67213346/e5b15fcf-4f8a-4343-b762-ffcf15d9011d)

However this is an EV, I dont believe I even have engine coolant so I'm not sure what that's reporting but it's 46 F outside right now so nothing should be that hot.

Haven't found any other temp sensors that are off but if I find any I'll update this thread.

Thanks!

**Comment by itchannel** [comment]
So I've changed the system to use HA native conversion. 

Can you run the autonomics.py script or check your logs and just tell me what those temperature values say in the json. Need to see if the API reports back C or F for your vehicle.

**Comment by mojomojoman** [comment]
Sure thing....  okay. I just did a double take and ran it twice to be sure but the raw value i'm getting for that is 7.25???
I cant even explain this. HA is still reporting the "correct" value. I mean besides the already stated conversion issue.

![image](https://github.com/itchannel/fordpass-ha/assets/67213346/5d0060d2-ec24-4b09-b039-bbeb78f81a53)

[mojomojoman_status_2023-10-18_00_17_06.zip](https://github.com/itchannel/fordpass-ha/files/12985489/mojomojoman_status_2023-10-18_00_17_06.zip)

I have a zwave motion detector/temp sensor in the garage reporting 58.7 F currently.

**Comment by itchannel** [comment]
So the API is responding in C which is what I'd expect. 

The code literally just returns the value to the sensor now:

```
return self.data["engineCoolantTemp"]["value"]
```

So I have no idea where your HA instance is getting these crazy values from. Can you just post the contents of sensor.py here for me. Just so I can compare the code to my current version, not that I'm expecting any changes in it.

**Comment by SquidBytes** [comment]
This should be fixed in 1.58 Release

**Comment by SquidBytes** [comment]
Hey @mojomojoman, just wanted to confirm you're not still having this issues.

**Comment by mojomojoman** [comment]
Nope. This issue is fixed.  Thanks!
