### ISSUE TITLE
HA Cloud - Entity exposure

### ISSUE THREAD

**Issue by thisisbenwoo** [itchannel/fordpass-ha#38]
Just coming back to playing with the integration. One thing I immediately noticed was that when I go to Configuration | Home Assistant Cloud | Alexa | Managed Entities, the following shows up:

![image](https://user-images.githubusercontent.com/45885373/100485959-ec34da80-30b6-11eb-8671-52ed393cf004.png)
![image](https://user-images.githubusercontent.com/45885373/100485973-f6ef6f80-30b6-11eb-97d8-65a27b6de452.png)

In the photos above, I've actually marked these to be removed from being exposed to Alexa. (I haven't looked at Google Home/Assistant, but I imagine it'll be the same). To me, to have the ability to start and unlock a car once it is integrated can be unsafe and insecure. Not sure if it is possible to default not to expose, but thought it is worth bringing up.

b

**Comment by petheridge** [comment]
Good point. Although it does appear (on Alexa) to be disabled on app and by voice by default. 

![image](https://user-images.githubusercontent.com/30731128/100487601-6d18c400-3101-11eb-94f8-2118ba45adc4.png)

**Comment by thisisbenwoo** [comment]
The default action of the FordPass skill in Alexa is to require a PIN. So
that might be something you consider.

---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by itchannel** [comment]
So I agree it can be a security issue, however it used the lock type entity for door locks which will automaticly follow the Alex or Google security perms you have setup. It's not something I can set from the integration that I'm aware of.

**Comment by thisisbenwoo** [comment]
NP.. I wasn't sure if it was something programmable or not. Thanks. Can
close this now.

---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by itchannel** [comment]
Was worth a check.
