### ISSUE TITLE
Integration failing to reload 

### ISSUE THREAD

**Issue by AlteVerwischteZiege** [itchannel/fordpass-ha#380]
Was all good until yesterday evening.

Receiving the following in the system log:

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:322
Integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: October 17, 2023 at 18:37:21 (620 occurrences)
Last logged: 08:09:34

Error fetching fordpass data: Error communicating with FordPass for MyVIN

Any thoughts on where to begin?

**Comment by notmayo** [comment]
Getting the same now with no changes to my environment, latest HA versions. It seems Ford changed something?

**Comment by Hobjersgarden** [comment]
updated to 1.58 /hacs and try reinstall : Fel
Konfigurationsflödet kunde inte laddas: {"message":"Invalid handler specified"}

**Comment by itchannel** [comment]
Issue Resolved
