### ISSUE TITLE
Cannot Generate Unique IDs

### ISSUE THREAD

**Issue by navarrolux** [itchannel/fordpass-ha#381]
Hello,
Is anyone else seeing this issue?
This prevents the unlock start and other commands from working.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 8:48:52 AM (18 occurrences)
Last logged: 8:48:54 AM

Platform fordpass does not generate unique IDs. ID VIN#-fordpass_outsideTemp already exists - ignoring sensor.fordpass_outsidetemp
Platform fordpass does not generate unique IDs. ID VIN#-fordpass_remoteStartStatus already exists - ignoring sensor.fordpass_remotestartstatus
Platform fordpass does not generate unique IDs. ID VIN#-fordpass_messages already exists - ignoring sensor.fordpass_messages
Platform fordpass does not generate unique IDs. ID VIN#-fordpass_dieselSystemStatus already exists - ignoring sensor.fordpass_dieselsystemstatus
Platform fordpass does not generate unique IDs. ID VIN#-fordpass_odometer already exists - ignoring sensor.fordpass_odometer

**Comment by navarrolux** [comment]
To help, my instance has the following versions
1.58-Beta 1 of FordPass And

Home Assistant 2023.10.3
Supervisor 2023.10.0

**Comment by itchannel** [comment]
Restarting your HA should fix this error.

**Comment by navarrolux** [comment]
> Restarting your HA should fix this error.

Thank you!
