### ISSUE TITLE
reinstall 1.58 fault

### ISSUE THREAD

**Issue by Hobjersgarden** [itchannel/fordpass-ha#382]
reinstall 1.58 /hacs dont work

Fel
Konfigurationsflödet kunde inte laddas: {"message":"Invalid handler specified"}

**Comment by itchannel** [comment]
Are you running version 1.58 from hacs? As this error exists in the 1.59 branch but that's not officially out yet.

**Comment by Hobjersgarden** [comment]
I tryed 1.59 first so maybe this is the problem

**Comment by itchannel** [comment]
I have fixed the error now in 1.59 but I'd recommend sticking with 1.58 until I've fully tested for bugs.

**Comment by Hobjersgarden** [comment]
I install 1.59 now and it works perfect. 

tanks for a good work ;0)

**Comment by Hobjersgarden** [comment]
works now
