### ISSUE TITLE
Locking when DOUBLE_LOCKED

### ISSUE THREAD

**Issue by DeputyJones** [itchannel/fordpass-ha#383]
I wanted to hopefully add some helpful troubleshooting info to some of the previous messages about issues with locking and unlocking. Apologies if it is already known.

After updating to 1.58, I was still not able to get locking and unlocking working and the status was always incorrect. I finally worked out how to interrogate the sensor info and logs and noticed the DOUBLE_LOCKED status. I then realised/remembered that I automatically double click the lock button on my remote to engage the deadlocks. I tested just clicking the remote once (normal locks) and hooray, everything works correctly in HA.

The FordPass app works correctly regardless of whether the vehicle is double or single locked so I'm not sure if that can be tweaked for HA?

Thanks for all the work with this integration.

**Comment by itchannel** [comment]
Thanks for the feedback, I didn't even realise double locking existed as a status. Definitely something I can add to the 1.59 release.

**Comment by itchannel** [comment]
Fixed in 1.59
