### ISSUE TITLE
Check doorLockStatus exists in API before adding door lock entity

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#388]
```
if lock.coordinator.data["metrics"]["doorLockStatus"] and lock.coordinator.data["metrics"]["doorLockStatus"][0]["value"] != "ERROR":
        async_add_entities([lock], False)
```

Current code doesn't check "doorLockStatus" exists before adding.

**Comment by itchannel** [comment]
#393 Need to slightly modify this code to do a .get in case the value is null but otherwise a good merge I will add later today :)

**Comment by sarangcr03** [comment]
#393 updated to handle potential null values using .get
