### ISSUE TITLE
Wrong oil status

### ISSUE THREAD

**Issue by Lux315** [itchannel/fordpass-ha#390]
the 'sensor.fordpass_oil' gets wrong data for me.

Right now it says 6% oil but theres actually 60%-70% oil in the car.

What could be the issue for that?

**Comment by itchannel** [comment]
The Integration and Fordpass applications return "oilLifeRemaining" not the actual amount of Oil in the car. So the % value you see is basically a countdown until your Oil needs changing rather than the amount of Oil in the car.

**Comment by SquidBytes** [comment]
Closing as itchannel has explained what this value is.
Feel free to re-open or open a new issue if you are having any issues.
