### ISSUE TITLE
[Feat. Req.] MDI icons / Better names

### ISSUE THREAD

**Issue by TRusselo** [itchannel/fordpass-ha#40]
Ford Door Lock
mdi:car-door-lock

Ford Window Position
mdi:car-door

Ford Starter
mdi:key-star

Ford Ignition Status
mdi:key

Ford Last Update
mdi:clock

Ford Odometer
mdi:gauge

Ford Doors
mdi:car-door

Ford Fuel Level
mdi:fuel

Ford Oil Life
mdi:oil

Ford Battery
mdi:car-battery

Ford Tire Pressure
mdi:car-tire-alert

Ford Alarm
mdi:bell

Ford Tracker
mdi:radar

Ford GPS
mdi:radar

**Comment by TRusselo** [comment]
![image](https://user-images.githubusercontent.com/1154815/100493890-2626d080-30f9-11eb-8b35-93ec18d30e0e.png)

**Comment by itchannel** [comment]
Icons are a good shout and will add them to the next release.  Naming wise I had issues seting proper names which caused the entity ID's to be set as the name which was weird. When I have 5 I'll look into that again

**Comment by petheridge** [comment]
@TRusselo good shout on icons. Just been having a look on mdi and wonder if these for odometer and fuel could be more intuitive? 

Ford Odometer
mdi:counter

Ford Fuel Level
mdi:gas-station

![image](https://user-images.githubusercontent.com/30731128/100499150-29ed3e00-315f-11eb-939d-4a23afc64ac6.jpeg)

**Comment by TRusselo** [comment]
ooohh sweet those are better choices.

**Comment by ObiKaiKenobi** [comment]
And for cars with remote start feature:

```
entity: switch.fordpass_ignition_switch
name: (Ford) Remote Start
icon: hass:power
```

**Comment by itchannel** [comment]
New icons have been added in #51
