### ISSUE TITLE
elveh and odometer broken

### ISSUE THREAD

**Issue by frankie-boy-hgv** [itchannel/fordpass-ha#402]
Hi,

1.60 broke my elveh and odometer entities :-(.
Edit:1.59 also broke it.
 
Got an error:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 450, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 248, in get_value
    if batt_volt != 0 and batt_amps != 0:
       ^^^^^^^^^
UnboundLocalError: cannot access local variable 'batt_volt' where it is not associated with a value

Not sure if it has something to do with it.

Regards,

Frank

**Comment by crowedavid** [comment]
seeing elveh and odometer broken for me on 1.60 as well but with different errors:

> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:507
> Integration: Sensor (documentation, issues)
> First occurred: 11:45:57 AM (2 occurrences)
> Last logged: 11:56:22 AM
> 
> Error adding entities for domain sensor with platform fordpass
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
>     state, attr = self._async_generate_attributes()
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
>     attr.update(self.extra_state_attributes or {})
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/fordpass/sensor.py", line 450, in extra_state_attributes
>     return self.get_value("attribute")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/fordpass/sensor.py", line 292, in get_value
>     elecs["Trip Efficiency"] = elecs["Trip Distance Traveled"] / elecs["Trip Energy Consumed"]
>                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ZeroDivisionError: float division by zero
>

**Comment by sarangcr03** [comment]
> Hi,
> 
> 1.60 broke my elveh and odometer entities :-(. Edit:1.59 also broke it.
> 
> Got an error: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state state, attr = self._async_generate_attributes() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes attr.update(self.extra_state_attributes or {}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/fordpass/sensor.py", line 450, in extra_state_attributes return self.get_value("attribute") ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/fordpass/sensor.py", line 248, in get_value if batt_volt != 0 and batt_amps != 0: ^^^^^^^^^ UnboundLocalError: cannot access local variable 'batt_volt' where it is not associated with a value
> 
> Not sure if it has something to do with it.
> 
> Regards,
> 
> Frank

2 possible fixes : 
1. initialize both batt_volt and batt_amps to a default value before the conditional checks
2. directly check and compute the value within the conditions. 
```python
if "xevBatteryVoltage" in self.data and "xevBatteryIoCurrent" in self.data:
    batt_volt = float(self.data.get("xevBatteryVoltage", {}).get("value", 0))
    batt_amps = float(self.data.get("xevBatteryIoCurrent", {}).get("value", 0))
    
    elecs["Battery Voltage"] = batt_volt
    elecs["Battery Amperage"] = batt_amps
    
    if batt_volt != 0 and batt_amps != 0:
        elecs["Battery kW"] = round((batt_volt * batt_amps) / 1000, 2)

**Comment by sarangcr03** [comment]
> seeing elveh and odometer broken for me on 1.60 as well but with different errors:
> 
> > Logger: homeassistant.components.sensor
> > Source: helpers/entity_platform.py:507
> > Integration: Sensor (documentation, issues)
> > First occurred: 11:45:57 AM (2 occurrences)
> > Last logged: 11:56:22 AM
> > Error adding entities for domain sensor with platform fordpass
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
> > await asyncio.gather(*tasks)
> > File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
> > await entity.add_to_platform_finish()
> > File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
> > self.async_write_ha_state()
> > File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
> > self._async_write_ha_state()
> > File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
> > state, attr = self._async_generate_attributes()
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
> > attr.update(self.extra_state_attributes or {})
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/fordpass/sensor.py", line 450, in extra_state_attributes
> > return self.get_value("attribute")
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/fordpass/sensor.py", line 292, in get_value
> > elecs["Trip Efficiency"] = elecs["Trip Distance Traveled"] / elecs["Trip Energy Consumed"]
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > ZeroDivisionError: float division by zero

possible fix is to add an additional check to ensure elecs["Trip Energy Consumed"] is not zero

**Comment by itchannel** [comment]
@frankie-boy-hgv @crowedavid Can you please give 1.61 Beta a go

**Comment by crowedavid** [comment]
> @frankie-boy-hgv @crowedavid Can you please give 1.61 Beta a go

that works well.  👍

**Comment by frankie-boy-hgv** [comment]
> @frankie-boy-hgv @crowedavid Can you please give 1.61 Beta a go

Didn't fix it for me 😞

**Comment by itchannel** [comment]
@frankie-boy-hgv Can you provide me with any errors in the logs.

**Comment by frankie-boy-hgv** [comment]
> @frankie-boy-hgv Can you provide me with any errors in the logs.

Of course. I have 2 error messages:
1)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor (documentation, issues)
First occurred: 08:59:35 (1 occurrences)
Last logged: 08:59:35

Error while setting up fordpass platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 189, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.fordpass_fuel cannot be added a second time to an entity platform

2)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: 08:59:40 (1 occurrences)
Last logged: 08:59:40

fordpass: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 507, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 240, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 467, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 262, in get_value
    if batt_volt != 0 and batt_amps != 0:
       ^^^^^^^^^
UnboundLocalError: cannot access local variable 'batt_volt' where it is not associated with a value

**Comment by itchannel** [comment]
@frankie-boy-hgv Please give 1.61 Beta 3 a go.

**Comment by frankie-boy-hgv** [comment]
> @frankie-boy-hgv Please give 1.61 Beta 3 a go.

Yep, working again!

**Comment by SquidBytes** [comment]
@Jeppedy Can you double check you are running 1.61 Beta 3, and have restarted after installing; this should be fixed, and the line it is referencing `248` is incorrect if its the Beta 3 build.

**Comment by Jeppedy** [comment]
My apologies. It does seem to be working now. Although, I don't have a
value for the battery voltage but it doesn't return an error.

**Comment by tledford** [comment]
I got the same error as @crowedavid for the elVeh sensor:
```
File "/config/custom_components/fordpass/sensor.py", line 292, in get_value
    elecs["Trip Efficiency"] = elecs["Trip Distance Traveled"] / elecs["Trip Energy Consumed"]
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```
This happened when I started my Lightning but didn't drive anywhere, hence the 0 kWh consumed. Here's my Autonomic data: [my_status_2023-10-23_19_46_14_REDACTED.json](https://github.com/itchannel/fordpass-ha/files/13172329/my_status_2023-10-23_19_46_14_REDACTED.json)

Lastly, a huge thanks to @itchannel and @SquidBytes for your hard work on this integration.

**Comment by SquidBytes** [comment]
When I changed all the EV items over to using a different method to get the data, I also added bugs :/ It was late, and I've been swamped at work, so I missed some spots. I added conversions in the code for kW, which inadvertently added bugs by not checking for the values before conversions.

In the future I plan on integrating a better to way to detect for EV's, and their values, which should remove these issues. And hopefully bypassing code conversions and handing that off to HA to do. Just need some time to work on it.

Apologies for the problems.

This should be fixed soon, for now you can comment that section out and it should work.

**Comment by SquidBytes** [comment]
> I got the same error as @crowedavid for the elVeh sensor:
> 
> ```
> File "/config/custom_components/fordpass/sensor.py", line 292, in get_value
>     elecs["Trip Efficiency"] = elecs["Trip Distance Traveled"] / elecs["Trip Energy Consumed"]
>                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ZeroDivisionError: float division by zero
> ```
> 
> This happened when I started my Lightning but didn't drive anywhere, hence the 0 kWh consumed. Here's my Autonomic data: [my_status_2023-10-23_19_46_14_REDACTED.json](https://github.com/itchannel/fordpass-ha/files/13172329/my_status_2023-10-23_19_46_14_REDACTED.json)
> 
> Lastly, a huge thanks to @itchannel and @SquidBytes for your hard work on this integration.

That should be fixed in Beta3, and the fix will be in the next release.
