### ISSUE TITLE
Refresh data triggers remote start

### ISSUE THREAD

**Issue by reddok69** [itchannel/fordpass-ha#408]
As of 1.60 refresh of data triggers remote start on EV.

**Comment by michalk-k** [comment]
I'm not sure if it's related, but on my end, the remote start switch is stuck in the enabled position.
In the evening refresh didn't turn it off. Also, an attempt to switch it off and then on manually did not start the vehicle.

At the time I'm writing this message (afternoon) I reissued refresh and the switch turned back to off.

**Comment by itchannel** [comment]
@SquidBytes Have you received any of these symptoms with your electric vehicle? I can't diagnose as I only have petrol cars :)

**Comment by SquidBytes** [comment]
I have not seen anything like this.

However, I don't use the refresh service.

**Comment by reddok69** [comment]
Still not working.  If the ignition switch is turned on, it stays on even though the ignition state stays off.

Also do not have the switch entity to lock the doors anymore.  This used to function.

**Comment by reddok69** [comment]
Updating my Ford Sync from 3.4.22200 to 3.4.23188 seems to have resolved this issue for me.
