### ISSUE TITLE
Lincoln support?

### ISSUE THREAD

**Issue by jofotoo** [itchannel/fordpass-ha#411]
Hi all,

I'm seeing references to using this with Lincolns. How is this accomplished?  I can't add a Lincoln to my FordPass account, and if i try to use LincolnMyWay credentials, it tells me i have no vehicles to add.  Strangely, I think one time it showed my Ford's VIN when I was using the Lincoln creds....Email address is the same.

So, what's the word on how this would work?

**Comment by SquidBytes** [comment]
It is being looked into.
#344

**Comment by itchannel** [comment]
Closing as duplicate to #344
