### ISSUE TITLE
Wrong battery level

### ISSUE THREAD

**Issue by Donni1966** [itchannel/fordpass-ha#413]
Hi, 
i have a Mustang mach e - model from 2023.  There is a Batteriy Level, but ich think 20% less than reality. 
if it fully loaded, the HA say
at the moment of the screenshot the level in the ford app is 100: 
![Bildschirmfoto 2023-10-27 um 19 34 21](https://github.com/itchannel/fordpass-ha/assets/61660957/baccda4e-0823-48dd-9609-c9eef449614e)

any idea what the reason for? 

byby, Michael

**Comment by crowedavid** [comment]
the fordpass_battery sensor tracks the LV (12v) battery, not the HV battery, state of charge.  the HV battery is the "Battery Charge" attribute of the fordpass_elVeh sensor.

**Comment by Donni1966** [comment]
Thanx a lot.
