### ISSUE TITLE
Request:  Don't make "Charging kW" disappear when not charging.

### ISSUE THREAD

**Issue by mojomojoman** [itchannel/fordpass-ha#414]
My vote is definitely not to remove the state attrib but to zero it when not charging Amps or Volts input (which I think it will do organically given the maths would come out to zero anyway).

```
    # This will make Charging kW not display if vehicle is not charging. Not sure if that is bad practice by having it pop in and out
    if "xevBatteryChargerVoltageOutput" in self.data and "xevBatteryChargerCurrentOutput" in self.data:
        if ch_volt != 0 and ch_amps != 0:
            cs["Charging kW"] = round((ch_volt * ch_amps) / 1000, 2)
```

Mainly because I break out some of these state attribs into their own template sensors.  It's easier to use on cards and you can look at graphs, etc but those don't expect strings when you've set them to a specific type or if you've used a gauge card or whatever. Not a huge deal but just produces errors in the UI if i have it in a card.

**Comment by itchannel** [comment]
It was added to prevent a division by zero error, but this can be changed to return 0 instead.

**Comment by mojomojoman** [comment]
Interesting. I never get the div/0 error even when it was added before and showing up all the time.  Or maybe it only shows in the logs and I missed it.  Regardless, thanks for the PR!
