### ISSUE TITLE
F-150 Lighting Battery Level

### ISSUE THREAD

**Issue by chester512** [itchannel/fordpass-ha#415]
Hi, How do I determine the charge level of my EV battery?  There is a "fordpass battery" entity, but that is 12V battery? The "fuel" entity stays at zero.

**Comment by itchannel** [comment]
Can you please do the following and provide me a copy of your vehicles json output so I can see if your missing the xevbattery value. 

https://github.com/itchannel/fordpass-ha/wiki/AutonomicData-Tutorial

**Comment by SquidBytes** [comment]
I didn't notice the fuel sensor being odd for EV's.
I generally use the elVeh sensor.

Its a bug with how the fuel sensor is returned.
Working on it now, should be fixed in next release.

**Comment by chester512** [comment]
Thank you for the response and update.  Appreciate all the work you have
put into this integration.
