### ISSUE TITLE
Question about battery level

### ISSUE THREAD

**Issue by ilbeppe83** [itchannel/fordpass-ha#420]
Hi,
I have a Mild Hybrid Puma and on the new itegration I can see a % level on the sensor fordpass_battery in addition to the voltage.

Do you know if that % value is related to 12v battery (as the voltage value seems to be) or to the 48v hybrid battery?

Thank you for all your work on this itegration.

**Comment by SquidBytes** [comment]
The `fordpass_battery` sensor is mapped to the vehicles low voltage (12v) battery.

For EV specific information, if your vehicle supports it, it will be mapped under the `fordpass_elVeh` sensor.

If you're having difficulty with that sensor displaying - it is either a known bug in 1.60 Release and I would recommend grabbing 1.60 Beta3.

And/or please provide your vehicles json data

**Comment by ilbeppe83** [comment]
Thank you for your answer.

I do not have difficulty with that sensor, my question is just to understand better this new value appeared right after the new API modifications. The % value changes when driving, so I was supposing that this was related to the status of charge of the hybrid battery.

I do not have EV sensors as my vehicle is only a mild hybrid car.

**Comment by SquidBytes** [comment]
Battery % should be your low voltage battery.
Fuel, currently, is only your fuel tank value

The "EV" sensors aren't specific to EV only. They should still have some information for Hybrid vehicles.

I changed a bit of the `fordpass_fuel` sensor that should display both the Fuel Range and Battery Range for Hybrids. That should be in the next release.

Without knowing your vehicles specific data I won't be able to know if some values are different for you, I only have my data to go off of.
https://github.com/itchannel/fordpass-ha/wiki/AutonomicData-Tutorial
