### ISSUE TITLE
Ford Pass Ford Fusion Hybrid (2018) no tire pressure anymore?

### ISSUE THREAD

**Issue by BostonDanPhD** [itchannel/fordpass-ha#422]
Fordpass use to have the tire pressure for this vehicle, but for a few versions (not certain which version it was when this issue started), the tire pressure sensor does not show up. I have checked the sensors in Home Assistant (including hidden and disabled entities) and it is no longer on this vehicle. Any way to get this back, or understand why this disappeared?

**Comment by itchannel** [comment]
It sounds like the new API isn't providing the tire pressure status for your vehicle or the endpoint it used has moved/changed. 

If you can follow the below tutorial and provide me with the output I can check to see if your vehicle supports tire pressure in the latest Fordpass API update. 

https://github.com/itchannel/fordpass-ha/wiki/AutonomicData-Tutorial

**Comment by itchannel** [comment]
Closing as no data provided so can't diagnose further.
