### ISSUE TITLE
Fordpass platform does not generate unique IDs

### ISSUE THREAD

**Issue by itsredan97** [itchannel/fordpass-ha#429]
Hi all,

I'm using Fordpass integration for HA from yesterday and I noticed that isn't updating data in my dashbord unless I keep removing-adding my car to the integration, looks like it isn't able to ping API or the car to get the data, so i made an automation calling refresh_status service to try to fix that issue but keeps not updating.

I checked errors from the logs and this error came up:

```
Platform fordpass does not generate unique IDs. ID W****102-fordpass_doorlock already exists - ignoring lock.fordpass_doorlock
Platform fordpass does not generate unique IDs. ID W****102-fordpass_tracker already exists - ignoring device_tracker.fordpass_tracker
Platform fordpass does not generate unique IDs. ID W****102-fordpass_ignition already exists - ignoring switch.fordpass_ignition_switch
```

These are exactly the entities I included in my dashboard. Looks like there's something going wrong with IDs, but I'm not able to figure out how to fix this issue.

Many thanks to everyone for the attention

**Comment by pbryan7** [comment]
I just added a new vehicle today and I get the same errors about not generating unique IDs.    I haven't experienced data not updating in HA yet, but I haven't had much success with the 'refresh' service actually forcing new data from a car either.

**Comment by itchannel** [comment]
Please reboot your HA instance, try just doing a standard restart first otherwise you might need to reboot the host. This will fix the already exists error.

**Comment by itsredan97** [comment]
> Please reboot your HA instance, try just doing a standard restart first otherwise you might need to reboot the host. This will fix the already exists error.

Thanks,  but I already rebooted (directly plugged/unplugged my nuc) and restarted, uninstalled and reinstalled the integration but the issue is still there. Could i do something else?

**Comment by itchannel** [comment]
Can you uninstall the integration and check to see if you still have any fordpass entities left as it seems like something on your installation has resulted in some leftover entities that haven't been cleaned up.

{HA_URL}/config/entities
