### ISSUE TITLE
Fordpass Entity ID enumeration issues with multiple vehicles?

### ISSUE THREAD

**Issue by rtw819** [itchannel/fordpass-ha#430]
Running Version:  1.61-Release with 2 Ford full EVs

Background:  I've upgraded through most of the recent 1.60 beta's to the current 1.61-Release, and I'm now finding that the NEW API related Entity IDs between vehicles (which used to be all matching) are somehow no longer matching between both all-electric vehicles.  (See attached screen snips, and fordpass_elVehCharging versus fordpass_elVehCharging_2 for example.  Similarly, entities for the new fordpass_indicators and fordpass_indicators_2 are crisscrossed between vehicles as well.) 

In case it isn't obvious, some _2 new/replacement entity names have been added to the first/primary vehicle (the rest of the entities on the first vehicle don't have _2 identifiers) and vice-versa for the second vehicle, where most have _2 but the new/replacement identities don't have _2 somehow.  Many are mixed up, and when working on dashboards it is a little difficult to remember which one is for which.

This may be related to https://github.com/itchannel/fordpass-ha/issues/429 but not quite the same thing?

First vehicle (entity name examples)
![image](https://github.com/itchannel/fordpass-ha/assets/13564953/29998fd3-dd48-4c7e-adab-41afcfb3ba62)

Second vehicle (entity name examples)
![image](https://github.com/itchannel/fordpass-ha/assets/13564953/06e8212d-d1f1-4dcd-8675-4c6c3fa5bb88)

Is there an easy fix for this?  Not sure why it would have crossed the two entity name varieties between vehicles when adding them in the first place.  Any thoughts?

Thanks in advance.

**Comment by rtw819** [comment]
Well, crud.  So, to fix this (based on the images seen above) would it work to simply manually swap/rotate/rename the entity IDs shifting the out-of-order entity ID names back to the correct enumeration for both vehicles?  Failing that, would a delete/uninstall of the add-on, and then re-install and re-add both vehicles in the proper order?  Otherwise, what options do I have to clean up these somewhat randomly assigned/mismatched entity ID's with numbers?

I can't really maintain my sanity not knowing easily which identifier to use in the dashboards when they don't all maintain the same _# (or without) aligned uniquely with each respective vehicle, especially given I have several dashboards built.

Giving some thought to the fordpass_[VIN]_sensorname proposed nomenclature, it seems like it would make for some very long entity names.  Perhaps an option to allow use of the last 4 or last 6 of the VIN instead of the whole VIN?  

If we could just somehow keep like-for-like (e.g.  _2 for the second vehicle) for all the (same) 2nd vehicle's entities... life would be back to normal.

Thoughts or guidance is appreciated!

**Comment by rtw819** [comment]
I think the solution for this was to remove the vehicles, and then re-add them in the proper order, and the enumeration issue takes care of itself.  

Additionally, if you do not have the entities tied to Automations, Scenes or Scripts it is easy to rename the entities back and forth 1 -> X, _2 -> 1, X -> _2 if you need to shuffle names of some of the resources.

There are ways to get this to work out eventually, it just takes some time.  Closing this issue.

**Comment by kevin-david** [comment]
> I don't know if there is an easy way too fix this. Ideally I would change how sensors are generated to use a unique id such as fordpass_{VIN}_doorlock. But this would require everyone to update any templates or other changes they have.
> 
> Might be an option going forward if the consensus if people would be happy with the change.

Old issue, but wanted to mention that this would be nice as a setup option perhaps? For now I'm sticking with `_2` because I want to avoid a migration but if I could have started with the VIN I would have done that...
