### ISSUE TITLE
Unable to login - Europe

### ISSUE THREAD

**Issue by gvala** [itchannel/fordpass-ha#435]
Same as with other regions. Reloaded the addon and cannot login anymore

**Comment by pimisen** [comment]
same same but same :-)

**Comment by gvala** [comment]
Now it seems to work. Just now I re-enabled Fordpass and works fine. 
Version 1.61.
I will update to 1.63

**Comment by erkan7g** [comment]
Again same issue. It was fixed but now back to same

**Comment by michalk-k** [comment]
Initially I saw the "step 1 has reached..." error which is reported in another thread.

I moment ago I restarted HA and found FordPass integration starts with unavailable entities.

At the same time (in both cases "step1" error and integration init) it seems like Ford's FordPass application is remains working.

**Comment by itchannel** [comment]
@erkan7g @michalk-k What version are you running? 1.63 Beta 1 has the latest login fix as of last week.

**Comment by woempiej** [comment]
Hi,

When becomes the Beta version stable and downloadable from HACS?

**Comment by erkan7g** [comment]
> @erkan7g @michalk-k What version are you running? 1.63 Beta 1 has the latest login fix as of last week.

I am in stable so 1.61. yes when this beta will be avaliable. ?

**Comment by michalk-k** [comment]
@itchannel i used to use 1.61.
After installing 1.63beta it started to work, however it seems refresh status service doesn't work in this version. But this is another issue. I have to look at it closer.

btw when on 1.61 (which was in failed state), I was't able to update to beta version. I had to uninstall and install.

**Comment by Calimerorulez** [comment]
Installed 1.63 beta 1, and also can confirm I can log in again, thanks for the fix.

One thing that caught my attention, was that the overall door lock status was off. The car was locked, but the integration said unlocked. After I locked it again, from within the integration, the status was locked.

**Comment by michalk-k** [comment]
@Calimerorulez it was like that before (at least on my side). I believe it's an issue with the car/modem which doesn't send the most recent state. I often get door not closed (some of them is ajar). I have to use the refresh service to get the correct state.
I don't know the solution for that. Maybe updating some components in the car could fix it. I'm about to ask for that on Ford forums.

**Comment by Calimerorulez** [comment]
After the update to the beta version of the integration, now seeing the following errors:

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:229
Integration: FordPass (documentation, issues)
First occurred: 20 november 2023 om 22:03:55 (49 occurrences)
Last logged: 10:05:47

Error communicating with FordPass for WF0PXXXXXXXXXXXXX`

**Comment by Hobjersgarden** [comment]
cannot login anymore 1.63 Beta1

**Comment by michalk-k** [comment]
It still works for me but refresh took 9 minutes!!! 
Since the beta, I have a strong impression the comm is severely slower than in v1.61

**Comment by Loopback666** [comment]
> cannot login anymore 1.63 Beta1

Can you try to log into the Ford website and see if they force you to generate a new password? This solved the problem for me; see my comment [here](https://github.com/itchannel/fordpass-ha/issues/440#issuecomment-1821307730)

**Comment by Hobjersgarden** [comment]
> cannot login anymore 1.63 Beta1

"Solved" change password in the app and make new login.

**Comment by xaviersand** [comment]
Hi, can anyone please enlighten me on how can I change the password in ha?  (since i succesfully updated it in the ford app)

**Comment by Calimerorulez** [comment]
> Hi, can anyone please enlighten me on how can I change the password in ha? (since i succesfully updated it in the ford app)

I just removed the integration in HA, and re-added it. Then you can input your credentials again.

**Comment by SquidBytes** [comment]
Ignoring current issues and since this spawned a new issue I'm going to close this for cleanup
