### ISSUE TITLE
Tire pressure units are wrong in US (beta 1)

### ISSUE THREAD

**Issue by lymanepp** [itchannel/fordpass-ha#436]
I'm running the latest beta version to fix the authentication issue with version 1.61. Pressure units should be PSI instead of kPa.

![image](https://github.com/itchannel/fordpass-ha/assets/4195527/63045adc-0062-4e3a-a211-8843cffca360)

**Comment by itchannel** [comment]
Can you confirm you have PSI selected in fordpass options?

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/917525ba-d085-4f0b-bd7f-be6a27425014)

**Comment by lymanepp** [comment]
> Can you confirm you have PSI selected in fordpass options?

Ah, I didn't realize that was added in the latest update. Thanks for the tip and for the integration!
