### ISSUE TITLE
Windows position incomplete

### ISSUE THREAD

**Issue by michalk-k** [itchannel/fordpass-ha#439]
Data of an attribute of fordpass_WindowPosition sensor looks incomplete:

![image](https://github.com/itchannel/fordpass-ha/assets/7868445/7b44bbb9-01f4-49c6-9455-3cb654409fe5)

I can bet, sometimes I can see passengerWindow inside

Seen in v1.61 and v1.63-beta

**Comment by itchannel** [comment]
It's actually what's returned by the current Fordpass API endpoint. It doesn't include all window information anymore. 

However there is another potential way I'm exploring based upon information returned when you refresh the status against the vehicle manually.

**Comment by SquidBytes** [comment]
#349
