### ISSUE TITLE
Cant reload integration again, asia

### ISSUE THREAD

**Issue by doronazl** [itchannel/fordpass-ha#441]
Did ford fuck it up again?

**Comment by BallistikG** [comment]
Same issue for me. Deleted integration and tried to re-add. Now getting an "Invalid Credentials Error". Looking like Ford's grip is tightening
![image](https://github.com/itchannel/fordpass-ha/assets/68307558/8ec66ef0-a3cb-4b72-8c1f-93fa678d2338)

**Comment by Loopback666** [comment]
> Same issue for me. Deleted integration and tried to re-add. Now getting an "Invalid Credentials Error". Looking like Ford's grip is tightening

Can you try to log into the Ford website and see if they force you to generate a new password? This solved the problem for me; see my comment https://github.com/itchannel/fordpass-ha/issues/440#issuecomment-1821307730

**Comment by doronazl** [comment]
update - so i went to the ford website to login from there
now i dont know how others used this , but for us in asia, had to use a phone number to login , not email address
but today, when i went to the ford website to login, it asked me to switch to email, i did that, got otp to the email, then signed in to the website succesfully
i then deleted the integration on home assistant and reinstalled it, logged in this time with the email address and not with the phone like before, it worked, i can use the integration again
but whats fucked up now is my phone app, the official ford pass app is asking me to login with a phone, not with email, trying to login with the phone hits me with error invalid credentials, so basically those idiots switched to email but forgot to update the app ? , i am not solely depended on home assistant to remote control my car, what a joke this company is
