### ISSUE TITLE
1.63 Beta 1 login not working

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#442]
It appears Ford is requesting certain users to reset their passwords. This might be because they've moved to a new authentication system and are now enforcing a new password policy. 

There is also a small bug in the beta which hardcodes the region for one part which I'll fix this week but don't think this is causing the reset.

**If you do get the login issue, please use the latest Fordpass app and sign in, it should prompt you to change your password. You can then re-enter those details in the integration**

**Comment by noman1228** [comment]
Confirmed. Changed password and logged in successfully. Thanks for all of your hard work!

**Comment by luongdaniel** [comment]
Thanks for that, everything is working as expected now!

**Comment by doronazl** [comment]
update - so i went to the ford website to login from there
now i dont know how others used this , but for us in asia, had to use a phone number to login , not email address
but today, when i went to the ford website to login, it asked me to switch to email, i did that, got otp to the email, then signed in to the website succesfully
i then deleted the integration on home assistant and reinstalled it, logged in this time with the email address and not with the phone like before, it worked, i can use the integration again
but whats fucked up now is my phone app, the official ford pass app is asking me to login with a phone, not with email, trying to login with the phone hits me with error invalid credentials, so basically those idiots switched to email but forgot to update the app ? , i am not solely depended on home assistant to remote control my car, what a joke this company is

**Comment by doronazl** [comment]
update - so i went to the ford website to login from there
now i dont know how others used this , but for us in asia, had to use a phone number to login , not email address
but today, when i went to the ford website to login, it asked me to switch to email, i did that, got otp to the email, then signed in to the website succesfully
i then deleted the integration on home assistant and reinstalled it, logged in this time with the email address and not with the phone like before, it worked, i can use the integration again
but whats fucked up now is my phone app, the official ford pass app is asking me to login with a phone, not with email, trying to login with the phone hits me with error invalid credentials, so basically those idiots switched to email but forgot to update the app
i then created a new account from within the app, with my phone number again, the same phone number from before, it created successfully, which means they no longer know that phone number, but couldnt grant access to this user without resetting the whole ford connect system from the car itself, WHAT A MESS
i did that, while registering it asked for email , gave it a new one, linked that user to the car, fordpass working again.
now back to the integration, cant login, invalid credentials no matter what i do, phone number, email, whatever, dead.
went back to the website, thought maybe il sacrifice a user by forcing the change to email again, but nope, cant login with the phone like before or with an email.

looks to me that the credentials are totally different now between what the app uses and what the ford website/integration is using.
so situation now is ford app working, but no way to login to the integration or their website

**Comment by doronazl** [comment]
> update - so i went to the ford website to login from there now i dont know how others used this , but for us in asia, had to use a phone number to login , not email address but today, when i went to the ford website to login, it asked me to switch to email, i did that, got otp to the email, then signed in to the website succesfully i then deleted the integration on home assistant and reinstalled it, logged in this time with the email address and not with the phone like before, it worked, i can use the integration again but whats fucked up now is my phone app, the official ford pass app is asking me to login with a phone, not with email, trying to login with the phone hits me with error invalid credentials, so basically those idiots switched to email but forgot to update the app i then created a new account from within the app, with my phone number again, the same phone number from before, it created successfully, which means they no longer know that phone number, but couldnt grant access to this user without resetting the whole ford connect system from the car itself, WHAT A MESS i did that, while registering it asked for email , gave it a new one, linked that user to the car, fordpass working again. now back to the integration, cant login, invalid credentials no matter what i do, phone number, email, whatever, dead. went back to the website, thought maybe il sacrifice a user by forcing the change to email again, but nope, cant login with the phone like before or with an email.
> 
> looks to me that the credentials are totally different now between what the app uses and what the ford website/integration is using. so situation now is ford app working, but no way to login to the integration or their website

to further clarify, if i go to login.ford.com - it asks for email address, but login.ford.co.th which is thailand , im getting login by phone, 2 totally different interfaces and that .com one is where the integration going
@itchannel is there a way to direct the login to login.ford.co.th instead for thailand users ? this might be the same issue with australia im not sure need to check

**Comment by 400HPMustang** [comment]
I've updated my password with Ford, do I need to do something special in HA to change it in the integration? I've tried disabling and enabling it again after restarting HA and I get nothing.

**Comment by buskjan** [comment]
I have changed my Fordpass password and can log in in the phone app. Reinstalled the integration but the home assistant integration still complains of wrong credentials.

**Comment by pdecker414** [comment]
Same issue. I can log out of the phone app and log back in but cannot log in via Fordpass integration.

**Comment by pdecker414** [comment]
I can confirm that 1.63 beta fixes the login issue

**Comment by itchannel** [comment]
> going

I need a copy of the Thai fordpass app ideally an apk so I can check the login url. But from what I've seen most fordpass applications now use login.ford.com then a region string after that. I thought they might have got away from using mobile for some users and email for others.

I'll try and have a look later today but this is part of the reason I haven't realised a production version yet as there's been quite a few different changes

**Comment by Cellivar** [comment]
Chiming in here to echo success, thank you for handling this quickly!

1. Signed into [the ford website](https://www.ford.com/myaccount/account-dashboard) and changed my password.
2. Logged out and back into the mobile app on my phone.
3. Deleted my old car entity in HA and set up a new one using the new credentials.

Got my C-Max's status reporting in again!

**Comment by zomar** [comment]
I have changed my password after being prompted by the Fordpass app. Where in HA am I  able to re-enter the new password details in the integration?

**Comment by miguelpucela** [comment]
> Chiming in here to echo success, thank you for handling this quickly!
> 
> 1. Signed into [the ford website](https://www.ford.com/myaccount/account-dashboard) and changed my password.
> 2. Logged out and back into the mobile app on my phone.
> 3. Deleted my old car entity in HA and set up a new one using the new credentials.
> 
> Got my C-Max's status reporting in again!

This worked for me.
Thanks!

**Comment by xaviersand** [comment]
> e integr

same issue here, i changed my password, but i've beeing looking (almost) everywhere to find where to enter my new password in ha

**Comment by pdecker414** [comment]
> > e integr
> 
> same issue here, i changed my password, but i've beeing looking (almost) everywhere to find where to enter my new password in ha

Delete you instance in HA and then add it again and you will be able to use the new password.

**Comment by xaviersand** [comment]
well, isn't that going to remove all my statistics and history for the entities ? i have many things like refueling for example, that i keek over years i don't want to lose.
Isn't there some other way ?

**Comment by itchannel** [comment]
The other way to do it currently is to edit the HA database and change the saved values for Fordpass username and password. 

I will look at adding in the ability to change creds in the future, just requires a bit of a rewrite.

**Comment by zomar** [comment]
@itchannel Thank you for your response and your consideration to add the ability to change creds in the future. If it's going to take up a lot of your time then I would skip it. I have been using your integration for a very long time and this situation has only been required once.

**Comment by zomar** [comment]
![image](https://github.com/itchannel/fordpass-ha/assets/1669247/a1db91d5-4506-4a6d-bae0-0d001db66daf)
