### ISSUE TITLE
Attribute calibration

### ISSUE THREAD

**Issue by KX-T308** [itchannel/fordpass-ha#443]
I have a Transit Connect that shows a fuel range of 440 miles, but HA is reporting 698 miles. The AdBlu is also reporting a higher figure then the vehicle. Is there anyway of calibrating the intergration to show the correct figure?

**Comment by KX-T308** [comment]
Your right. I did the conversion and it is in km. I've added a Template helper to so the conversion. The FordPass app and dashboard card are now showing the same. I have also done the same with the AdBlue, hoping everything stays synced.

**Comment by itchannel** [comment]
The integration should use the default units you have set in HA e.g. Metric or US in /config/general. 

If this is not working for you I will need to have a look into it.

**Comment by KX-T308** [comment]
I've just checked. My units are set as metric and the fuel attribute show as US, but if I change the units to US it shows as metric. The exhaustFluidLevel range still show in US when either unit is selected

**Comment by SquidBytes** [comment]
I'm not sure if this is still an issue.
If it is - are you able to provide
- The value HomeAssistant displays
- The value it should be
