### ISSUE TITLE
Login not Working

### ISSUE THREAD

**Issue by timo55001** [itchannel/fordpass-ha#444]
I updated the Ford Pass integration today. Since then I always get the error Authorization failed.

**Comment by iampwd** [comment]
Have you tried this?

https://github.com/itchannel/fordpass-ha/issues/442

**Comment by timo55001** [comment]
Yes, I have tried that

**Comment by willyc58** [comment]
login for betarelease  of 1.63 was working for me but when I clicked the send button  I got a popup window not in English or Dutch (my language)

**Comment by CodyJon** [comment]
Also having same issue, seems I'm having to delete and re integrate quite often,now it's not accepting my login.

**Comment by itchannel** [comment]
If you are still having issues with the beta release. Can you please provide me a copy of your logs so I can diagnose the issue. 

https://github.com/itchannel/fordpass-ha/wiki/Obtaining-Integration-Logs

**Comment by itchannel** [comment]
Closing as there's been no updates in a month. If this is still an issue for you then please re-open the issue and provide the logs.
