### ISSUE TITLE
Lincoln Navigator VIN

### ISSUE THREAD

**Issue by JDogg016** [itchannel/fordpass-ha#447]
I removed v 1.61 and installed 1.63b. I can enter my username and password, but when I am prompted to enter the VIN, I see two things:

- HA states it cannot find a VIN associated with the account and
- When I enter the VIN, it says not found

I noticed in the description that the API changes may have impacted my particular vehicle as I have a 2020 Lincoln navigator.

**Comment by itchannel** [comment]
There is still an issue with Lincoln models, they don't appear to show on the new fordpass API. I would need to run someone through the process or provide me with creds to go through the process on the lincoln app and see what the changes are.

**Comment by JDogg016** [comment]
Is this something that I can help with?

From: itchannel ***@***.***>
Date: Sunday, November 26, 2023 at 2:37 AM
To: itchannel/fordpass-ha ***@***.***>
Cc: JDogg016 ***@***.***>, Author ***@***.***>
Subject: Re: [itchannel/fordpass-ha] Lincoln Navigator VIN (Issue #447)

There is still an issue with Lincoln models, they don't appear to show on the new fordpass API. I would need to run someone through the process or provide me with creds to go through the process on the lincoln app and see what the changes are.

**Comment by sdholden28** [comment]
> There is still an issue with Lincoln models, they don't appear to show on the new fordpass API. I would need to run someone through the process or provide me with creds to go through the process on the lincoln app and see what the changes are.

I'm willing to provide you with account credentials for a lincoln vehicle. How should I contact you?

**Comment by slumdlordshnay** [comment]
Same here 2018 Lincoln Navigator asks for vin after user/password but then says it can't find it.

**Comment by itchannel** [comment]
> > There is still an issue with Lincoln models, they don't appear to show on the new fordpass API. I would need to run someone through the process or provide me with creds to go through the process on the lincoln app and see what the changes are.
> 
> 
> 
> I'm willing to provide you with account credentials for a lincoln vehicle. How should I contact you?

Please email me at github@itchannel.me

Could you also try logging into the standard fordpass app instead of the Lincoln app and tell me if your vehicle shows.

**Comment by slumdlordshnay** [comment]
If I open the fordpass app I use my same login/password but no vehicle is there. So I put in my vin and get an error saying "That's a Lincoln! Please download the lincoln app"

**Comment by itchannel** [comment]
If anyone can work with me on this either running a proxy or temporarily providing me some Lincoln creds I can get this added. Unfortunately I don't have access to such vehicles so can't currently debug on my end. 

If anyone wants to personally message me my email is gitlab@itchannel.me

**Comment by sdholden28** [comment]
> If anyone wants to personally message me my email is [github@itchannel.me](mailto:github@itchannel.me)

Email sent with Lincoln Way App credentials and Lincoln VIN

**Comment by itchannel** [comment]
@sdholden28 Progress. Should be ready for a Beta later today turns out the fix was super simple. 

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/5e611c72-f0e3-4396-ba5e-c505d8a1f2a3)

**Comment by sdholden28** [comment]
Good news! That was fast. Thank you for your efforts.

**Comment by itchannel** [comment]
@sdholden28 @slumdlordshnay If either of you have time, can you try the 1.65 Beta1  release. It should now work when manually adding a Lincoln VIN number to the integration. If it works I'll look into getting vehicle lookup working down the line.

**Comment by sdholden28** [comment]
> @sdholden28 @slumdlordshnay If either of you have time, can you try the 1.65 Beta1 release. It should now work when manually adding a Lincoln VIN number to the integration. If it works I'll look into getting vehicle lookup working down the line.

I've installed v1.65 Beta 1 and I was able to successfully set up my lincoln vehicle. I provided the Lincoln Way App credentials, and then the VIN number when the vehicle lookup failed (as expected). All functions appear to work as expected.

**Comment by slumdlordshnay** [comment]
Sorry been away and crazy busy but I just tested it as well and works now! Thanks for the update!

**Comment by itchannel** [comment]
Thanks for confirming. I have now pushed 1.65 to Release :)

**Comment by itchannel** [comment]
Closing as 1.65 addresses this issue.

**Comment by sdholden28** [comment]
Well, maybe I spoke too soon. I can't seem to get lock/unlock to work. I thought it had worked earlier, but apparently not. I've deleted and re-added without trouble, but lock/unlock does nothing. I'll get some logs tomorrow, but I wanted to go ahead and mention it.

**Comment by slumdlordshnay** [comment]
Same here. It connected and filled out all the data but I am unable to get any updates or unlock door or start vehicle or anything else.

> Well, maybe I spoke too soon. I can't seem to get lock/unlock to work. I thought it had worked earlier, but apparently not. I've deleted and re-added without trouble, but lock/unlock does nothing. I'll get some logs tomorrow, but I wanted to go ahead and mention it.

**Comment by sdholden28** [comment]
I'll open a new issue since this one is already closed and technically, lincoln vehicles can be added now.
