### ISSUE TITLE
Door Lock always shows an "unlocked" status

### ISSUE THREAD

**Issue by dacmcbibs** [itchannel/fordpass-ha#45]
The entity seems to bounce between unlocked and unavailable , never showing a locked state
- if there is anything I can collect to help troubleshoot let me know

**Comment by itchannel** [comment]
Have you ran the fordpass.refresh_status service at all? As it won't auto poll the car due to battery drain so it's up to you to set an automation to poll that service depending on how quick you want to poll data from your car otherwise the values won't change.

**Comment by itchannel** [comment]
![image](https://user-images.githubusercontent.com/5840973/100556216-7b770380-32ec-11eb-9a75-370367c324d0.png)
Try running that and let me know if your lock status updates

**Comment by dacmcbibs** [comment]
Yes I have run the refresh status service... , but it still always shows as unlocked:
![image](https://user-images.githubusercontent.com/36335317/100557969-374b1b00-327a-11eb-8335-28e6c59d8623.png)

**Comment by itchannel** [comment]
Can you look in your HA logs for me and see if there is any error from the fordpass integration. Is it just the lock or are you getting the same issues with the other entities?

**Comment by dacmcbibs** [comment]
I cleared my logs, and ran a refresh status service call, no errors in the logs.  The status of the other entities is as follows:
alarm - shows error
doorStatus - ways shows open because hood door and inner tailgate door are invalid (because I don't have those I assume :) ) all other doors show valid status of closed
Window position - unsupported 

Otherwise the other entities all show valid values

**Comment by itchannel** [comment]
Can you give me a state for those invalid doors, I can edit the code to disregard them then. 

Interesting your alarm shows error. 

Out of interest what model and year of car do you have. 

May get you to run the debug script which will spit out the vehicle json data as it sounds like your car is different to a lot of others.

**Comment by dacmcbibs** [comment]
Its a Ford Escape 2018 
The state of HoodDoor and InnerTailGateDoor are both "Invalid"
I'd be happy to run the debug script, would you mind pointing me to it? I don't see it in the repository.

**Comment by itchannel** [comment]
[Debug](https://github.com/itchannel/ford_debug) If you can run that and then send me the contents of the log file minus passwords and tokens. 

Don't worrry about putting a region or anything as it only needs a temp token

**Comment by dacmcbibs** [comment]
Attached is my sanitized log (really just the last line of the log since from the look of it that's all you really need) 
Let me know if you need anything else
[log.zip](https://github.com/itchannel/fordpass-ha/files/5613561/log.zip)

**Comment by itchannel** [comment]
From what I can tell it's an issue with your car or compatibility with your car and the latest API as I can see the following for both "lockstatus" and "alarm"

"lockStatus":{"value":"ERROR","status":"CURRENT","timestamp":"11-30-2020 00:44:22"}
"alarm":{"value":"ERROR","status":"CURRENT","timestamp":"11-30-2020 00:44:22"},

where as normally these should be locked/unlocked and Set/notset. 

I can at least modify the code to accept your missing doors which I'll do in the next update so it shows open/closed for you.

**Comment by dacmcbibs** [comment]
I saw the same when I looked at the log.  Maybe it isn't supported on my car .  I can lock and unlock the car from the FordPass app, but nothing in the app actually tells me the status of the doors being locked or unlocked (I just get a popup that the action was successful)  - there is also no entry in the app for the alarm (which also works ).  Thanks for taking a look.

**Comment by itchannel** [comment]
I would try running the debug script a couple of times over a day or two and see if those two values change in the JSON at all just incase. I know fords API has been very buggy the last 24hrs

**Comment by itchannel** [comment]
Closing this issue as the original point has been fixed and there has been no answer from the original author in 10 days
