### ISSUE TITLE
South Africa Cell login stoped working (did not update version)

### ISSUE THREAD

**Issue by gerhardking** [itchannel/fordpass-ha#453]
Hi There, you assisted me a while ago to get FordPass integration working in South Africa (dropping the 0 and using a older version of the app) but it unfortunatly stopped working again and i am not able to login. please can you assist again ? Thanks a mil Gerhard

**Comment by itchannel** [comment]
Can you please try using the country code and + symbol like below for the username:

+99123456789

This seems to work for most people.

**Comment by SquidBytes** [comment]
Checking in to see if that, or any of the new releases fixed this for you @gerhardking
