### ISSUE TITLE
Distance in Miles not working again

### ISSUE THREAD

**Issue by stumiles86** [itchannel/fordpass-ha#454]
I have set the integration to Miles but the odometer is still being shown in KM.

This was an issue a while ago in an older version and was previously fixed, but since the API change this issue has returned.

**Comment by dougle03** [comment]
Same issue

**Comment by BobMac57** [comment]
DTE is not even showing up in fordpass_fuel attributes...

**Comment by itchannel** [comment]
Can you please confirm what unit you have selected under the fordpass_odometer settings like shown below:

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/e2a2bd12-7c09-4bd5-bbd8-a007f5f26e25)

**Comment by dougle03** [comment]
Hi, changed it to 'Mi' and now it's perfect. Thanks.
