### ISSUE TITLE
Source_type GPS deprecated

### ISSUE THREAD

**Issue by albamatti** [itchannel/fordpass-ha#464]
Getting an error in HA.
Core
2024.1.0
Supervisor
2023.12.0
Operating System
11.3
Frontend
20240103.3

SOURCE_TYPE_GPS was used from fordpass, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead,

**Comment by itchannel** [comment]
Thanks for the heads up. Just fixed it in 1.66 :)
