### ISSUE TITLE
No vehicle

### ISSUE THREAD

**Issue by rpajik** [itchannel/fordpass-ha#466]
Hello,

I'm unable add my new car. I get a valid access token, it fetch the VIN via api and not add the vehicle.

I set configure the debug and see this information:

2024-01-06 20:26:54.648 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2024-01-06 20:26:54.648 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] Getting Vehicles
2024-01-06 20:26:57.007 DEBUG (MainThread) [custom_components.fordpass.config_flow] [{'VIN': 'WF......', 'nickName': 'Mustang', 'tcuEnabled': True, 'isASDN': False}]
2024-01-06 20:26:57.007 DEBUG (MainThread) [custom_components.fordpass.config_flow] {'WF....'}
2024-01-06 20:26:57.007 DEBUG (MainThread) [custom_components.fordpass.config_flow] {'VIN': 'WF....', 'nickName': 'Mustang', 'tcuEnabled': True, 'isASDN': False}
2024-01-06 20:26:57.007 DEBUG (MainThread) [custom_components.fordpass.config_flow] No Vehicles?

I'm not sure, if this is issue in your integration or this is on Ford side.

Could you help me?

**Comment by itchannel** [comment]
Can you please provide the following information:

- Model and year of vehicle
- Version of Sync on entertainment unit
- Version of Home assistant
- Region your from

It could be that your Sync unit needs updating for the new autonomics API or that you have privacy settings enabled on your cars dashboard. Ford data sharing needs to be enabled etc for it to work.

**Comment by rpajik** [comment]
> Can you please provide the following information:
> 
>     * Model and year of vehicle
> 
>     * Version of Sync on entertainment unit
> 
>     * Version of Home assistant
> 
>     * Region your from
> 
> 
> It could be that your Sync unit needs updating for the new autonomics API or that you have privacy settings enabled on your cars dashboard. Ford data sharing needs to be enabled etc for it to work.

Mustang Mach E 2023
Sync: 22280_PRODUCT, Rev 592
HA: 2023.12.4
Region: EU
fordpass-ha: 1.66 ( just updated from 1.65 and tested )

**Comment by serlinGi** [comment]
hello,
I'm encountering the same problem.
yesterday my 2 vehicles were not available;
I realized that their status wasn't even updated from the Ford app.
to avoid error messages and warnings, last night I disabled the 2 integrated cars in HA.
Today everything is working again with the app but
unfortunately, however, when I try to reactivate the integrations, the result is "No vehicles on account or all are configured already".
I also completely uninstalled the integration and downloaded it again but the result is the same.
😢

**Comment by serlinGi** [comment]
> hello, I'm encountering the same problem. yesterday my 2 vehicles were not available; I realized that their status wasn't even updated from the Ford app. to avoid error messages and warnings, last night I disabled the 2 integrated cars in HA. Today everything is working again with the app but unfortunately, however, when I try to reactivate the integrations, the result is "No vehicles on account or all are configured already". I also completely uninstalled the integration and downloaded it again but the result is the same. 😢

solved: I apologize but it was my fault (in part) 😬.
although I uninstalled and downloaded the integration again, the 2 previously disabled cars remained in the disabled list.  rehabilitate and now everything is OK

**Comment by rpajik** [comment]
Similar issue ... it was in disabled car. Don't know why, because it was never been enabled and adding car always return some errors.

**Comment by paulcusick3** [comment]
Where is the disabled car list?

**Comment by rpajik** [comment]
@paulcusick3 Settings -> Devices & Services -> Integrations -> there you can show disabled integrations ( XXX disabled SHOW ).

**Comment by paulcusick3** [comment]
@rpajik  ok - I deleted that; and now can not add back.. Will try to uninstall
