### ISSUE TITLE
issue with lates version.. 

### ISSUE THREAD

**Issue by denperss11** [itchannel/fordpass-ha#47]
When im running at 1.0.6 everything is working fine. 
- But when im update to 1.0.7 vers, i get errors like:

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:140
Integration: FordPass (documentation, issues)
First occurred: 9.23.22 (246 occurrences)
Last logged: 15.01.31

401 Client Error: 
501 server error: 

Iv'e tried the guide but 107 dosent work for my EU ford. 

- I updated to 107 from 106, 
- restarted 
- called service refresh. 
- also tried to uninstall everything and install 107 directly but just comes back with error :(

**Comment by itchannel** [comment]
Are you still encountering this issue?

What region did you select for your car? also can you try deleting the integration and deleting /tmp/token.txt & /tmp/fordpass_token.txt then adding the integration to clear all tokens.

**Comment by denperss11** [comment]
Hi,

Yes im still having this issue.

i'm selecting UK&EUROPE,.

Also i dont have the to files in my temp folder.. ?
- i'm running it at Synology Nas with Hass.io/HomeAssistant



Den tir. 1. dec. 2020 kl. 14.11 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
Is that using the docker instance on your NAS? If so you need to interact with the container and delete it from within the container.

**Comment by denperss11** [comment]
No it dosent use docker. Its a direct install with normal dictionary..

tirsdag den 1. december 2020 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
Can you link me to the install you used, as I can't find any synology installs that don't use docker.

**Comment by denperss11** [comment]
Sorry.

It dident see it, i install hassio by a plugin..

But when im lookin at the docker, there is no temp files.
- My docker folder is emty.


Logger: homeassistant.config_entries
Source: config_entries.py:247
First occurred: 30. november 2020 15.58.57 (3710 occurrences)
Last logged: 9.48.57

   - Config entry for fordpass not ready yet. Retrying in 40 seconds
   - Config entry for hue not ready yet. Retrying in 40 seconds
   - Config entry for ipp not ready yet. Retrying in 80 seconds
   - Config entry for fordpass not ready yet. Retrying in 80 seconds
   - Config entry for hue not ready yet. Retrying in 80 seconds




Den ons. 2. dec. 2020 kl. 02.03 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
Deleting the token has fixed the issue for @denperss11
