### ISSUE TITLE
fordpass_battery 24 %

### ISSUE THREAD

**Issue by slumdlordshnay** [itchannel/fordpass-ha#470]
Home assistant is showing fordpass_battery 24 % Where does this data come from? I thought my trucks battery level was low so I put a charger on it and it was fully charged in under 10 mins. But this never updated in home assistant. The battery isn't that old and the truck starts fine no sign of a weak battery, so why is it so off? A week or so ago it said 32-34%.

**Comment by SquidBytes** [comment]
The sensor is just displaying what `batteryStateOfCharge` is returned from the API.
