### ISSUE TITLE
Trunk/Frunk Entity?

### ISSUE THREAD

**Issue by dbosso** [itchannel/fordpass-ha#474]
I see #212 was closed, but there is now a trunk/frunk button on my fordpass app for the Mach-E. I'd like to re-request this as it would be very helpful. Thanks!

**Comment by SquidBytes** [comment]
Interesting. I don't have a button or option in my app for the Lightning.
Are you able to [provide your json file](https://github.com/itchannel/fordpass-ha/wiki/AutonomicData-Tutorial)?

**Comment by dbosso** [comment]
After further investigation those buttons only work when you have a phone as key direct bluetooth connection with the car. They are obviously not working over the network API. Bummer...
