### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by paulcusick3** [itchannel/fordpass-ha#475]
Anyone getting access errors today 30JAN?  Started for me an hour ago.  Also having website issues... logsin, data old and then lots of errors and logs out.

`WARNING (MainThread) [custom_components.fordpass] 401 Client Error: Unauthorized for url: https://login.ford.com/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-US/oauth2/v2.0/token`

Concerned lockouts... I do not have polling adjusted from default.

**Comment by paulcusick3** [comment]
Thanks - I disabled for now... don't want my polls to compound me on their radar.

**Comment by paulcusick3** [comment]
Also, I am not blocked on Fordpass as I use a different user.  Started this after the last time this happened.  Glad I did; highly recommend.

**Comment by BatMahn** [comment]
Just re-enabled and it appears to be working again. Maybe Ford just being Ford earlier?

**Comment by SquidBytes** [comment]
> Just re-enabled and it appears to be working again. Maybe Ford just being Ford earlier?

I think this may be the case
