### ISSUE TITLE
Missing PHEV status

### ISSUE THREAD

**Issue by denperss11** [itchannel/fordpass-ha#48]
Hi. 

Im using your awesome work, thank u! 
But i only se 12v battery status.
- Can u make it so it states the volts and not just status "Good/Bad"  but ex. "12.3v"
- It also missing the status of the EV/PHEV Battery procent.. 

Is it possible that u can add this to the next update ? 

Really great great job! 
Thank u..

**Comment by itchannel** [comment]
I would need a dump of the vehicle status json to see what values are required for a EV/PHEV as I don't have one. 

If you could run the following script on a pc with python and send me the output from the log file minus passwords and tokens I can look at getting it integrated for you [Debug Script](https://github.com/itchannel/ford_debug)

**Comment by denperss11** [comment]
Hi there,

Thank u so much !
I haven't tried that before, could u please quick guide me trough so i can
do it correctly? :)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den tir. 1. dec. 2020 kl. 14.14 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
It's pretty much

1. Clone the debug repo
2. Ensure you have python3 installed
3. python3 -m pip install requests json 
4. python3 debug.py email password vin 1
5. Log file is created in the same folder as the script

**Comment by TRusselo** [comment]
batteryStatusActual":{"value":13,"status":"CURRENT","timestamp":"11-23-2020 00:57:36"}}

"batteryFillLevel":null,"elVehDTE":null,"hybridModeStatus":null,"chargingStatus":null,"plugStatus":null,"chargeStartTime":null,"chargeEndTime":null,"preCondStatusDsply":null,"chargerPowertype":null,"batteryPerfStatus":null,"outandAbout":{"value":"PwPckOffTqNotAvailable","status":"CURRENT","timestamp":"11-23-2020 00:57:36"},"batteryChargeStatus":null,"dcFastChargeData":null,

I think these may be relevant...  my van is not HEV but returned these values

**Comment by TRusselo** [comment]
for non electric vehicles would also like to see added :
Distance to Empty:  144.3 KM
"fuel":{"fuelLevel":51.304512,**"distanceToEmpty":144.3**,"status":"CURRENT","timestamp":"11-23-2020 00:57:36"}

Battery Voltage : 13 Volts
Battery Status Actual (needs testing to see if this IS voltage or not)
"batteryStatusActual":{"value":13,"status":"CURRENT","timestamp":"11-23-2020 00:57:36"}}

Oil Life - change the current "Status Good"  to OilLifeActual - 57 % life left.
"oil":{"oilLife":"STATUS_GOOD","oilLifeActual":57,"status":"CURRENT","timestamp":"11-23-2020 00:57:36"}

GPS - geocoded location entity via lat long
"gps":{"latitude":"99.9999999","longitude":"-999.499999","gpsState":"UNSHIFTED","status":"LAST_KNOWN","timestamp":"11-21-2020 18:05:44"}

Each door / hood / trunk/tailgate (bonnet)
00:57:36"},"leftRearDoor":{"value":"Closed","status":"CURRENT","timestamp":"11-23-2020 00:57:36"},"driverDoor":{"value":"Closed","status":"CURRENT","timestamp":"11-23-2020 00:57:36"},"passengerDoor":{"value":"Closed","status":"CURRENT","timestamp":"11-23-2020 00:57:36"},"hoodDoor":{"value":"Closed","status":"CURRENT","timestamp":"11-23-2020 00:57:36"},"tailgateDoor":{"value":"Closed","status":"CURRENT","timestamp":"11-23-2020
I would assume cars have "rightRearDoor' as well, but i have a Van

Diesel Vehicles would appreciate:
"dieselSystemStatus":{"exhaustFluidLevel":null,"filterSoot":null,"ureaRange":null,"metricType":null,"filterRegenerationStatus":null}},"version":"4.0.0","status":200}
exhaust fluid AKA DEF fluid in North America.
**An automation when DEF fluid is low, order some online....?

**Comment by denperss11** [comment]
Yes, that looks like the correct data :)

Please add all options both HEV an non HEV dat as listed from TRusselo
<https://github.com/TRusselo>.


Thank u for sharing!

Den ons. 2. dec. 2020 kl. 03.19 skrev Tristyn Russelo <
notifications@github.com>:

**Comment by denperss11** [comment]
Is there any one that have time for a remote session to assist me doing the
log file.
Sorry but im not the best with python :(


My skype is: live:denperss11

Den ons. 2. dec. 2020 kl. 10.01 skrev Dennis Aydin <spamdennis2018@gmail.com

**Comment by itchannel** [comment]
@TRusselo 

- distanceToEmpty is already an attribute for the fuel entity so I recommend adding a template if you want to use it to save a lot of entities. 
![image](https://user-images.githubusercontent.com/5840973/100863294-1683ff00-34e0-11eb-9332-797ddc2451f5.png)

- Battery voltage I will be adding as a attribute to the battery sensor 

- Oil level is already an attribute
![image](https://user-images.githubusercontent.com/5840973/100863282-0ec45a80-34e0-11eb-9f5b-578225604aa8.png)

- GPS is set as a tracker entity and sensor entity don't think we need another one
![image](https://user-images.githubusercontent.com/5840973/100863260-0704b600-34e0-11eb-8683-7061f8a8cce1.png)

- Doors are individually listed already 
![image](https://user-images.githubusercontent.com/5840973/100863234-fbb18a80-34df-11eb-9bd6-0f6207b2fe7e.png)

Diesel I will look into and the EV stuff I need to know what the intended values are I know the keys in the json to use but not the data values that are output without seeing an EV output

**Comment by denperss11** [comment]
Hello,

If u could add my skype, or other preferred i can give u alle the requested
data from my HEV.

but i need the help by running the python scrip from my win.
- im ready now by my pc.

Or if u could do a small video guide, from your end then i will upload it
right away..

Thank u..

Den ons. 2. dec. 2020 kl. 11.52 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
skype: itchannelv2

**Comment by denperss11** [comment]
Sorry i did first see your msg now, but ping me when ready..
ive added you to skype..


Den ons. 2. dec. 2020 kl. 12.12 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
Need to add the following:

``` 
"batteryFillLevel":{
      "value":0.0,
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "elVehDTE":{
      "value":0.0,
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "hybridModeStatus":{
      "value":"AutoChargeSustainMode",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "chargingStatus":{
      "value":"NotReady",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "plugStatus":{
      "value":0,
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "chargeStartTime":{
      "value":"12-02-2020 22:59:00",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "chargeEndTime":{
      "value":"12-03-2020 02:02:00",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "preCondStatusDsply":{
      "value":"NotScheduled",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "chargerPowertype":{
      "value":"EVSENotDetected",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
   "batteryPerfStatus":{
      "value":"Oknomessagedisplayed",
      "status":"CURRENT",
      "timestamp":"12-02-2020 22:00:00"
   },
```

**Comment by itchannel** [comment]
New entity added called elVeh which shows the current charge status and any attributes like charge time. #51

**Comment by itchannel** [comment]
Added in 1.0.8

**Comment by denperss** [comment]
Hi, 
Could u check skype ? :)
