### ISSUE TITLE
PHEV Battery percentage

### ISSUE THREAD

**Issue by fabiofabbrucci** [itchannel/fordpass-ha#481]
Hi guys,
thanks to this integration I've been able to get some data in my HA. Ty 
I own a Ford Kuga PHEV 2020.
But I still have 2 issues.

Here some screens to give you some context
![IMG_20240410_124435](https://github.com/itchannel/fordpass-ha/assets/150018882/aeda4b12-0b23-4282-83c6-8cff10b80db9)
![IMG_20240410_124445](https://github.com/itchannel/fordpass-ha/assets/150018882/535ccb3e-263d-4e59-b03b-3ad4793bd18d)
![Screenshot 2024-04-10 at 14 28 47](https://github.com/itchannel/fordpass-ha/assets/150018882/2183b28e-a25b-47fc-8747-61eec676439e)

## Issue 1: PHEV Battery Percentage is missing
As you can see from HA screen, the sensor `fordpass_elVeh` tells me how many km I can run with my battery, but I would need to know how much PHEV battery is left (so the 31%). And this is for a few reasons:
1. I want to know when PHEV battery is too low to trigger some events (recharge, notifications on mobile)
2. I want to monitor the PHEV battery performance
How can I create a sensor that shows that specific data?
And to be more specific, I would not like to translate 19km in a percentage because the 19kms are an estimation made by Ford. If possible, I would like to get the plain data of the PHEV battery.

## Issue 2: Top Right data is misleading
In HA, on the device detail screen (see screenshot) the 80% on battery can mislead a user.
The main data should be the PHEV battery, and not the other batter (to let the car turn on).
How can we change the main data for that screen (once we have the % of the PHEV battery)?

**Comment by fabiofvc** [comment]
I tried to enable logging and I got this

> Registratore: homeassistant.components.recorder.db_schema
> Fonte: components/recorder/db_schema.py:599
> Integrazione: Recorder (documentazione, problemi)
> Prima occorrenza: 9 aprile 2024 alle ore 12:36:26 (24 occorrenze)
> Ultima registrazione: 13:00:07
> 
> State attributes for sensor.fordpass_metrics exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**Comment by Ulrich72** [comment]
Issue 1 - check the attributes:

![image](https://github.com/itchannel/fordpass-ha/assets/116371857/e27db07b-994e-4996-88df-c6cc7279b7d9)

![image](https://github.com/itchannel/fordpass-ha/assets/116371857/766052f1-b8cc-4145-99b8-711a2a1ebf02)

![image](https://github.com/itchannel/fordpass-ha/assets/116371857/22af60bc-acfb-4d7c-aefd-6c563a6efc39)

**Comment by fabiofabbrucci** [comment]
Ty @Ulrich72 
I solved adding this sensors to `configuration.yaml` file:

```
template:
  - sensor:
      - name: "Ford elVeh Battery Level"
        unique_id: "1133"
        state: "{{state_attr('sensor.fordpass_elVeh', 'Battery Charge') }}"
        unit_of_measurement: "%"
        icon: >-
          {% set batteryLevel = states('sensor.ford_elveh_battery_level') | round (-1) | int %}
          {% if batteryLevel == 100 %}
            mdi:battery
          {% else %}
            mdi:battery-{{ batteryLevel }}
          {% endif %}
      - name: "Ford elVeh Battery Charging Status"
        unique_id: "1144"
        state: "{{state_attr('sensor.fordpass_elVehCharging', 'Charging Status') }}"
        icon: >-
          {% if is_state_attr('sensor.fordpass_elVehCharging', 'Charging Status', "IN_PROGRESS") %}
            mdi:ev-station
          {% else %}
            mdi:battery
          {% endif %}
```
