### ISSUE TITLE
Authentication error after HA Update

### ISSUE THREAD

**Issue by compoundbow83** [itchannel/fordpass-ha#489]
Hello,
I have update HA today to version 2024.5.2. After this the integration stopp working.

I have delete the integration and would like to make it new. But now if I put in the login credicals I get the Authentication error.

Must I change anything or is this an bug after the HA Update?

**Comment by Itsjelko** [comment]
Same here cant login changed password twice same error. I live in belguim europa

**Comment by Tomette** [comment]
Idem

**Comment by ziptbm** [comment]
Same here in the US.

**Comment by vroomlab** [comment]
Same here

**Comment by notmayo** [comment]
I don't think this error is related to the update; it is more likely that your connection to Ford's API was closed when restarting home assistant and their APIs are now blocking third-party apps.

**Comment by notmayo** [comment]
I am in the US and I am receiving this error:
2024-05-07 22:01:55.861 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for VINHERE
2024-05-07 22:02:37.080 WARNING (MainThread) [custom_components.fordpass] 403 Client Error: Forbidden for url: https://login.ford.com/redactingjustincase/B2C_1A_SignInSignUp_EN-US/SelfAsserted?tx=StateProperties=redactingjustincase&p=B2C_1A_SignInSignUp_en-AU
2024-05-07 22:02:37.080 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for VINHERE
2024-05-07 22:02:37.080 WARNING (MainThread) [custom_components.fordpass] Returning Stale data to prevent unavaliable status

**Comment by blindguynar** [comment]
Oh great, now i gotta throw away my truck like i did my garage door opener.  This ha hobby is expensive!!

**Comment by notmayo** [comment]
> Oh great, now i gotta throw away my truck like i did my garage door opener.  This ha hobby is expensive!!

Haha, you may be joking but I did that with MyQ and I am thinking about doing this with my F150 now (selling it ofc) if they do indeed do a press release about blocking 3rd party api use. I have automations to ensure my truck is locked, to start my truck to cool it off before lunch and before getting off work, and more. This is something I rely on and isn't inherently a security risk like these companies want us to believe.

**Comment by blindguynar** [comment]
> > Oh great, now i gotta throw away my truck like i did my garage door opener.  This ha hobby is expensive!!
> 
> Haha, you may be joking but I did that with MyQ and I am thinking about doing this with my F150 now (selling it ofc) if they do indeed do a press release about blocking 3rd party api use. I have automations to ensure my truck is locked, to start my truck to cool it off before lunch and before getting off work, and more. This is something I rely on and isn't inherently a security risk like these companies want us to believe.

Oh i agree.  I did take myq to e-waste recycling place.  I use this to track oil and fuel levels on our vehicles and to send reminders for oil chg and need to get fuel.  Track miliage for other repairs such as tire rotation, replacement, brakes etc.

it’s gonna kinda suck if its really blocked.  I don’t know they don’t take a page from apple.  In-app puchase subscription.  $2.99 a month and i’d gladly forgo a cheese burger and instrad grab ramen noodles for an evening!!

They need to see us as potential revenue streams and not as problems.

**Comment by frankie-boy-hgv** [comment]
Duplicate of https://github.com/itchannel/fordpass-ha/issues/488

**Comment by dougle03** [comment]
> They need to see us as potential revenue streams and not as problems.

They already do and allowing 3rd party API integration means we are less likely to pay them directly. VaaS (Vehicle as a Service) is coming... You will own nothing.....!

**Comment by SquidBytes** [comment]
> Duplicate of #488

Main conversation is moving to that thread
