### ISSUE TITLE
can't refresh, service is not there anymore

### ISSUE THREAD

**Issue by wriel1989** [itchannel/fordpass-ha#495]
After installing 1.68beta and later 1.68release. 
not able to press refresh again. See that the sensor or switch is missing fordpass.refresh_status

**Comment by wriel1989** [comment]
seems ford fixed it, or atleast today it was suddenly working ok

**Comment by SquidBytes** [comment]
There are probably going to be many problems here and there.

> Due to security changes being implemented by Ford, the current solution may stop working in the near future. We are in talks with Ford about how we could potentially support their official 3rd party API, but this may not be a quick process as it's still in development.

On the release notes
