### ISSUE TITLE
403 Client Error: Forbidden for url  (Redirecting U.S. sign-ins to Australia?) 

### ISSUE THREAD

**Issue by aminorjourney** [itchannel/fordpass-ha#497]
With all the caveats of late, things have been working fine until today - then I had the well-documented error fetching ford pass data (with the usual "Error communicating with FordPass for <VIN>")

Naturally, this also included the "Returning Stale data to prevent unavailable status" error, which is to be expected for the first. 

I've since disabled the integration as per recommendations here.  Prior to that, I did try erasing and re-logging into the integration and got an interesting error. 

Despite selecting the correct country (USA) and entering my known-good credentials (Ford's portal and smartphone app continue to work), I saw this error:

`This error originated from a custom integration.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:228
integration: Fordpass (documentation, issues)
First occurred: 3:08:04 PM (13 occurrences)
Last logged: 3:12:05 PM

403 Client Error: Forbidden for url: https://login.ford.com.au/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-AU/SelfAsserted?tx=StateProperties=eyJUSUQiOiIwMmEyNDhkMi1lMDBkLTRlMWQtYWU2ZC0zMTU3N2U5ZWRlMGMifQ&p=B2C_1A_SignInSignUp_EN-AU
`

I tried it a few times to see if it would work - and to confirm that I'd selected the correct integration.  I'm wondering if some redirects are happening in the backend?

**Comment by jonepet** [comment]
403 for me too now.

But, I have been testing the fordpass public API from Norway with my norwegian account and norwegian vehicle, and I can get data from the public API. Request token on web site works, I can log in using the instructions (which is not very well documented, have to get it from the postman docs).

Auth:
Have to request access to vehicle as described in docs (frontend)
After requesting access, token request using code parameter from authorization redirect URL in request access,

curl -X POST -d 'grant_type=authorization_code&client_id=[client id from ford]&client_secret=[client secret from ford]&redirect_uri=https%3A%2F%2Flocalhost%3A3000&code=[the very long "code" parameter received]' 'https://dah2vb2cprod.b2clogin.com/914d88b1-3523-4bf6-9be4-1b96b4f6f919/oauth2/v2.0/token?p=B2C_1A_signup_signin_common'

Response:
{"access_token":"[the important access token]","id_token":"[id token]","token_type":"Bearer","not_before":1715897570,"expires_in":1200,"expires_on":1715898770,"resource":"[uuid]","id_token_expires_in":1200,"profile_info":"[could be secret]","scope":"https://dah2vb2cprod.onmicrosoft.com/fordconnect/access openid offline_access","refresh_token":"[the refresh token we need to get new access tokens after current one has expired]","refresh_token_expires_in":7776000}

The access token can be used to send API requests:

$ curl -H 'Application-ID: AFDC085B-377A-4351-B23E-5E1D35FB3700' -H 'Authorization: Bearer [access token]' -H "Accept: application/json" 'https://api.mps.ford.com/api/fordconnect/v3/vehicles'
{"status":"SUCCESS","vehicles":[{"vehicleId":"[uuid]","make":"F","modelName":"Mustang Mach-E","modelYear":"2021","color":"CARBONIZED GRAY/ASHER GRAY","nickName":"MachE","modemEnabled":true,"vehicleAuthorizationIndicator":1,"serviceCompatible":true,"engineType":"BEV"}]}

More data:
$ curl -H 'Application-ID: AFDC085B-377A-4351-B23E-5E1D35FB3700' -H 'Authorization: Bearer [access token]' -H "Accept: application/json" 'https://api.mps.ford.com/api/fordconnect/v3/vehicles/ff8080818f7a0680018f836f18ab0037'
{"status":"SUCCESS","vehicle":{"vehicleId":"ff8080818f7a0680018f836f18ab0037","make":"F","modelName":"Mustang Mach-E","modelYear":"2021","color":"CARBONIZED GRAY/ASHER GRAY","nickName":"MachE","modemEnabled":true,"lastUpdated":"05-16-2024 21:49:19","vehicleAuthorizationIndicator":1,"serviceCompatible":true,"engineType":"BEV","vehicleDetails":{"batteryChargeLevel":{"value":80.0,"distanceToEmpty":311.0,"timestamp":"05-16-2024 21:40:31"},"mileage":90656.2,"odometer":145897.0},"vehicleStatus":{"tirePressureWarning":false,"deepSleepInProgress":false,"firmwareUpgradeInProgress":false,"remoteStartStatus":{"status":"ENGINE_STOPPED","duration":0,"timeStamp":"05-15-2024 05:02:32"},"chargingStatus":{"value":"ChargeTargetReached","timeStamp":"05-16-2024 21:15:45","chargeStartTime":"05-16-2024 23:14:00","chargeEndTime":"05-16-2024 23:15:00"},"plugStatus":{"value":true,"timeStamp":"05-16-2024 21:15:45"},"ignitionStatus":{"value":"OFF","timeStamp":"05-16-2024 21:40:31"},"doorStatus":[{"vehicleDoor":"UNSPECIFIED_FRONT","value":"CLOSED","vehicleOccupantRole":"DRIVER","timeStamp":"05-16-2024 21:15:32"},{"vehicleDoor":"REAR_LEFT","value":"CLOSED","vehicleOccupantRole":"PASSENGER","timeStamp":"05-16-2024 21:15:32"},{"vehicleDoor":"UNSPECIFIED_FRONT","value":"CLOSED","vehicleOccupantRole":"PASSENGER","timeStamp":"05-16-2024 21:15:32"},{"vehicleDoor":"REAR_RIGHT","value":"CLOSED","vehicleOccupantRole":"PASSENGER","timeStamp":"05-16-2024 21:15:32"},{"vehicleDoor":"TAILGATE","value":"CLOSED","vehicleOccupantRole":"PASSENGER","timeStamp":"05-16-2024 21:15:32"},{"vehicleDoor":"INNER_TAILGATE","value":"CLOSED","vehicleOccupantRole":"PASSENGER","timeStamp":"05-16-2024 21:15:32"},{"vehicleDoor":"HOOD_DOOR","value":"CLOSED","vehicleOccupantRole":"NOT_APPLICABLE","timeStamp":"05-16-2024 21:15:32"}],"lockStatus":{"value":"LOCKED","timeStamp":"05-16-2024 21:15:32"},"alarmStatus":{"value":"SET","timeStamp":"05-16-2024 21:15:32"}},"vehicleLocation":{"speed":0.0,"direction":"SOUTH","timeStamp":"05-16-2024 21:15:45","longitude":"15.409693","latitude":"67.262964"},"vehicleCapabilities":{"remoteLock":"Available","remoteUnlock":"Available","remoteStart":"Available","remoteStop":"Available","boundaryAlerts":"Unavailable"}}}

**Comment by thomase1234** [comment]
I'm based in the EU and the integration is also not working for me since yesterday. Similar, but not the same error,

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:228
integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: May 16, 2024 at 8:12:51 PM (514 occurrences)
Last logged: 8:31:58 AM

    403 Client Error: Forbidden for url: https://login.ford.ie/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-IE/SelfAsserted?tx=StateProperties=eyJUSUQiOiI0MDQ2NjNkZS04MDVmLTQxMDYtYTNjZS1hNzJlMTBjMjhlMGUifQ&p=B2C_1A_SignInSignUp_EN-IE

**Comment by doronazl** [comment]
Same here Thailand, 403 since today

**Comment by thoompje** [comment]
Same here in the Netherlands, fordpass app self is working.

**Comment by danielbrunt57** [comment]
Similar here in CA... can no longer register the integration with my credentials...

**Comment by ziptbm** [comment]
+1 for US

**Comment by slopemad** [comment]
So this will just be linked to issue #488 then...

**Comment by daath** [comment]
> I'm based in the EU and the integration is also not working for me since yesterday. Similar, but not the same error. Note that the URL is not .au, but .ie in my case.
> 
> Logger: custom_components.fordpass Source: custom_components/fordpass/**init**.py:228 integration: Fordpass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues)) First occurred: May 16, 2024 at 8:12:51 PM (514 occurrences) Last logged: 8:31:58 AM
> 
> ```
> 403 Client Error: Forbidden for url: https://login.ford.ie/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-IE/SelfAsserted?tx=StateProperties=eyJUSUQiOiI0MDQ2NjNkZS04MDVmLTQxMDYtYTNjZS1hNzJlMTBjMjhlMGUifQ&p=B2C_1A_SignInSignUp_EN-IE
> ```

I'm in Denmark and mine also tries to log in to ford.ie and fails ...

**Comment by thoompje** [comment]
Suddenly it's working for me again here in the Netherlands

**Comment by daath** [comment]
I tried changing const.py and set it like this:

```
REGIONS = {
    "UK&Europe": {
        "region": "1E8C7794-FF5F-49BC-9596-A1E0C86C5B19",
        "locale": "DA-DK",
        "locale_short": "DK", #Temp fix 
        "locale_url": "https://login.ford.dk"
    },
```

But I get more or less the same error:

```
2024-05-17 15:36:34.687 DEBUG (SyncWorker_4) [custom_components.fordpass.fordpass_new] https://login.ford.dk/(guid)/B2C_1A_SignInSignUp_DA-DK/SelfAsserted?tx=StateProperties=(state)&p=B2C_1A_SignInSignUp_DA-DK
2024-05-17 15:36:34.903 WARNING (MainThread) [custom_components.fordpass] 403 Client Error: Forbidden for url: https://login.ford.dk/(guid)/B2C_1A_SignInSignUp_DA-DK/SelfAsserted?tx=StateProperties=(state)&p=B2C_1A_SignInSignUp_DA-DK
2024-05-17 15:36:34.904 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for (VIN)

```

**Comment by cryogenx** [comment]
Same issue, got so excited, i had two days of using Siri to start my truck..

**Comment by daath** [comment]
I give up - it stopped working again for some reason, after I updated to Home Assistant Core 2024.5.4 ;P

**Comment by thoompje** [comment]
> I give up - it stopped working again for some reason, after I updated to Home Assistant Core 2024.5.4 ;P

Same here💀

**Comment by aminorjourney** [comment]
Happy to close this as looking through the code base I can now see that the Australian URL was used as a temporary fix. Please ignore!
