### ISSUE TITLE
403 Client Error: Forbidden for url: https://login.ford.com.au/

### ISSUE THREAD

**Issue by Next9999** [itchannel/fordpass-ha#498]
In Canada after the update of the FordPass app

This error originated from a custom integration.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:228
integration: Fordpass (documentation, issues)
First occurred: 4:32:06 PM (25 occurrences)
Last logged: 5:01:56 PM

403 Client Error: Forbidden for url: https://login.ford.com.au/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-AU/SelfAsserted?tx=StateProperties=eyJUSUQiOiI2MjdlMzZhMi01Yzg1LTRkYzItODNhYS1kYWRiNDIxZGFjNGYifQ&p=B2C_1A_SignInSignUp_EN-AU
403 Client Error: Forbidden for url: https://login.ford.com.au/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-AU/SelfAsserted?tx=StateProperties=eyJUSUQiOiIzNGZjNzNlMS0yNDdlLTQ3OGUtYTJjYS1hOGFjNWMwNzgzYjQifQ&p=B2C_1A_SignInSignUp_EN-AU
403 Client Error: Forbidden for url: https://login.ford.com.au/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-AU/SelfAsserted?tx=StateProperties=eyJUSUQiOiJmNWJhOWU2Ni1iZjA0LTQzYmItOGEwMy0xN2NkMWQxZGY1ZDIifQ&p=B2C_1A_SignInSignUp_EN-AU
403 Client Error: Forbidden for url: https://login.ford.com.au/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-AU/SelfAsserted?tx=StateProperties=eyJUSUQiOiI1OTdhMGIyMC02NTNlLTQyNjktYTljZC02ZWU0NzhhMDk1MmYifQ&p=B2C_1A_SignInSignUp_EN-AU
403 Client Error: Forbidden for url: https://login.ford.com.au/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_EN-AU/SelfAsserted?tx=StateProperties=eyJUSUQiOiIxMzZhNjZmMi1hOTMzLTQ0NGItODYyNy02OThhMDI2MWUyZjcifQ&p=B2C_1A_SignInSignUp_EN-AU

**Comment by cryptk** [comment]
Check out #488 , seems to be the same issue has already been reported

**Comment by Next9999** [comment]
Duplicate
