### ISSUE TITLE
sensor.fordpass_fuel Does not update anymore

### ISSUE THREAD

**Issue by TAGVL** [itchannel/fordpass-ha#500]
I have the app refresh interval on 900sec but still since some days the sensor.fordpass_fuel does not update anymore or not frequent which makes my charging automation worthless since it doesn’t see the correct state of charge. I now manually added this via a number helper but would be great if the sensors updates again on a normal basis. E.g at this moment the car is home with 46% but the sensors states 82% from 2 days ago.

**Comment by John-P-C** [comment]
https://github.com/itchannel/fordpass-ha/issues/488

**Comment by itchannel** [comment]
Closing as linked to #488
