### ISSUE TITLE
Lots of tinkering to get token, then KeyError.

### ISSUE THREAD

**Issue by noman1228** [itchannel/fordpass-ha#504]
WE HAVE SUCCESS!!!!!

**Comment by noman1228** [comment]
To get here from USA:
https://fordconnect.cv.ford.com/common/login/?make=F&application_id=AFDC085B-377A-4351-B23E-5E1D35FB3700&client_id=30990062-9618-40e1-a27b-7c6bcb23658a&response_type=code&state=123&redirect_uri=https%3A%2F%2Flocalhost%3A3000&scope=access

leads to resolved:
https://login.ford.com/4566605f-43a7-400a-946e-89cc9fdb0bd7/B2C_1A_SignInSignUp_en-US/oauth2/v2.0/authorize?ford_application_id=AFDC085B-377A-4351-B23E-5E1D35FB3700&country_code=USA&language_code=en-US&response_type=code&client_id=5fb91578-2ac9-476a-b8b4-e9311eab2982&scope=%205fb91578-2ac9-476a-b8b4-e9311eab2982%20openid&redirect_uri=https://fordconnect.cv.ford.com/oauth/callback

sign in -choose vehicle -  save cookies

THEN generate link with integration.

Enter URL into browser that was signed in.

Web console - get request provides location with correct token.

**Comment by noman1228** [comment]
![Untitled](https://github.com/itchannel/fordpass-ha/assets/163939/d9405f4b-f93a-4213-a4d2-d72562e481de)

**Comment by itchannel** [comment]
Nice one! I'd also recommend replacing the sensor.py with the latest 1.70 commit as I'd updated the wrong version so is missing a few sensors.
