### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by kurtSejr** [itchannel/fordpass-ha#505]
My fordpass, 0.1.68, has stopped working. I'm sure I use the correct credentials, have tested them by logging out on the mobile APP and logging in again. So username and Password is correct. Password contains both letters, numbers and a @ (total 9 characters)
I'm in Europe

Strange, it has been working after updating to latest FordPass version;

HA Installation:
Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Brugerflade 20240501.1

Any idear?

**Comment by iMelsom** [comment]
This is a known issue due to changes in how fordpass allows login. A fix is being worked on in a new version, but it is not quite ready for release yet. Please see https://github.com/itchannel/fordpass-ha/issues/488 for more information on fix development for this issue
