### ISSUE TITLE
1.70 click on website opens fordpass app

### ISSUE THREAD

**Issue by TechsavvyCNC** [itchannel/fordpass-ha#506]
When I click on website to get token it just opens fordpass app messages.  If I delete the app then click on the web page it is just blank.

**Comment by itchannel** [comment]
Please see https://github.com/itchannel/fordpass-ha/wiki/Obtaining-Tokens-(As-of-25-05-2024)

**Comment by dadalouis** [comment]
how i get 1.70?

**Comment by SquidBytes** [comment]
> how i get 1.70?

https://github.com/itchannel/fordpass-ha/tree/1.70

**Comment by Illyze** [comment]
> > how i get 1.70?
> 
> https://github.com/itchannel/fordpass-ha/tree/1.70

sorry how do you install it?

**Comment by TechsavvyCNC** [comment]
I just downloaded the 1.70 files the copied them over the other files in home assistant.  I just got it to work this morning.

**Comment by dadalouis** [comment]
Worked like a charm !!! Was I minute to look for the token but I found it
