### ISSUE TITLE
1.70

### ISSUE THREAD

**Issue by knuser666** [itchannel/fordpass-ha#512]
wanted to try version 1.70 but i cant see it in HACS :(

what are im doing wrong :)

**Comment by mattlemercier** [comment]
It's not detected. I had the same issues.
Go to branch 1.7 and copy the files manualy.

**Comment by SquidBytes** [comment]
Yes, it will need to be done manually. I added that to the Q&A in the #509 thread. I don't want to write up a tutorial or anything because it is not released yet, which is why its not on HACS.
