### ISSUE TITLE
Missing data points for Ford Expedition

### ISSUE THREAD

**Issue by MartyTremblay** [itchannel/fordpass-ha#52]
Noticing a few Ford Expedition-specific data points missing from this awesome component; specifically TPMS is of interest... Dumping my debug output for future reference.

`{'vin': 'XXXXX', 'lockStatus': {'value': 'LOCKED', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'alarm': {'value': 'SET', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'PrmtAlarmEvent': {'value': 'Null', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'odometer': {'value': 57303.0, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'fuel': {'fuelLevel': 65.543688, 'distanceToEmpty': 498.7, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'gps': {'latitude': 'xx.xxxx', 'longitude': '-xx.xxxx', 'gpsState': 'UNSHIFTED', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'remoteStart': {'remoteStartDuration': 0, 'remoteStartTime': 0, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'remoteStartStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'battery': {'batteryHealth': {'value': 'STATUS_GOOD', 'timestamp': '10-18-2020 14:59:29'}, 'batteryStatusActual': {'value': 12, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}}, 'oil': {'oilLife': 'STATUS_GOOD', 'oilLifeActual': 54, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'tirePressure': {'value': 'STATUS_GOOD', 'timestamp': '12-03-2020 20:11:46'}, 'authorization': 'AUTHORIZED', 'TPMS': {'tirePressureByLocation': {'value': 1, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'tirePressureSystemStatus': {'value': 'Systm_Activ_Composite_Stat', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'dualRearWheel': {'value': 0, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'leftFrontTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'leftFrontTirePressure': {'value': '251', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'rightFrontTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'rightFrontTirePressure': {'value': '251', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'outerLeftRearTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'outerLeftRearTirePressure': {'value': '244', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'outerRightRearTireStatus': {'value': 'Normal', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'outerRightRearTirePressure': {'value': '239', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'innerLeftRearTireStatus': {'value': 'Not_Supported', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'innerLeftRearTirePressure': None, 'innerRightRearTireStatus': {'value': 'Not_Supported', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'innerRightRearTirePressure': None, 'recommendedFrontTirePressure': {'value': 39, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'recommendedRearTirePressure': {'value': 39, 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}}, 'firmwareUpgInProgress': {'value': False, 'timestamp': '05-09-2020 17:46:48'}, 'deepSleepInProgress': {'value': False, 'timestamp': '11-13-2020 23:14:04'}, 'ccsSettings': {'timestamp': '09-19-2018 14:06:35', 'location': -1, 'vehicleConnectivity': -1, 'vehicleData': -1, 'drivingCharacteristics': -1, 'contacts': -1}, 'lastRefresh': '12-03-2020 20:11:46', 'lastModifiedDate': '12-03-2020 20:11:48', 'serverTime': '12-03-2020 21:49:32', 'batteryFillLevel': None, 'elVehDTE': None, 'hybridModeStatus': None, 'chargingStatus': None, 'plugStatus': None, 'chargeStartTime': None, 'chargeEndTime': None, 'preCondStatusDsply': None, 'chargerPowertype': None, 'batteryPerfStatus': None, 'outandAbout': {'value': 'PwPckOffTqNotAvailable', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'batteryChargeStatus': None, 'dcFastChargeData': None, 'windowPosition': {'driverWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'passWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'rearDriverWindowPos': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'rearPassWindowPos': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}}, 'doorStatus': {'rightRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'leftRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'driverDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'passengerDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'hoodDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'tailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'innerTailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}}, 'ignitionStatus': {'value': 'Off', 'status': 'CURRENT', 'timestamp': '12-03-2020 20:11:48'}, 'batteryTracLowChargeThreshold': None, 'battTracLoSocDDsply': None, 'dieselSystemStatus': None}`

**Comment by itchannel** [comment]
Will add TPMS to the 1.0.9 release

**Comment by itchannel** [comment]
Added to #54

**Comment by itchannel** [comment]
Closing as the feature is now live
