### ISSUE TITLE
Can't Login Invalid Credentials

### ISSUE THREAD

**Issue by francesco-girardi** [itchannel/fordpass-ha#527]
Hi,
when i try to add the integration and login using UK&Europe servers the login fail with invalid credentials error.
I'm sure to put in the correct one i copy and paste from a password manager.

**Comment by TheLizard** [comment]
This is on the 1.70 branch? There is already a pull request to resolve this:
https://github.com/itchannel/fordpass-ha/pull/526

**Comment by kiekerjan18** [comment]
how to get 1.70 branch in Home Assistant. I am using HACS and since 1.70 is not realeased I can't get it in. Maximum version 1.68.

**Comment by TheLizard** [comment]
This would mean to overwrite the files manually using either SSH or a file manager plugin

**Comment by francesco-girardi** [comment]
Hi i add the ford pass in version 1.7 but when i copy and paste the token url on my browser i optain the following error from ford pass login page:

![image](https://github.com/user-attachments/assets/f0da37d9-6f15-46c9-bd6e-8fca9b143999)

**Comment by TheLizard** [comment]
Probably due to changes on Ford side, it might be possible to select different regions

**Comment by francesco-girardi** [comment]
Thanks, using US region instead of Europe the login works.

**Comment by kiekerjan18** [comment]
Tried it, but I keeps saying invalid token. I am from Netherlands which seems a separate option. USA didnt do the trick for me.
