### ISSUE TITLE
Enhancement: SOC sensor

### ISSUE THREAD

**Issue by kurtSejr** [itchannel/fordpass-ha#529]
For using intelligent charging, the battery state is important, this value is hiding in "fordpass_elVehCharging" and called "State of Charge", will it be possible to have this value as a separate sensor? 
BTW: 1.70 works fine for me :-)

**Comment by TheLizard** [comment]
I believe this to be a duplicate of #465

**Comment by TheLizard** [comment]
I actually made this change in my local instance
![image](https://github.com/user-attachments/assets/1f24ba94-595e-4a5e-b4f1-e8b1fa3be700)

**Comment by kurtSejr** [comment]
Sounds great! - lookin forward to the next update :-)
