### ISSUE TITLE
Install 1.70 branch with HACS

### ISSUE THREAD

**Issue by ravermeister** [itchannel/fordpass-ha#534]
Hey, how can I install the 1.70 branch via HACS?
I can't find it in the additional version tab

Thanks in advance

**Comment by hroling** [comment]
The 1,70 branch can be found here.

https://github.com/itchannel/fordpass-ha/tree/1.70

**Comment by ravermeister** [comment]
I know, but I don't know how to use this branch with HACS

**Comment by hroling** [comment]
> I know, but I don't know how to use this branch with HACS

I installed 1.68 and ccopied this version over 1.68. That worked for me.

**Comment by gmbrown21** [comment]
> I know, but I don't know how to use this branch with HACS

I used the method outlined here, and it worked for me--and it was pretty easy:

https://github.com/itchannel/fordpass-ha/issues/488#issuecomment-2305308642

**Comment by ravermeister** [comment]
Yes that worked, sadly the new login process doesn't seem to work on Germany

**Comment by MephistoJB** [comment]
Don´t use Europe, use the US as location. That worked for me.

**Comment by ravermeister** [comment]
Yes that worked, I used Netherland instead of Europe (I'm from Germany) let's cross fingers we get not banned. 

By the way could it be that not all values for the ford puma st are measured correctly? My windows report as open but they're closed, and some other value seem wrong too.
But great work! 💪😊

**Comment by hroling** [comment]
> Yes that worked, I used Netherland instead of Europe (I'm from Germany) let's cross fingers we get not banned.
> 
> By the way could it be that not all values for the ford puma st are measured correctly? My windows report as open but they're closed, and some other value seem wrong too. But great work! 💪😊

I have the same issue with my windows. One windows is open and the rest is closed.

And issues with this. https://github.com/itchannel/fordpass-ha/issues/530

**Comment by ravermeister** [comment]
- Installation worked via https://github.com/itchannel/fordpass-ha/issues/488#issuecomment-2305308642
- registration worked as described with using Netherland instead of Europe
