### ISSUE TITLE
White screen when opening URL to login

### ISSUE THREAD

**Issue by W19wedwards91E** [itchannel/fordpass-ha#537]
When i try this 1.70 branch integration over the past few months on and off, i just hit a white screen when i copy the link from  HA to my browser. I don't get the ford login screen. 
The only difference is if i try on my phone it will redirect and pop up the ford pass app. 
I've tried Mac Chrome / Safari / Firefox and Edge on Windows Laptop but all get the same white screen with no login details. When i go to developer mode and check the elements there is a hidden message (for some reason) that says this website needs cookies enabling to use it. I checked and they are and i also added the ford login URL with direct cookie enablement closed Chrome fully and re-opened but no luck 

Is anyone able to suggest a way forward :)

**Comment by istbarp** [comment]
I am having the same issue, but if i change to netherlands or another thing, other than UK/Europe, i get the login screen

But i am from EU, so i figure i need it to be that ?

--Edit I just used the netherlands, and used my login, and then it seemed to work. All the devices/entities is in english despite the netherlands login screen (i'm from denmark)

**Comment by W19wedwards91E** [comment]
ahhh amazing!!  i never thought to try another country. Just tried and got it working :)!! thanks so much @istbarp

**Comment by istbarp** [comment]
> ahhh amazing!! i never thought to try another country. Just tried and got it working :)!! thanks so much @istbarp

No worries! I still hope my account doesn't get the "ban" like some people has gotten.
