### ISSUE TITLE
New Install .... Not able to login at at all.

### ISSUE THREAD

**Issue by paulgmcdonald** [itchannel/fordpass-ha#545]
Hi ... just installed this into my Home Assistant software.  I'm not able to login to my ford pass account.  It's saying invalid in Home Assistant configuration of FordPass device.   When I use the exact credentials on the ford website or fordpass app, it works fine.

Is this integration no longer working at all?

I'm also seeing this in the log file:

2024-11-10 16:57:48.315 WARNING (ImportExecutor_0) [py.warnings] /config/custom_components/fordpass/fordpass_new.py:263: SyntaxWarning: invalid escape sequence '\s'
  ibm_url = re.findall('data-ibm-login-url="(.*)"\s', response.text)[0]

**Comment by zchian** [comment]
i got same issue

**Comment by BobMac57** [comment]
Same as above. Was working before this latest update... ugh

**Comment by sparkman1** [comment]
I'm having this issue as well.

**Comment by nicholasmparker** [comment]
same issue

**Comment by ve6rah** [comment]
Yup, many of us in this boat.

Entering my credentials into 1.70 just gets "unknown error occurred" and I can't complete setup. despite the same credentials working just fine on the website.

**Comment by AJErazzor** [comment]
same here "Entering my credentials into 1.70 just gets "unknown error occurred" and I can't complete setup. despite the same credentials working just fine on the website."

**Comment by ve6rah** [comment]
I just tried getting the token with the developer tools in chrome and it worked for me.
I had previously been trying Brave and Firefox but neither of those worked.

So maybe try to get the token with Chrome in a private tab with all extensions disabled?

**Comment by AJErazzor** [comment]
> I just tried getting the token with the developer tools in chrome and it worked for me. I had previously been trying Brave and Firefox but neither of those worked.
> 
> So maybe try to get the token with Chrome in a private tab with all extensions disabled?

Are you Australian?  wondering if its region specific

**Comment by ve6rah** [comment]
> Are you Australian? wondering if its region specific

Canadian

**Comment by AJErazzor** [comment]
I can get the token it just fails with unknown error in HA

**Comment by ve6rah** [comment]
> I can get the token it just fails with unknown error in HA

That's exactly what happened to me when using Firefox. I would get the token, it just wouldn't work in HA. My suspicion is that it was being truncated by Firefox or something. 

Once I switched to Chrome it worked perfectly.

**Comment by AJErazzor** [comment]
> > I can get the token it just fails with unknown error in HA
> 
> That's exactly what happened to me when using Firefox. I would get the token, it just wouldn't work in HA. My suspicion is that it was being truncated by Firefox or something.
> 
> Once I switched to Chrome it worked perfectly.

I thought I would try that as you suggested and Chrome didnt include the fordapp:// prefix so I thought I would compare that token with firefox - different but perhaps thats supposed to be?

I DID GET IT TO WORK THOUGH - the instructions do say copy the RAW code, not the truncated text - I was highlighting the text in value and pasting that - which wasnt working - when I (in firefox) secelcted the location value and then right clicked and chose Copy Value - THIS WORKED

Would be great if some others who had an issue could confirm this.

**Comment by bmcomp** [comment]
Likewise I was copying the value using Edge and it was failing as an invalid token.  When I did this using Chrome it worked.

**Comment by paulgmcdonald** [comment]
Hi All ... I finally got this working.  I wasn't using the 1.7 version!  Once I downloaded and used this version ... I was able to get things working.  BTW ... I'm in Canada.
