### ISSUE TITLE
Ford Pass stopped working

### ISSUE THREAD

**Issue by jasonAspireWPG** [itchannel/fordpass-ha#58]
The integration was working but since reinstalling HA I can't get integration to work. Below is the log entry.

Logger: custom_components.fordpass
Source: helpers/update_coordinator.py:166
Integration: FordPass (documentation, issues)
First occurred: 4:35:31 PM (1 occurrences)
Last logged: 4:35:31 PM

Error fetching fordpass data: Error communicating with FordPass for 1*********KFB86523

**Comment by itchannel** [comment]
Did you reinstall HA to the same box? 
Has the integration been installed and then getting the error or are you getting that error when trying to install it entering in your details?

**Comment by pbnj4640** [comment]
I am seeing some similar results. I have not done any new installations.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:162
Integration: FordPass (documentation, issues)
First occurred: 12:20:05 PM (7 occurrences)
Last logged: 12:24:04 PM

Error communicating with FordPass for 1********LGC06114


V. 1.10 was good, since then, I am seeing this issue. If I interact with my vehicle from fordpass app, the HA entities will sync up, then eventually get dropped again.

**Comment by jasonAspireWPG** [comment]
It was installed on the same Synology Diskstation using Docker. Would it be
the move from Hass.Io to the official HA docker image?

The installation was working perfectly until this change

**Comment by itchannel** [comment]
Can I confirm you have both selected the correct region for the application. As the app dropping etc is a result of the region not being set correctly ?

**Comment by jasonAspireWPG** [comment]
I can confirm that. I reinstalled it and ensured it was set to North
America and Canada

**Comment by itchannel** [comment]
I'll install a copy of the HA docker image today/tomorrow and have a play to check as a couple of people seem to have issues with the latest docker image from HA.

**Comment by itchannel** [comment]
So I can't even sign in using the HA docker image and the integration. It appears to be an issue with the python libraries installed on the latest docker image as it's causing URL's to timeout

``` requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.mps.ford.com', port=443): Max retries exceeded with url: /api/oauth2/v1/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff731dbbd90>: Failed to establish a new connection: [Errno -3] Try again')) ```

**Comment by itchannel** [comment]
So I can fix the issue by entering the docker container and changing the DNS server in /etc/resolv.conf to point to 1.1.1.1 or some other DNS server. So it seems like a docker issue. Can anyone else who is having issues try that for me.

**Comment by itchannel** [comment]
The docker image from HA seems to have dns issue from what I can tell. So not something I can fix from my end as hardcoding an IP is a bad idea considering the fordpass API uses Azures APP gateway

![image](https://user-images.githubusercontent.com/5840973/102704707-a2f93480-42ca-11eb-9778-8994cbb980a2.png)

**Comment by sminker81** [comment]
Im getting the same error. If I reload the integration it starts working right away. About 4-8 hours later I get the error again and entities show as unavailable.

**Comment by sminker81** [comment]
I dont know how close this is to a HomeBridge plugin, but they had an update recently that addressed something similar.

**Comment by sminker81** [comment]
Is this what you are talking about changing? I can give it a whirl as long as the whole Matrix doesnt come down with it lol.

<img width="280" alt="Screen Shot 2021-01-01 at 7 46 01 PM" src="https://user-images.githubusercontent.com/76228732/103449174-240ce000-4c6a-11eb-8438-9dc3e873c708.png">

**Comment by itchannel** [comment]
@sminker81 Please try the new update and let me know if it fixes it for you

**Comment by pbnj4640** [comment]
This is working for me now.

**Comment by jasonAspireWPG** [comment]
Worked for me! Appreciate your efforts

**Comment by itchannel** [comment]
Awesome. Will close this issue now
