### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by degrashopper** [itchannel/fordpass-ha#61]
When i try to login with mij fordpass credentials and VIN number i instantly get the message that the authentication is invalid.
Fordpass is working with these credentials on my phone.

Could it be that the integration can't handle special characters in the password?

HA 2020.12.0

**Comment by itchannel** [comment]
Can I ask what special character you are using as I have special characters in mine working ok.

**Comment by degrashopper** [comment]
Yes you can. these are the characters #&^

**Comment by itchannel** [comment]
I've just changed my password to contain those symbols and it works fine. 

Can you double check your VIN and credentials is correct. Failing that you could run the debug script and look at the log file to check the response from the authorisation API as it will tell you what is wrong [debug](https://github.com/itchannel/ford_debug)

**Comment by degrashopper** [comment]
@itchannel my password was not correct... I requested a new password and now it works!! Thanks for your support and sorry for the inconvenience.
