### ISSUE TITLE
fordpass_windowPosition

### ISSUE THREAD

**Issue by Afterdark1st** [itchannel/fordpass-ha#62]
My card reports windows Open, but on focus all windows report Fully closed  

Loving the integration thx for all your hard work

**Comment by itchannel** [comment]
Can you let me know the exact value it says under the attributes. Is it "Fully_Closed" or something different?

**Comment by itchannel** [comment]
Don't worry I've identified the issue and should be fixed in 10mins

**Comment by itchannel** [comment]
Should be fixed in #63

**Comment by itchannel** [comment]
Closing this issue as it has been verified as fixed in another issue #56
