### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by oggioniale** [itchannel/fordpass-ha#67]
I try to install this add-on in my HA system (information below) but I obtain this error: "Invalid Add-on repository!"
![Screenshot 2020-12-22 at 10 11 30](https://user-images.githubusercontent.com/1393893/102871804-2b004b00-443f-11eb-9c95-64208c0a0c72.png)

## System Health

version | 2020.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4972
Installed Version | 1.9.0
Stage | running
Available Repositories | 702
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.9
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 4.4 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.8.2), File editor (5.2.0), Duck DNS (1.12.4), SSH & Web Terminal (7.8.0), Check Home Assistant configuration (3.6.0), Mosquitto broker (5.1), WireGuard (0.4.0), JupyterLab Lite (0.3.1), Node-RED (7.2.11), Home Assistant Google Drive Backup (0.102.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 1
resources | 0

</details>

**Comment by degrashopper** [comment]
You are in the wrong spot. You try to add it as an addon in the supervisor addon store. Install it via the HACS integration.

**Comment by oggioniale** [comment]
sure I was in the wrong spot!
