### ISSUE TITLE
Decimals?

### ISSUE THREAD

**Issue by DukeSkywalker** [itchannel/fordpass-ha#70]
Hi

I've been looking around but can't see if anyone else asked:

Is it possible to have values with decimals, eg battery status, I don't know if the value from ford is rounded already?

Thanks for this integration, it's awesome!

**Comment by itchannel** [comment]
Unfortunately it's not possible for the battery as the Ford API only responds with the voltage as a rounded number

```
'battery': {'batteryHealth': {'value': 'STATUS_GOOD', 'timestamp': '12-15-2020 00:35:24'}, 'batteryStatusActual': {'value': 12, 'status': 'CURRENT', 'timestamp': '12-15-2020 00:35:36'}},
```

I have done to two decimals on other values where possible

**Comment by itchannel** [comment]
Closing as not possible.
