### ISSUE TITLE
No devices/entities

### ISSUE THREAD

**Issue by Bariego6484** [itchannel/fordpass-ha#71]
Good afternoon, no entities or devices appear. In log I get this:

Logger: custom_components.fordpass
Source: helpers / update_coordinator.py: 166
Integration: FordPass (documentation, issues)
First occurred: 18:17:35 (20 occurrences)
Last logged: 18:30:59
Error fetching fordpass data: Error communicating with FordPass for XXXXXXXXXXXXX

**Comment by EvasionOfTruth** [comment]
Just added today and having the same issue

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:162
Integration: FordPass (documentation, issues)
First occurred: 2:44:53 PM (8 occurrences)
Last logged: 2:50:12 PM

Error communicating with FordPass for 1fterXXXXXXX

**Comment by EvasionOfTruth** [comment]
Odd, logged in with the phone app and now everything shows in Hass.  Not sure if timing issue or using the app helped

**Comment by Bariego6484** [comment]
I don't get it. How exactly do I clear the tokens?
Thnks

**Comment by itchannel** [comment]
A new update is coming that should fix this for niche cases like you are experiencing. Should have something rolled out by tomorrow.

**Comment by Bariego6484** [comment]
> Se acerca una nueva actualización que debería solucionar este problema para casos específicos como el que está experimentando. Debería haber lanzado algo para mañana.

**Comment by Bariego6484** [comment]
> A new update is coming that should fix this for niche cases like you are experiencing. Should have something rolled out by tomorrow.


great!!! Thanks a lot. Sorry I didn't think to close ...
