### ISSUE TITLE
Last refresh rate

### ISSUE THREAD

**Issue by canon102** [itchannel/fordpass-ha#73]
Hey There, 

Great Integration, The only issue i'm having right now is that the last refresh rate time stamp is horribly off.

fordpass_lastRefresh - 01-17-2021 12:52:58

my Current time is -01-17-2021 06:57:23

So it looks like my time zone for the refresh is off by 6 hours.

**Comment by itchannel** [comment]
@canon102 Current refresh date is in UTC time as that's what Ford supplies from the API. I'll add in a check to change the time to your local timezone from the HA config.

**Comment by canon102** [comment]
Thanks that would be great.

Another question,  Is it possible to do separate lock and unlock commands ?  The only thing I see is the lock entity toggle.

**Comment by itchannel** [comment]
The lock entity allows you to do lock/unlock, you can also lock/unlock separately using it depending on how you are displaying the entity

**Comment by canon102** [comment]
How do I do lock / unlock separately on a button card ?

**Comment by itchannel** [comment]
Local refresh time added in #77
