### ISSUE TITLE
fordpass.tracker refresh rate

### ISSUE THREAD

**Issue by Hydrooxygen** [itchannel/fordpass-ha#75]
Hi,
I figured, that the device_tracker.fordpass_tracker refreshes every 5 minutes.
Is there a posibility to change that interval?
I want to automate the garage door. And waiting 5 mins in front of it is not the solution ;)

Thanks a lot.

**Comment by itchannel** [comment]
You can call the service "fordpass.refresh_status" which will poll the car and get an update. However the more you do this the more the battery will drain so I wouldn't recommend using the fordpass tracker solely for detecting when your near home. 

Also the individual entity can be updated more often by addding the below, however it will only poll the API more often not the car.
```
fordpass:
   scan_interval: 1s
```

**Comment by Hydrooxygen** [comment]
Thank you for the info
