### ISSUE TITLE
Does FordPass give the status of a navigation request, eg. advise if the nav is set for Home?

### ISSUE THREAD

**Issue by thisisbenwoo** [itchannel/fordpass-ha#76]
Hi, 
Sorry I've been a little absent. But at least for my Explorer, everything is working the way I want (I'm not stressing it too hard). But one thing that dawned on me, is it possible, since my car already has the Nav built in, to figure out what destination is set for the Nav, and if it is (say) Home, then it can pass a notification through to HA. That way, I can calculate roughly how long it would take for me to get home (or, even better if the Nav could pass this info), and then it can signal to my wife that I'm on my way home, and that I'll be there in x minutes? 

Thanks!

**Comment by itchannel** [comment]
Unfortunately that isn't currently exposed by the Ford API so wouldn't be possible.

**Comment by thisisbenwoo** [comment]
:-( 
Oh well, woulda been nice! :-)
