### ISSUE TITLE
Odometer Reading

### ISSUE THREAD

**Issue by cmlittle** [itchannel/fordpass-ha#81]
Small nit, but after selecting "imperial" in the integration, my odometer is still reading in km, rather than miles. While I know the imperial system sucks, this is the world I live in and I'm wondering if there is anyway to fix this. Amazing integration, btw, thank you.

**Comment by itchannel** [comment]
@cmlittle you need to restart home assistant for the change to take effect once changing options 👍

**Comment by itchannel** [comment]
Closing issue as user needs to restart HA for unit change to take effect
