### ISSUE TITLE
DistanceToEmpty Attribute does not follow unit of measurement

### ISSUE THREAD

**Issue by dacmcbibs** [itchannel/fordpass-ha#83]
The distance to empty attribute for the fuel sensor doesn't follow Imperial unit of measurement.

The attribute still shows the distance in Kilometers 

Also, the fuel sensor reports values greater than 100% (104%) when the tank is full.  I'm sure this is just how fordpass is returning the value, but thought I'd mention for completeness

**Comment by itchannel** [comment]
@dacmcbibs Thanks I will change the attribute to reflect Kilometres/Miles in the next update. 

The fuel tank sender can record over up to 105% capacity I believe, I could cap it at 100% but I quite like the  idea of getting the exact measurement )

**Comment by dacmcbibs** [comment]
105%? I guess I am shorting myself when I fill up my tank ;) 
Thanks again for developing this integration!

**Comment by itchannel** [comment]
This is still on my list to change in the next release. Just been mega busy so haven't actioned it yet :)

**Comment by JacobWasFramed** [comment]
#127 This merge will address this issue.

**Comment by itchannel** [comment]
Fixed in #135
