### ISSUE TITLE
Issue dosent show my car suddenly

### ISSUE THREAD

**Issue by denperss** [itchannel/fordpass-ha#84]
![image](https://user-images.githubusercontent.com/59692230/109244773-979d1a80-77df-11eb-9c29-984e66eb8c3c.png)

Suddenly my car is not avaible, i tried to delete the device and added it again but it dosent show it :( 

i try the refresh automation but without luck..

**Comment by denperss** [comment]
is deleted the win no..

**Comment by itchannel** [comment]
Can you check your home assistant logs for me and let me know if there’s any errors.

**Comment by denperss** [comment]
Error fetching fordpass data: Error communicating with FordPass forExpecting value: line 1 column 1 (char 0)Is there any specific I should look for ?Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: itchannel <notifications@github.com> Dato: 02.03.2021  09.09  (GMT+01:00) Til: itchannel/fordpass-ha <fordpass-ha@noreply.github.com> Cc: denperss <denperss11@gmail.com>, Author <author@noreply.github.com> Emne: Re: [itchannel/fordpass-ha] Issue dosent show my car suddenly (#84) 

Can you check your home assistant logs for me and let me know if there’s any errors.

**Comment by itchannel** [comment]
Weird. Could you try deleting the fordpass_token.txt file in "custom_components/fordpass/fordpass_token.txt" and then uninstalling/reinstalling the integration. Might have a wonky token cached somewhere

**Comment by denperss** [comment]
Hi..

It worked by deleting the token file, thank u :) !


Med venlig hilsen / Kind regards




Den ons. 3. mar. 2021 kl. 11.00 skrev itchannel <notifications@github.com>:

**Comment by itchannel** [comment]
Glad it worked :)
