### ISSUE TITLE
[ENHANCEMENT] ELVeh is missing the distance to empty range

### ISSUE THREAD

**Issue by jysaloma** [itchannel/fordpass-ha#85]
Would it be possible to add similar distance to empty or range for ELVeh?
<img width="388" alt="kuva" src="https://user-images.githubusercontent.com/24212289/109306065-4a549380-7847-11eb-8158-fe4d773a5eb9.png">

**Comment by jysaloma** [comment]
In fuel this is available
<img width="395" alt="kuva" src="https://user-images.githubusercontent.com/24212289/109306262-98699700-7847-11eb-9360-b906c843fa83.png">

**Comment by itchannel** [comment]
I don’t have a electric vehicle to check on mine, are the fuel values the remaining electric range? If you have time I could get you to run a debug script which will give me the values from your car to add the function if available

**Comment by garide78** [comment]
hi, I have a kuga plug in hybrid, and would be interested in having what you requested from jysaloma in the electrical part of the car, (% of recharge, distance traveled, etc ...) 
if I can help you debug the data let me know.
 Thank you

**Comment by itchannel** [comment]
If the values are exposed by the API I'll look at adding them.

**Comment by root01** [comment]
That sounds great.

**Comment by itchannel** [comment]
Closing old ticket.
