### ISSUE TITLE
[ENHANCEMENT] status-color defined for non-normal readings

### ISSUE THREAD

**Issue by cbennett6008** [itchannel/fordpass-ha#86]
Is it possible to flag the sensors to display a status color if a non-optimal reading is detected?
for instance the tire pressure in my truck is 'STATUS_LOW' at the moment, thanks to the cold weather this month, and it sure would be nice to see that in my UI.
I know I could define a second copy of the sensor as a template sensor to do this, but I hate to have that many duplicate sensors, seems un-tidy. :)

Thanks for all you do!
Chris

**Comment by itchannel** [comment]
I don't know if it's possible to set the status color for a sensor. I know switches etc do it. But short of using a template or a custom lovelace card I don't think I can do it from a developer perspective. I may be wrong just couldn't find any documentation on it from a quick look.
