### ISSUE TITLE
Version key is missing in the manifest file

### ISSUE THREAD

**Issue by alexrasmussendk** [itchannel/fordpass-ha#87]
### New requirement for custom components

**Version key** is required in the manifest file for future support in Home Assistant otherwise it will be blocked from running.

More information: https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by itchannel** [comment]
This will be added in my next update, hopefully later this week.

**Comment by itchannel** [comment]
Added in Update 1.15
