### ISSUE TITLE
Integration not initialising

### ISSUE THREAD

**Issue by pinthenet** [itchannel/fordpass-ha#90]
I've tried to install this a few times but with no luck. I see the following messages in the log, every minute

`Mar 17 11:12:45 newgromit hass[29531]: 2021-03-17 11:12:45 WARNING (MainThread) [custom_components.fordpass] [Errno 2] No such file or directory: 'custom_components/fordpass/fordpass_token.txt'
Mar 17 11:12:45 newgromit hass[29531]: 2021-03-17 11:12:45 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for XXXXXXXXXXXXXXXXX
Mar 17 11:12:45 newgromit hass[29531]: 2021-03-17 11:12:45 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for XXXXXXXXXXXXXXXXX`

I installed fordpass-python from clarkd and the demo.py works.

Car: Kuga PHEV 2020
Region: UK/Europe
Should it work with a PHEV?

**Comment by itchannel** [comment]
There is a small bug on certain systems that can't acces the token location. If you change the line ''' self.token_location = "custom_components/fordpass/fordpass_token.txt" ''' in fordpass_new.py which can be found in "config/custom_components/fordpass/" on your system.

to ''' self.token_location = "/config/custom_components/fordpass/fordpass_token.txt" '''

it should work. I haven't added it to the release yet as waiting to test on all HA systems.

**Comment by pinthenet** [comment]
I tried "/config/custom_components/fordpass/fordpass_token.txt" & "config/custom_components/fordpass/fordpass_token.txt" with the same results – it can't find the token file (and it really doesn't exist)

I also tried /custom_compontents/fordpass/fordpass_token.txt

**Comment by pinthenet** [comment]
I took a risk & changed the path to "/home/homeassistant/.homeassistant/custom_components/fordpass/fordpass_token.txt" and it now seems to work (no errors, 1 device, 15 entities). Maybe I have a strange setup? I don't really understand the background intricacies of HA....

**Comment by itchannel** [comment]
Great glad you managed to fix it. Interesting that the path I suggested didn't work for you. Good thing I haven't pushed that update yet until I'd tested all instances :)
