### ISSUE TITLE
Missing top cealing window

### ISSUE THREAD

**Issue by denperss** [itchannel/fordpass-ha#92]
Hi.. 

Is it possible to add the top sealing (Sun light) window status ? 
currently missing :)

**Comment by goofy7264** [comment]
It also appears to have issues with the rearpassenger and reardriver windows on f-150 CrewCab.  Both report Unknow Window Position although the front windows report correctly.  This may or maynot be an API issue, but it if is, is there a way to exclude those windows so the overall sensor does not show open all the time?

Also, appears that the F-150 has one additional Window (which also may not be supported in the API) for the Rear Sliding Window (may be vehicle trim/option level dependent)

**Comment by itchannel** [comment]
@goofy7264 can you look in the door entity and let me know the exact string for "Unknown window position" you're getting. The integration should filter out unknowns but may be a new status I haven't seen.

**Comment by goofy7264** [comment]
Sure thing, here it is.  

RearDriverWindowPos
Undefined window position
RearPassWindowPos
Undefined window position

![image](https://user-images.githubusercontent.com/39275640/113503894-ae334180-9502-11eb-80ce-b35f8fab5d9a.png)

**Comment by itchannel** [comment]
Thanks. This is a weird one as the code is there to exclude windows from reporting open with the "Undefined window position" value. Will have to look into it further 

```
    elif self.sensor == "windowPosition":
                if self.coordinator.data[self.sensor] == None:
                    return "Unsupported"
                window_closed_status = [
                    "Fully_Closed",
                    "Fully_closed_position",
                    "Undefined_window_position",
                    "Undefined",
                ]
                for key, value in self.coordinator.data[self.sensor].items():
                    if value["value"] not in window_closed_status:
                        return "Open"
```

**Comment by itchannel** [comment]
I take it you're running the latest version of the integration?

**Comment by denperss11** [comment]
Yes im running the lates vers. i will update u later today with the states from the top celing windows states..

**Comment by goofy7264** [comment]
I installed via HACS and it lists ver 1.15 so I assume that's the latest version?

**Comment by denperss** [comment]
> I installed via HACS and it lists ver 1.15 so I assume that's the latest version?

This is not relevant to this bug.. 
Please create another!

**Comment by goofy7264** [comment]
> > I installed via HACS and it lists ver 1.15 so I assume that's the latest version?
> 
> This is not relevant to this bug..
> Please create another!

I responded to the question asked

> I take it you're running the latest version of the integration?

**Comment by goofy7264** [comment]
oh, so you feel that the original post I made was not relevant to the "bug" of not reporting the top "cealing" window (whatever that is).  I, apparently wrongly, assumed you were reporting an a "bug" with the window sensor so I added that the rear winodws were also a problem.  my mistake for not fully understand what a top "cealing" window was.

**Comment by itchannel** [comment]
@goofy7264 In regards to this bug. Can you please go to the developer tab in HA and send me all the values in the "State Attributes" area for the "fordpass_windowposition" sensor. As I can't replicate the issue my end so just want to see the exact sensor values you retrieve thanks.

**Comment by itchannel** [comment]
Ahh ignore me. I think I have just spotted the issue :) My bad getting mixed up with Doors and Windows lol

**Comment by itchannel** [comment]
Closing this issue as the bug relates to #97 . The actual support for the missing ceiling window is not supported by the official Ford API so there is no way of currently adding it as a sensor value.
