### ISSUE TITLE
[ENHANCEMENT] Separate Distance and Tire Pressure Units of Measure 

### ISSUE THREAD

**Issue by goofy7264** [itchannel/fordpass-ha#93]
Would it be possible to separate Distance and Tire Pressure Units of Measure.  It's quite common (in Canada) to use metric for Distance UOM but use Imperial (psi) for tire pressure UOM.  If possible it would be ideal if you could select the UOM for distance separate from the pressure.  Maybe two selections in the Integration Options?

**Comment by itchannel** [comment]
I would recommend just using a simple template sensor to convert it back to psi and display it as an entity you can use. I could change the settings but it's a small use case and would clutter up the UI for now.

**Comment by goofy7264** [comment]
> I would recommend just using a simple template sensor to convert it back to psi and display it as an entity you can use. I could change the settings but it's a small use case and would clutter up the UI for now.

I can certainly do that, I just thought since it would simply be adding a second dropdown in the Config portion (Distance Units and Pressure Units) it might be worth doing.  Thanks for the consideration.

**Comment by itchannel** [comment]
I will definitely add it to the future list as agreed it would be a nice to have. Unfortunately super busy with work commitments so haven't found the time to dedicate to this for a while.

**Comment by goofy7264** [comment]
Totally understandable.  Work and Family have to come before side projects :)

**Comment by Pepe962** [comment]
This is also the case in Australia
We use KM for distance and speed but psi for tyre pressures
