### ISSUE TITLE
Installed via HACS, but can't add integration

### ISSUE THREAD

**Issue by cjramseyer** [itchannel/fordpass-ha#94]
Have latest HA, HACS, and installed Fordpass from HACS.
Reboot HA, and process to add the integration, however, the integration doesn't show in the list.

**Comment by goofy7264** [comment]
A silly question, but you are you looking in the correct integration area (HA Configuration-->Integrations)? It is listed as FordPass.  It is not Under HACS.

![image](https://user-images.githubusercontent.com/39275640/112772335-2cbd4a00-8ffe-11eb-9a02-84572b2af90e.png)

**Comment by cjramseyer** [comment]
It is not a standard integration so must first be installed via HACS then 
added from components -- integrations.
It is NOT in the list.  Even following a reboot of HA as required once 
installed.

Regards,
CJ

**Comment by itchannel** [comment]
@cjramseyer Have you checked your HA logs to see if there is any errors, also when searching in the integration list make sure you use a capital F.

**Comment by famgrowor** [comment]
@cjramseyer Found any solution? Got the very same problem here...

**Comment by cjramseyer** [comment]
It finally showed up in integrations a couple days ago.  I added it and am adding my vehicle

**Comment by itchannel** [comment]
Good to hear it showed up. Weird that your HA instance didn't add it straight away.
