### ISSUE TITLE
Doors not showing as locked after driving (used to work at some point)

### ISSUE THREAD

**Issue by RyanEwen** [itchannel/fordpass-ha#95]
Hi there,

I have an automation that checks if the doors were left unlocked and notifies my phone. It used to work very well but after some update (not sure which) the doors never show up as locked again unless locked through the service. This means every time I get out, lock the doors (using the door handle or fob), my automation later alerts me that the doors were left unlocked. 

Ford Ranger 2019 Lariat, if it helps.

**Comment by itchannel** [comment]
Hi @RyanEwen, I've always found the Ford API to be unreliable when it comes to updating of door statuses. On my truck it updates automatically when I unlock the doors but not for locking it. 
So I have an automation which detects when my person status changes to "Home" and then sends a fordpass_refresh service request to get the latest status from the car after 10minutes being home. 
That way I get the latest update from the car.

**Comment by RyanEwen** [comment]
Interesting, I could just have it refresh the status before it notifies me. I didn't think of that.

I'll try that, thanks

**Comment by RyanEwen** [comment]
Just following up to say it works well now that I have it calling the refresh service about a minute before my timer finishes and checks on the door lock status. There's been once instance where a minute wasn't enough time between refreshing and checking, but otherwise it's been great. Thank you

**Comment by itchannel** [comment]
Glad it worked for you :)

**Comment by RyanEwen** [comment]
I just wanted to add that I updated SYNC from 3.3 to 3.4 and I suspect this is what broke things. Perhaps there's a bug in SYNC where it doesn't push the lock status like it does the unlock status?
