### ISSUE TITLE
issues with the rearpassenger and reardriver windows on f-150 CrewCab.  Both report Unknow Window Position although the front windows report correctly.  This may or maynot be an API issue, but it if is, is there a way to exclude those windows so the overall sensor does not show open all the time?

### ISSUE THREAD

**Issue by denperss** [itchannel/fordpass-ha#97]
It also appears to have issues with the rearpassenger and reardriver windows on f-150 CrewCab.  Both report Unknow Window Position although the front windows report correctly.  This may or maynot be an API issue, but it if is, is there a way to exclude those windows so the overall sensor does not show open all the time?

Also, appears that the F-150 has one additional Window (which also may not be supported in the API) for the Rear Sliding Window (may be vehicle trim/option level dependent)

_Originally posted by @goofy7264 in https://github.com/itchannel/fordpass-ha/issues/92#issuecomment-808980096_

**Comment by itchannel** [comment]
If it reports Unknown window position then the Ford API doesn't have a sensor avaliable to report the position. The integration should ignore "Unknown window position" so it doesn't report Open all the time. If it's not then there is a potential bug which I need to look into as per the original issue. 

The additional window if it doesn't show in the window sensor then it isn't supported or listed in the official API as the integration grabs any window in the doors array and parses it.

**Comment by itchannel** [comment]
@denperss @goofy7264 In regards to this bug. Can you please go to the developer tab in HA and send me all the values in the "State Attributes" area for the "fordpass_windowposition" sensor. As I can't replicate the issue my end so just want to see the exact sensor values you retrieve thanks.

It "should" catch the Undefined position in this array 

```
                window_closed_status = [
                    "Fully_Closed",
                    "Fully_closed_position",
                    "Undefined_window_position",
                    "Undefined",
                ]
                for key, value in self.coordinator.data[self.sensor].items():
                    if value["value"] not in window_closed_status:
                        return "Open"
                return "Closed"
```

However it looks like it might not be for you guys, so may be a simple spelling mistake on my part, if you can send me the attribute values from the raw sensor I can look at getting it fixed.

**Comment by goofy7264** [comment]
Here is what I got from the state_attributes

driverWindowPosition: Fully closed position
passWindowPosition: Fully closed position
rearDriverWindowPos: Undefined window position
rearPassWindowPos: Undefined window position
friendly_name: fordpass_windowPosition
icon: 'mdi:car-door'

I think the problem may be that you have "Undefined_window_position" and it's reporting "Undefined Window Position"?  not sure if the underscores are significant or not.

![image](https://user-images.githubusercontent.com/39275640/113798458-355e0080-9721-11eb-8b1e-7818cb480161.png)

**Comment by itchannel** [comment]
So where you see a space it is actually an underscore, HA just automaticly removes it. I can't see why its not working for you as that value should of hit the array and reported back as closed rather than open. 

Annoyingly my truck doesn't support window statuses so makes it harder for debugging as I get a blank array back. Only thing I can think is to add a bit of debugging, unless you know how to edit HA integrations and could look at your instance for me

**Comment by goofy7264** [comment]
IF you let me know what you need me to do, I can try and take a look at it.

**Comment by mclever** [comment]
Mine shows undefined without spaces and state is closed instead of open like yours. 

RearDriverWindowPos: Undefined_window_position
rearPassWindowPos: Undefined_window_position

**Comment by itchannel** [comment]
@mclever thanks for the feedback. This is definitely a weird issue and only seems to affect a subset of people. Will have to look into this more when I have some spare time

**Comment by studiowildcard** [comment]
I also have this same problem.![image](https://user-images.githubusercontent.com/10143893/117580899-d976f680-b095-11eb-8ede-e02a673e2e41.jpeg)

**Comment by jrapczak** [comment]
I have this same issue. ![image](https://user-images.githubusercontent.com/3497380/117580981-1ba03800-b096-11eb-8e57-2c730794feca.jpeg)

**Comment by tonesto7** [comment]
I think only vehicles with 1-touch up down buttons actually know the position of the windows.  It's why you can control the rear Windows with the key fob (this is enabled with FORScan)

**Comment by itchannel** [comment]
This should be resolved in #104 . Can you let me know if it is for you so I can close out the issue

**Comment by mclever** [comment]
> This should be resolved in #104 . Can you let me know if it is for you so I can close out the issue

No changes on mine.
rearDriverWindowPos: Undefined_window_position
rearPassWindowPos: Undefined_window_position

Do you think I need to query a refresh from the truck or drive it around for a little while?

**Comment by itchannel** [comment]
@mclever It will still show that as that is the value because those windows aren't supported. However does it now show as "Closed" for you as the overall state of the door sensor?

**Comment by goofy7264** [comment]
1.17 seems to have resolved this for me

**Comment by itchannel** [comment]
Great going to close this issue for now.
